### ISSUE TITLE
Sileo and zebra only appearing if Tweak Injection is disabled

### ISSUE THREAD

**Issue by Skribb11es** [opa334/Dopamine#100]
As the title states, I can jailbreak perfectly fine, however if tweak injection is enabled both sileo and zebra never show up. The second I turn it off however, both show up, but I am unable to actually use any tweaks.

iPhone 12 Pro Max on iOS 15.0.1

**Comment by opa334** [comment]
It can take a bit for them to show up in some instances. Maybe you just didn't wait long enough?

**Comment by Skribb11es** [comment]
I left it over night yesterday and they still never showed up.

**Comment by Cryptiiiic** [comment]
@Skribb11es disable tweaks one by one in choicy

**Comment by Liam0205** [comment]
Tested and should fix in most cases: Refresh App Registrations in TrollStore Helper and then Rebuild Icon Cache in Trollstore.

**Comment by Cryptiiiic** [comment]
No response
