### ISSUE TITLE
Updating within the app while non-jailbroken stays stuck

### ISSUE THREAD

**Issue by NotDarkn** [opa334/Dopamine#103]
Device: iPhone 11 Pro
Version (before): 1.0.1
Version (now): 1.0.2

tl;dr/summary:
When trying to use the built-in updater when you're not jailbroken, the updater gets stuck after it finishes downloading, it basically just loads for an infinite amount of time. 

Only solution I found atm was to close out of the app then manually update through the .tipa.

**Comment by opa334** [comment]
Normal behaviour, I forgot to implement this. It should open the tipa in TrollStore, this will be added in a future update.
