### ISSUE TITLE
Shell & SSH doesn't work with Dopamine 1.0.2, iOS 15.1, iPhone XR

### ISSUE THREAD

**Issue by Liam0205** [opa334/Dopamine#110]
## Environ

* iPhone XR
* iOS 15.1
* Dopamine 1.0.2

## Reproduction steps

* Jailbreak with Dopamine 1.0.2
* Install `New Term 3 Beta` from Sileo
* Open `New Term 3 Beta`
* Each time, it gives "Session Ended" in red

![IMG_0054](https://user-images.githubusercontent.com/3348485/236155698-f8c4ba7c-5fbe-4cbb-8ec0-308cfb5f9035.jpg)

BTW, the same combination of Dopamine & New Term 3 Beta on iPhone 13 Pro/iOS 15.4.1 works fine.

Also, SSH connection to the device cannot be established (with OpenSSH server installed).

**Comment by Liam0205** [comment]
I ain't installed it.

Liam Huang
From my iPhone

**Comment by Liam0205** [comment]
> Check if it works when you disable tweaks in the Dopamine app

@opa334 still not work. Test route:

1. reboot, disable tweak injection, jailbreak, open New Term 3 --- Session End, SSH not work
2. reboot, enable tweak injection, jailbreak, open Dopamine, disable tweak injection, open New Term 3 --- Session End, SSH not work

**Comment by opa334** [comment]
> > Check if it works when you disable tweaks in the Dopamine app
> 
> @opa334 still not work. Test route:
> 
>     1. reboot, disable tweak injection, jailbreak, open New Term 3 --- Session End, SSH not work
> 
>     2. reboot, enable tweak injection, jailbreak, open Dopamine, disable tweak injection, open New Term 3 --- Session End, SSH not work

Means probably wrong setuid offset? I only verified iOS 15.1.1 and 15.4.1, I assumed 15.2 - 15.3 would have the same as 15.4.1 but maybe that's not correct.

**Comment by opa334** [comment]
That's certainly weird. Try reinstalling system-cmds in Sileo.

If nothing else works, try removing jailbreak environment and then after being jailbroken, only install NewTerm3 and check if it works then.

**Comment by Liam0205** [comment]
@opa334 still not work. Test route:

1. reboot, open Dopamine, in Settings, Uninstall Jailbreak.
2. reboot
3. reset whole iPhone in System Preferences
4. Install TrollStore, Install Dopamine, Jailbreak
5. Install New Term 3 Beta in Sileo, open it --- Got Session Ended
6. Install OpenSSH (both server & client) --- SSH connection closed

**Comment by opa334** [comment]
The fact SSH doesn't work is really weird, like that should work in all cases as long as the trustcache was loaded and the daemon got started.

**Comment by Liam0205** [comment]
@opa334 Same feeling here.

So... without SSH connection and local shell, how can I check if trustcache is loaded correctly, and how can I figure out if SSH daemon get started normaly?

**Comment by opa334** [comment]
If the app doesn't error out while jailbreaking, both these things should work.

**Comment by Liam0205** [comment]
New info: MTerminal reports bus error when start.

**Comment by qnblackcat** [comment]
@Liam0205 I have the exact same issues as your. I installed `login` from this repo (http://nt994.github.io/) and it fixed the Session Ended error in Newterm 3

SSH is still broken tho

**Comment by Liam0205** [comment]
same issue could be found here:

* <https://www.reddit.com/r/jailbreak/comments/13fbuc1/help_how_do_i_fix_the_session_ended_error_in/>

**Comment by Liam0205** [comment]
> @Liam0205 I have the exact same issues as your. I installed `login` from this repo (http://nt994.github.io/) and it fixed the Session Ended error in Newterm 3
> 
> SSH is still broken tho

Thanks for the information.

I can confirm that by installing this package, New Term 3 works while MTerminal and SSH are still broken.

I was trying to trace this package, and find [the tweet](https://twitter.com/youcheng123456/status/1655779977802186753). However, it seems that the tweet is still not the origin of the package.

**Comment by Liam0205** [comment]
> Please let me know if you have the original source

sure thing

**Comment by opa334** [comment]
The root cause is that `/private/preboot/<UUID>` is not owned by root:wheel on some devices. Fix the permissions with Filza and then everything should work

**Comment by opa334** [comment]
Also DO NOT install that login package, it makes this issue 10 times worse, it does not solve anything. Remove that package, then reinstall system-cmds.

**Comment by qnblackcat** [comment]
@opa334 
Trust me, I reinstall system-cmds a dozen times but it didnt fix Newterm. Even on a fresh jailbreak where Newterm is the only package I have.


![00EFB138-5C8A-4172-A69E-420E7C37592E](https://github.com/opa334/Dopamine/assets/52943116/2c76699c-019b-48ad-af4d-d1b8f6673bef)
Does my ownership look good tho?


@

**Comment by Liam0205** [comment]
iPhone 13 Pro, wiith New Term and SSH working well: owner `root:wheel`, permissions `755`.

iPhone XR, wiith New Term and SSH broken: owner `root:wheel`, permissions `777`.

Maybe I should change `777` to `755`? Will this break SSV?

**Comment by Liam0205** [comment]
OK, `755` works. Both New Term and SSH work well now.

**Comment by opa334** [comment]
No this will not break SSV

777 is definitely wrong and is what causes the issue

755 is right

**Comment by qnblackcat** [comment]
Can confirm 755 works 👌
