### ISSUE TITLE
The Fonts folder in the mapping directory does not seem to take effect

### ISSUE THREAD

**Issue by Xuefeng122** [opa334/Dopamine#115]
The Fonts folder in the mapping directory does not seem to take effect. The font I replaced cannot take effect. Even if the user space is restarted, my device is iPhone13Pro Max, the system is 15.4.1, and I use Dopamine1.0.2

**Comment by Liam0205** [comment]
Official version of Dopamine does not provide path mapping. Hence do not ask question here. @Cryptiiiic this should be closed.

Go to @w2599's or @Liam0205's repo and post your issue.

**Comment by Liam0205** [comment]
Also, this should be a tweak in the future, not a part of jb tool itself. (I'm working on it.

**Comment by opa334** [comment]
@Liam0205 yes, see: https://github.com/opa334/Dopamine/issues/91
