### ISSUE TITLE
TrollStore, Sileo disappeared after "hide jailbreak" even after reboot

### ISSUE THREAD

**Issue by mbs0ft** [opa334/Dopamine#116]
Only solution was tap on "Refresh App Registrations" in GTA Car Tracker app that wasn't hidden and unhide jailbreak 

iOS 15.1, SE 2-nd gen, Dopamine 1.0.2

**Comment by mbs0ft** [comment]
oh also this happened after tapping unhide jailbreak and respring
why 4 empty folders, what
![IMG_4840](https://user-images.githubusercontent.com/22106304/236287240-5503c770-b488-484c-96bb-aaa2467714f0.jpg)

**Comment by Cryptiiiic** [comment]
This is normal iOS behavior, that's literally why refresh registrations exists @mbs0ft

**Comment by mbs0ft** [comment]
> This is normal iOS behavior, that's literally why refresh registrations exists

I was worried how i'm gonna unhide TrollStore and Dopamine

**Comment by Cryptiiiic** [comment]
Fyi jailed is the opposite of jailbroken, so... folder names are wrong per say

**Comment by mbs0ft** [comment]
> 
folder names are wrong per say

ik, when app/folder have long name ios stretches font and it's just ugly
