### ISSUE TITLE
No sources can be added

### ISSUE THREAD

**Issue by eieiejrjfidi** [opa334/Dopamine#118]
![9D83840E-1663-4A4F-8CAD-38704A43CF18](https://user-images.githubusercontent.com/132614115/236313972-5b1f896e-2fd8-4c98-b0b6-56426a23f4fe.png)

**Comment by eieiejrjfidi** [comment]
I trying to clean chach and rejailbreak amd no work

**Comment by Cryptiiiic** [comment]
Stop being a pirate
