### ISSUE TITLE
Demo version - Sandboxed

### ISSUE THREAD

**Issue by seanm2x** [opa334/Dopamine#119]
I just installed dopamine 1.02 for the first time on my iphone 13 pro max with ios 15.3 RC and I'm getting Demo version - Sandboxed at the bottom after opening the app. How do I fix this so I can jailbreak this device? Any ideas?

**Comment by Cryptiiiic** [comment]
Because you didn't install the correct version or didn't install it via trollstore, this is a requirement. You installed a version where the entitlements were removed. @seanm2x

**Comment by Nolan7883** [comment]
I installed the latest and it still says mismatching environment, or sandboxed
