### ISSUE TITLE
fugu15 Beta8 Dual card telecommunications and other inexplicable lack of service and signal

### ISSUE THREAD

**Issue by Myfyfy** [opa334/Dopamine#122]
During the use process, there will be inexplicable lack of service, which has been verified to be related to prison break，As shown in the figure
![1319F8BA-3C57-4D1E-9E64-0C4B947075F0](https://user-images.githubusercontent.com/17874444/236418941-9d0c4cb1-d427-4bc8-b27e-9e9642d1cfb5.png)

**Comment by Liam0205** [comment]
Disable and re-enable it from `Settings -> Cellular network -> Cellular number -> Enable this number -> Off -> On`.

See #25

**Comment by opa334** [comment]
Fugu15 Max is no longer supported. Use Dopamine.

**Comment by Myfyfy** [comment]
thank you
