### ISSUE TITLE
Missmatching environment version

### ISSUE THREAD

**Issue by GitHubNoobie** [opa334/Dopamine#125]
"the environelenbt version this device was jailbroken (0.9) mismatches the currently installed app version 1.0.2 pressing update will update the JB environement to the one of the currently installed app, uour device userspace reboot afterwards."

unfortunately it's stuck. update it's not working. stay stuck just after a clic on "update"

**Comment by opa334** [comment]
it should never say 0.9 so that means user error / you're using a leaked build.

**Comment by GitHubNoobie** [comment]
It’s not … I have downloaded thé build from this repo….

**Comment by GitHubNoobie** [comment]
Also just tried to use [Public Beta 8 (Final Beta)](https://github.com/opa334/Dopamine/releases/tag/1.0.0-beta.8). Exexpt this one now I have never downloaded any other release before the use of dopamine 1.0.2 that I got from this repo.

==>Fugu15 error : posix_spawnFailed (Result :1, erno :2)

Looking at Dopamine last 1.0.2 release please see enclosed some screenshot. It seems my phone is alrrady bootstraped. Seems to be already jailbroken. Very Very strange....

![IMG_5088](https://user-images.githubusercontent.com/39349551/236612422-0c6b5309-be96-4c9d-8509-1d7664f94792.PNG)
![IMG_5089](https://user-images.githubusercontent.com/39349551/236612435-1df24cbb-be71-496b-8351-95d24d3bb3a3.PNG)
![IMG_5090](https://user-images.githubusercontent.com/39349551/236612439-22b8923a-4298-4c5f-8e97-07646e35c2ba.PNG)
![IMG_5091](https://user-images.githubusercontent.com/39349551/236612441-bef0909c-3af2-4e34-b109-6ff338f55751.PNG)

FUGU 15 beta 8 :

![IMG_5093](https://user-images.githubusercontent.com/39349551/236612514-630b2b39-6e98-4dc8-9bb5-f2ae806a8692.PNG)
![IMG_5092](https://user-images.githubusercontent.com/39349551/236612519-2c2a6045-71af-4c45-a764-3fe2c54f08c7.PNG)

**Comment by opa334** [comment]
This is not supposed to work when you're jailbroken with Fugu15 Max. In that case you need to reboot and rejb...

**Comment by GitHubNoobie** [comment]
I have rebooted several times. And no improvement. Still thé same issue.

I think thé JB is persistent. I dont know how to remove it.

**Comment by opa334** [comment]
The problem is you need to install the jailbreak with TrollStore.
