### ISSUE TITLE
SSH doesn't work with Dopamine 1.0.3, iOS 15.4.1, iPhone 13

### ISSUE THREAD

**Issue by miosx** [opa334/Dopamine#128]
% ssh -l root -p 2222 localhost
(root@localhost) Password for root@iPhone13:
UNIX authentication refused

Can not connect, the password is correct.

**Comment by mimo1234** [comment]
same happened to me but I did download Mterminal typed sudo su it did worked

**Comment by mimo1234** [comment]
![F2F0DB1F-EF59-4966-AE5D-32BE7A733E86](https://user-images.githubusercontent.com/5606616/236680696-d25b124d-64ef-44dc-9e44-00d0144412bb.png)

**Comment by Cryptiiiic** [comment]
**PSA: Logging in as root**
Logging in as root is no longer supported. Nor is it recommended. Instead you can use the mobile user and run commands with sudo which will run them as root. You should have set your sudo password when jailbreak for the first time. (Dopamine has you do this)
Sudo is a better practice than root login. So please stop, thank you!

Closing this as its not an actual issue.

**Comment by refriedfood** [comment]
This is stupid and a catch 22, you can't modify root components via ftp. Nor does it specify ANYWHERE how or what the username is to log into--outside of root--to even run sudo. You can't use one without the other. Also, say you put in the wrong password from the beginning, what then? You can't reconfigure it without wiping completely. How would you even know how to log in if you cannot log in to begin with? This was poorly thought out.

**Comment by opa334** [comment]
Username: mobile
Password: (whatever you set on first jailbreak)

1.x versions had the ability to reset this password from the Dopamine app but 2.x currently does not.

**Comment by refriedfood** [comment]
Right, but then any tweak or application that requires non-rootless (say, terminal) will fail to install without an external shell. No? In fact, I'm willing to bet if you connect via shell and do a simple sudo updatedb it will permission fail.

*You'll have to sudo passwd root... and the file system remains read only. Isn't that pointless? How does this qualify as a jailbreak if you're read-only?

**Comment by opa334** [comment]
What? Everything works, including setting a root password. You cannot write to the root filesystem as it would brick your device, but there is also no need to ever do that.

**Comment by refriedfood** [comment]
Why would writing files to the file system as root brick the device? I literally have a phone here on 13 with unc0ver with plenty of written files to it, either by vi/ftp, you name it. This isn't a new thing. With dopamine I can't even edit the hosts file...

**Comment by opa334** [comment]
> Why would writing files to the file system as root brick the device? I literally have a phone here on 13 with unc0ver with plenty of written files to it, either by vi/ftp, you name it. This isn't a new thing. With dopamine I can't even edit the hosts file...

Yes it is a new thing in iOS 15 in case you've been living behind a rock. Also the hosts file isn't even used by the system anymore, you can install LetMeBlock and then put on inside the /var/jb filesystem.

**Comment by refriedfood** [comment]
Then I guess I have been living behind a rock, nice and sweet with a great ios that still does what I want. If what you say is true, that breaks everything. That means 90% of the debs won't work. So then if that's the case, what does this soft jailbreak have over any other file reading apps or sideloadly? It's essentially rootless.

**Comment by opa334** [comment]
> Then I guess I have been living behind a rock, nice and sweet with a great ios that still does what I want. If what you say is true, that breaks everything. That means 90% of the debs won't work. So then if that's the case, what does this soft jailbreak have over any other file reading apps or sideloadly? It's essentially rootless.

it's not a soft jailbreak, it is a full jailbreak. there is not a single thing that actually needs to write to rootfs.

**Comment by refriedfood** [comment]
Then you should have no problem answering that question? The file system isn't unlocked, therefore it isn't a jailbreak. A jailbreak literally means releasing opening the file system from its jail. This doesn't do that. Big deal.

**Comment by opa334** [comment]
> Then you should have no problem answering that question? The file system isn't unlocked, therefore it isn't a jailbreak. A jailbreak literally means releasing opening the file system from its jail. This doesn't do that. Big deal.

No, a jailbreak consists of three things: universal codesign bypass, system wide code injection and root code execution, all of which Dopamine offers.
