### ISSUE TITLE
CarPlay not opening

### ISSUE THREAD

**Issue by willieb2006** [opa334/Dopamine#130]
I’m having issues with CarPlay it never opens when jailbroken, I’ve heard snowboard is Likly issue but problem still persist after I removed snowboard completely

**Comment by willieb2006** [comment]
I figured out the issue it’s A-font when I disable it CarPlay works perfect so when I disable snowboard and a font CarPlay works great

**Comment by Cryptiiiic** [comment]
update choicy to latest, select carplay app, custom tweak configuration, deny snowboard.dylib, closing this not at all a dopamine issue
