### ISSUE TITLE
The Sileo and Zebra icons obviously don't look good. They are stretched and cut off.

### ISSUE THREAD

**Issue by daniliammo** [opa334/Dopamine#131]
Screenshot:
![F93A7325-FBC1-453C-B709-9CF6A89CD37B](https://user-images.githubusercontent.com/67186086/236695936-8226fe9d-87e2-4a56-94cb-83e8b41c9bb6.jpeg)

**Comment by sourcelocation** [comment]
Fixed in 4c5114bdf94f81baa06b5e2d7fdcedec965208e6
