### ISSUE TITLE
Shell command, /var/mobile/Containers/Data　

### ISSUE THREAD

**Issue by mickr000w** [opa334/Dopamine#133]
■Environ
・Dopamine 1.0.2
・iphone12
・iOS 15.1
 
■Reproduction Steps
・Jailbreak with Dopamine 1.0.2
・Install New Term 3 Beta from Sileo
・Open New Term 3 Beta
・cd /var/mobile/Containers/Data
・ls
ls : Operation not permitted

It was accessible in the XinaA15.

How to make it possible?

**Comment by Cryptiiiic** [comment]
Duplicate, see #81 , closing
