### ISSUE TITLE
When a password keypad appears for a mobile user, the dimming slides down.

### ISSUE THREAD

**Issue by daniliammo** [opa334/Dopamine#135]
Video:https://user-images.githubusercontent.com/67186086/236816421-cdfab464-c8cc-4437-a707-f49ccae21800.MOV
Dopamine 1.0.3

**Comment by iCrazeiOS** [comment]
smh @sourcelocation

**Comment by opa334** [comment]
where is the issue? I don't see it?

**Comment by iCrazeiOS** [comment]
> where is the issue? I don't see it?

It's more noticeable on phones imo
In the video, you can see the background of the UI shifting to the right whenever the keyboard is active
It shifts downwards on phones

**Comment by daniliammo** [comment]
> where is the issue? I don't see it?

The screen dimming slides down when the keyboard is opened. Screenshot:!![image](https://github.com/opa334/Dopamine/assets/67186086/c9ee7b40-6bcf-4dff-8c75-6eb599d601bf)

**Comment by opa334** [comment]
Will likely be implicitely fixed by Dopamine 2.0.
