### ISSUE TITLE
Termius continuously crashes

### ISSUE THREAD

**Issue by Lunascaped** [opa334/Dopamine#139]
### System Info
iOS:15.4.1
Device: iPhone 12 Pro Max
Previously jailbroken with Fugu 15 Max: No

### Issue
Once jailbroken with Dopamine (latest version), I can no longer open Termius and it crashes constantly in the background. ([Crash logs](https://paste.lunascape.gay/raw/snake-eel-monkey))

This started occurring after installing OpenSSH, but continues to occur after removal, hiding the jailbreak, and rebooting userspace. It also occurs after uninstalling and reinstalling Termius. I am not sure what the cause of this could be. I have no tweaks installed except NewTerm, frida-server, and OpenSSH.

**Comment by Lunascaped** [comment]
Just saw your comment update, I do not know why else this would occur since this only happened after jailbreaking with Dopamine even after using no tweaks.

**Comment by opa334** [comment]
As far as I know this is jailbreak detection. Using Choicy to disable tweaks works.
