### ISSUE TITLE
Screen light goes to incredibly low after a soft reboot like updating ElleKit or Dopamine

### ISSUE THREAD

**Issue by oOJohn6Oo** [opa334/Dopamine#143]
I'm using 12mini, 15.4.1, and it happens even on the latest 1.0.4 Dopamine and the latest ElleKit.

Adjusting the brightness in the control center has no effect.

But after a respring, screen light back to normal.

**Comment by julictus** [comment]
Exactly my case. If I need to attach any log, please tell me where can I locate it

**Comment by opa334** [comment]
This is most likely a stock issue. My device shows this behaviour too but it's only for like a second or two, after that the brightness goes back up. I assume there might be a bug where it's not able to get it back up.

**Comment by oOJohn6Oo** [comment]
This issue has been resolved since upgrading Ellekit to version 1.0(or the previous version)
