### ISSUE TITLE
iPad Dock Style tweaks = safe mode respring

### ISSUE THREAD

**Issue by Vorshim92** [opa334/Dopamine#147]
Hello dear Opa! Sorry for disturbing but I am at my wit's end xD
I tried everything but i keep having problems so I think you (and the other) have to know about this problem. I don't know if this problem it's related just to my freebuds bluetooth. I don't have this problem with other bluetooth devices... I will try with my old airpods as soon as possible. 
Initially I was using NicebarX tweak and so I was thinking the problem is something about that tweak. I also wrote to the developer but he doesn't seems to understand my request xD (just answer to my email with "yes" xD) but after discover that I have the same problem with every ipad dock tweaks (like DockController or FloatingDockXVI) I imagine that there is something that maybe you can undestand.

The problem is that I have respring to Safe Mode when I open apps after I connected my freebuds and the cause is the Ipad Style Dock...
to be precise, this part here:
![photo_2023-05-09_12-31-05 (3)](https://github.com/opa334/Dopamine/assets/7747380/3cee4dbf-c398-4ddc-baab-4e8de47e68ea)

in NiceBarX when I activate it a pop-up appears saying this:
![photo_2023-05-09_12-31-05 (2)](https://github.com/opa334/Dopamine/assets/7747380/55b4a2a7-6e63-474a-9b9b-c936b5f4864e)
I don't know what it means but here on the Settings - General I already try to disable handoff and airplay but nothing changes.
![photo_2023-05-09_12-50-33](https://github.com/opa334/Dopamine/assets/7747380/c41bd692-47cc-48d0-bf39-72c17e311a75)

any suggestions? :'( I can do without it but if there is something that can be done that would be great

**Comment by opa334** [comment]
From the looks of it, this really does not have anything to do with Dopamine, also no clue, sorry.
