### ISSUE TITLE
Random restart bug caused by bluetooth headset

### ISSUE THREAD

**Issue by Y1083098693** [opa334/Dopamine#152]
If you open the music app on the phone after connecting the Bluetooth headset, such as Netease Cloud Music, the phone will directly restart to safe mode
![Uploading 14665C56-D6B3-4939-9905-5F176E37D693.png…]()

**Comment by Y1083098693** [comment]
It is worth mentioning that I also encountered this bug on xina15

**Comment by opa334** [comment]
Sounds like a tweak issue to me

**Comment by Y1083098693** [comment]
> Sounds like a tweak issue to me

So, is there any hope of solving this bug in the next version?
