### ISSUE TITLE
Termius crash on launch.

### ISSUE THREAD

**Issue by midkin** [opa334/Dopamine#155]
After jailbreaking with Dopamine 1.0.4 the "Termius" app from AppStore crashes on launch.

Any solutions?

App url:
https://apps.apple.com/gr/app/termius-terminal-ssh-client/id549039908

**Comment by opa334** [comment]
Duplicate of #139

**Comment by ilizhu** [comment]
Install the Choicy Tweak  from "[opa334's Repo](https://opa334.github.io)" and disable tweak injection into the "Termius" app
