### ISSUE TITLE
CarPlay causes panic.

### ISSUE THREAD

**Issue by nintendowii111** [opa334/Dopamine#16]
Apple CarPlay causes a panic on Beta 4, iPhone 13 Pro Max, iOS 15.4.

**Comment by Vorshim92** [comment]
yes. me too. 15.4 iPhone 12

**Comment by The65Dude** [comment]
Same here iOS 15.3 iPhone 12

**Comment by Ijustplaymc** [comment]
update to beta 7, fixed it for me

export repos and tweak list!!! you will have to reinstall env due to switching to sileo stable

**Comment by HuChundong** [comment]
remove snowboard

**Comment by jecoteco** [comment]
Same on iPhone 12 Pro Max on iOS 15.4.1

**Comment by 20ksaul** [comment]
Also have the problem. Removed Snowboard but problem still persists.

**Comment by Tawnee323** [comment]
> Also have the problem. Removed Snowboard but problem still persists.
> 
> Public Beta 1. iPhone 13 Pro Max 15.3

Why are you using Public Beta 1? Thats probably why.

**Comment by Vorshim92** [comment]
with beta 8 and snowboard icon pack disabled it works perfectly. so I create a shortcut automations where I disable the theme when Carplay is connected and viceversa with ssh script using "snowboardutil" command.
like this:
![photo_2023-04-27_01-43-57](https://user-images.githubusercontent.com/7747380/234725581-f9630952-1403-465d-95af-4529cd8d6edc.jpg)

snowboardutil -u /theme/path/     DISABLE THEME
snowboardutil -t /theme/path/     ENABLE THEME

**Comment by opa334** [comment]
this should already be fixed in upstream, if this still happens in the final release when that's out, open another issue
