### ISSUE TITLE
Using Bluetooth earphones raises the possibility of experiencing kernel crashes.

### ISSUE THREAD

**Issue by invalidunit** [opa334/Dopamine#161]
When connecting Bluetooth earphones (such as AirPods), the probability of experiencing a kernel crash increases. Several of my friends have had their devices suddenly restart while wearing earphones and listening to music. 
Here is the log of my crash.
[panic-full-2023-05-12-090803.000.ips.txt](https://github.com/opa334/Dopamine/files/11458649/panic-full-2023-05-12-090803.000.ips.txt)

**Comment by Cryptiiiic** [comment]
Duplicate of #152

**Comment by invalidunit** [comment]
> Duplicate of #152

However, their issue involved entering safe mode, while my problem is a kernel crash and subsequent restart, so I don't think it's the same problem.

**Comment by Cryptiiiic** [comment]
even if its not, spinlock panic is not a planned fix
