### ISSUE TITLE
Apple Pay doesn't work?

### ISSUE THREAD

**Issue by mimo1234** [opa334/Dopamine#164]

**Comment by Cryptiiiic** [comment]
Provide more context please no description is entirely unhelpful

**Comment by mimo1234** [comment]
Sorry guys when I double click to pay in the store doesn't do anything and the wallet app just crash till I have to reboot user space to work again.

**Comment by Cryptiiiic** [comment]
@mimo1234 just tested apple pay on my heavily tweaked dopamine works fine for me so you will have to narrow down what tweak is breaking it.

**Comment by opa334** [comment]
can't reproduce
