### ISSUE TITLE
Notifications don’t work

### ISSUE THREAD

**Issue by sshrmr** [opa334/Dopamine#17]
When in jailbroken state, most of notifications, like WhatsApp or Telegram dont work. Have to open the app everytime for them to appear.

iOS 15.4.1, i have all the jb dependencies and Ampere, IAPStore, Shadow and Choicy installed, that’s all. 

Tried beta 5, 6, tried last beta 7 version - still.

**Comment by Ijustplaymc** [comment]
whats your ios versiob? installed tweaks and repos? What beta version?

**Comment by sshrmr** [comment]
> whats your ios versiob? installed tweaks and repos? What beta version?

Updated the info. U think repos can affect notifications?🧐

**Comment by Ijustplaymc** [comment]
> > whats your ios versiob? installed tweaks and repos? What beta version?
> 
> 
> 
> Updated the info. U think repos can affect notifications?🧐

some repos rehost the procursus debs and may not be the correct version or whatever

u couldve installed a weird version of something from not the official source and it could've caused issues but idk

**Comment by sshrmr** [comment]
Fixed in beta 8
