### ISSUE TITLE
AppStore doesn't work on Dopamine 1.0.5

### ISSUE THREAD

**Issue by jakche** [opa334/Dopamine#170]
Tried to reboot iPhone, tried to reboot Userspace, respring... I cannot download new apps from the AppStore, even when not jailbroken. 
[Example video](https://streamable.com/9apzje)

**Comment by opa334** [comment]
The only known fix for this is to make a backup, reset device in settings, restore backup.

**Comment by jakche** [comment]
Is that a permanent fix or intel next time I jailbreak, why does this happen?
> The only known fix for this is to make a backup, reset device in settings, restore backup.

**Comment by opa334** [comment]
It's some sort of obscure file permission issue, no it should not happen again, no idea what triggers it
