### ISSUE TITLE
cant't process jailbreak

### ISSUE THREAD

**Issue by qq2519157** [opa334/Dopamine#175]
device ： M1  iPad Pro 15.4.1  

first,I used Dopamine 1.0.2 ,it is worked for me ,but after i installed the  latest SnowBoard ,it is very caton,i cant't entry to sileo to uninstall it .so I reboot my ipad. after that ,i have never success to jailbreak my ipad again.even i changed the latest Dopamine.
it is show :
  hello from xxx server 
  my UID is 0
  my GID is 0
  xxxxx          ------->.    there is only oneline info. after that my ipad will be reboot. try to jailbreak again,it will be reboot after that info again.

i try to jailbreak with airplane mode，but is ineffective.

**Comment by Cryptiiiic** [comment]
Airplane mode is essentially useless, don't report issues if you are using old versions of dopamine, this wastes everyone's time.

I'm pretty sure the success rate on m1 is really really bad. Has not been investigated yet. @qq2519157

**Comment by qq2519157** [comment]
@Cryptiiiic I used the latest version on my iPhone 13 Pro，so I want use it on my M1 iPad Pro，but It doesn't seem to have a high success rate，after reboot i've never success jailbreak anymore

**Comment by Cryptiiiic** [comment]
Repeat... I'm pretty sure the success rate on m1 is really really bad. Has not been investigated yet.

**Comment by qq2519157** [comment]
well，Pray for success next time
