### ISSUE TITLE
Dopamine won’t process jailbreak just restarting

### ISSUE THREAD

**Issue by yosreased** [opa334/Dopamine#177]
i iPhone 11 Pro Max 15.0.1
https://github.com/opa334/Dopamine/assets/48576367/1274089c-3f28-4f70-bace-660d8892c8ea

All things Was fine on 1.0.2 until updated to 1.0.5 and now wouldn’t get into jailbreak mood .
tried so many times continually, every time won’t complete and restart.
Tried with tweak inject and without… all the same situations won’t respiring just restart
even tried so many times to remove jailbreak and reinstall again but with nothing 😔

To be clear
I was on Uncover Jailbreak ios (14.3) ( FutureRestore ) and suddenly boot-loop happened and forced me to restore & update to ( 15.0.1 ) that is my current version now
I hope you guys help me , Thanks

**Comment by opa334** [comment]
Are you sure jailbreaking with tweaks did not work? There is currently an issue with Shadow jailbreak detection bypass tweak where it makes Dopamine not able to realize the device is jailbroken. Disabling tweaks being broken might be a separate issue, will test soon.

**Comment by yosreased** [comment]
> Are you sure jailbreaking with tweaks did not work? There is currently an issue with Shadow jailbreak detection bypass tweak where it makes Dopamine not able to realize the device is jailbroken. Disabling tweaks being broken might be a separate issue, will test soon.

I don’t have Shadow tweak and I did use it before. 👉 No jailbreak while it’s say ( Device is bootstrapped
Success rate: 100.0% (15/15) !!!!🤔😔😔.
![Uploading B7FB2903-5CEA-4FBB-A5C9-FEB007A49D7B.png…]()

**Comment by dollarystem** [comment]
delete everything from /jb/Application opa pretends there is no such problem

**Comment by yosreased** [comment]
> delete everything from /jb/Application opa pretends there is no such problem
I can’t delete anything on jb folder 
![E0E98EF4-2345-4643-88DF-A518C6F2C6D5](https://github.com/opa334/Dopamine/assets/48576367/2b757333-db55-4cf8-85cd-29b6126897ab)
![6ED8E675-0AF7-4765-A8F8-C14BB70C2D43](https://github.com/opa334/Dopamine/assets/48576367/2c30adc3-460f-4c05-8bd0-0f6c70306690)

**Comment by dollarystem** [comment]
> > delete everything from /jb/Application opa pretends there is no such problem
> > I can’t delete anything on jb folder
> > ![E0E98EF4-2345-4643-88DF-A518C6F2C6D5](https://user-images.githubusercontent.com/48576367/242942873-2b757333-db55-4cf8-85cd-29b6126897ab.png)
> > ![6ED8E675-0AF7-4765-A8F8-C14BB70C2D43](https://user-images.githubusercontent.com/48576367/242942883-2c30adc3-460f-4c05-8bd0-0f6c70306690.png)

1) Download and Install Xina 1.1.8 from TrollStore and hit Jailbreak it will proccess it and it will work with Dopamine
2) You dont need Xina, Reboot, Go to Xina settings hit safe mode hit jailbreak
3) Now you can delete everything from /var/jb/Application!!!! but don't do it since there will be nothing because you are on Xina so
4) Go to /private/preboot/(YOUR SPECIAL ID)/jb-(some letters)/procursus/Application and delete every file inside there
5) If you need TrollStore version of Sileo until Opa fixes it, I can give it to you and Zebra too

**Comment by opa334** [comment]
?????????????????????????????????

Never mess with paths directly, just hit "Remove Jailbreak" in the Dopamine app under settings when not jailbroken.

**Comment by yosreased** [comment]
> > > delete everything from /jb/Application opa pretends there is no such problem
> > > I can’t delete anything on jb folder
> > > ![E0E98EF4-2345-4643-88DF-A518C6F2C6D5](https://user-images.githubusercontent.com/48576367/242942873-2b757333-db55-4cf8-85cd-29b6126897ab.png)
> > > ![6ED8E675-0AF7-4765-A8F8-C14BB70C2D43](https://user-images.githubusercontent.com/48576367/242942883-2c30adc3-460f-4c05-8bd0-0f6c70306690.png)
> 
> 1. Download and Install Xina 1.1.8 from TrollStore and hit Jailbreak it will proccess it and it will work with Dopamine
> 2. You dont need Xina, Reboot, Go to Xina settings hit safe mode hit jailbreak
> 3. Now you can delete everything from /var/jb/Application!!!! but don't do it since there will be nothing because you are on Xina so
> 4. Go to /private/preboot/(YOUR SPECIAL ID)/jb-(some letters)/procursus/Application and delete every file inside there
> 5. If you need TrollStore version of Sileo until Opa fixes it, I can give it to you and Zebra too

I tried everything with Xina15 and Dopamine and nothing !!!!😔😔😔
I thought can use Xina15 instead of Dopamine cause it’s jailbreak very easy and fast activation
But not allowing any tweak to be injected .
And tried to remove Dopamine files u said about  but as opa334 said just remove jailbreak and done . I tried all ways but all the same results.
I think I have the hole files of Uncover jailbreak that was on phone on ios 14.3 cause when happened i did restore my old backup cause all my data was gone, so all Uncover jailbreak files still on it till now .
Now i removed Both jailbreak Xina15 & Dopamine but after all this when open some apps won’t work like still there jailbreak files. Even tried reinstall but still not work.
I don’t know what to do 😔😔

**Comment by yosreased** [comment]
> ?????????????????????????????????
> 
> Never mess with paths directly, just hit "Remove Jailbreak" in the Dopamine app under settings when not jailbroken.

Is there anything can do to remove all jailbreak files without restore or losing data . So I can start fresh with Dopamine ???

**Comment by opa334** [comment]
> > ?????????????????????????????????
> > Never mess with paths directly, just hit "Remove Jailbreak" in the Dopamine app under settings when not jailbroken.
> 
> Is there anything can do to remove all jailbreak files without restore or losing data . So I can start fresh with Dopamine ???

The thing you quoted has the solution
