### ISSUE TITLE
Not able to jailbreak

### ISSUE THREAD

**Issue by PatrikPercinic** [opa334/Dopamine#178]
I have been trying to jailbreak my iPhone on every public version of Dopamine, the results are always the same.
Some attempts to jailbreak cause the device to boot for a long time (tries to boot then restarts while booting) before returning to ios.
Those times when the device takes longer to boot change the success ratio but no jailbreak is achieved ( the button always says jailbreak).
I have had hundreds of attempts to jailbreak across versions, removing jailbreak, turning tweak injection on/off, restarting/not restarting before jailbreak attempts but nothing seems to work.
I have attached some panic and reset logs. I have more logs if needed.
Thank you.
[Logs.zip](https://github.com/opa334/Dopamine/files/11511777/Logs.zip)

**Comment by Cryptiiiic** [comment]
Never seen the kernel data or static panics but the userspace panic will be mitigated in the next release. For now you can Jailbreak while holding volume up to enter safemode then you will have to diagnose which tweak is bad.

**Comment by PatrikPercinic** [comment]
@

**Comment by opa334** [comment]
Likely caused by you having installed Sileo or Zebra via TrollStore, remove it from there.
