### ISSUE TITLE
Re-Jailbreak is impossible

### ISSUE THREAD

**Issue by 1abd135** [opa334/Dopamine#181]
After reboot dopamine crashs and my phone start to showing a black screen with no response and I forced to reboot again only by power buttons

Dopamine works only when I delete environment

**Comment by 1abd135** [comment]
I have find the cause of crash
( dynamicpeninsula ) tweak is the cause of crash

Before dopamine get reboot userspace I've closed it and open filza ( via trollstore ) and tried to delete dynamicpeninsula's dylibs and then I reboot userspace and issue fixed

**Comment by Cryptiiiic** [comment]
Its a simple solution in the future, hold volume up while jailbreaking to enter safemode then disable or remove the bad tweak
