### ISSUE TITLE
When trying to SSH - UNIX authentication refused

### ISSUE THREAD

**Issue by authrequest** [opa334/Dopamine#182]
iPhone 12 Pro on 15.4.1 using Dopamine 1.0.5
I have installed openSSH from Procursus but I cannot SSH into my iphone

I have tried using iproxy as well but still same error
When using NewTerm on the iPhone and issue `sudo su` I am met with the same error.

**Comment by Cryptiiiic** [comment]
**PSA: Logging in as root**
Logging in as root is no longer supported. Nor is it recommended. Instead you can use the mobile user and run commands with sudo which will run them as root. You should have set your sudo password when jailbreak for the first time.
Sudo is a better practice than root login.

**Comment by SuFu123** [comment]
but still I cannot authenticate when I login as mobile

**Comment by geekbyter** [comment]
running into the same issue at Dopamine 2.1.7.11.

I use  `ssh mobile@x.x.x.x`  ，success connected，and use  `sudo passwd root`   , it's worked fine, in root mode
