### ISSUE TITLE
App wont open

### ISSUE THREAD

**Issue by UpperType** [opa334/Dopamine#183]
The app will not open, same problem with another Semi-Jailbreak (Xina) guessing the version I am on is not supported, iOS 15.0 (19A5281H). Anyway, support could be added?

**Comment by opa334** [comment]
Any crash log?

**Comment by UpperType** [comment]
I do not have a crash log, but here is a video to hopefully understand more. https://youtube.com/shorts/195LIB3G9-c?feature=share

**Comment by Cryptiiiic** [comment]
1.0.3 is outdated

**Comment by opa334** [comment]
crash log should be in settings... just send it here

**Comment by UpperType** [comment]
Here you go

**Comment by UpperType** [comment]
[dopamine.txt](https://github.com/opa334/Dopamine/files/11550266/dopamine.txt)

**Comment by UpperType** [comment]
> 1.0.3 is outdated

Does the same exact thing on the latest, I think it just has to do with the beta and Dopamine not being compatible.

**Comment by opa334** [comment]
Well it's a SwittUI problem @sourcelocation seems like some APIs used do not exist on 15.0 betas

**Comment by UpperType** [comment]
> Well it's a SwittUI problem @sourcelocation seems like some APIs used do not exist on 15.0 betas

Sadly, something happened when XINA15 came out and it was just not fixed :/ hopefully, the APIs get updated with 15.0 betas, feel free to DM me if you need a test device.

**Comment by UpperType** [comment]
Is there a chance this will be fixed? Really wanna jailbreak but if theres no chance ill be moving too iOS 16.

**Comment by opa334** [comment]
I will look into it for the next update

**Comment by Cryptiiiic** [comment]
https://github.com/opa334/Dopamine/actions/runs/5192489184

@UpperType please test the build linked in this run

**Comment by opa334** [comment]
Unfortunately this doesn't seem to be solvable, I really tried though, but apple fucked this beta up hard.

**Comment by opa334** [comment]
Might get fixed by Dopamine 2.0, although not a priority.
