### ISSUE TITLE
Need help on userspace reboot issue

### ISSUE THREAD

**Issue by bgli100** [opa334/Dopamine#187]
Hi, I am porting permaflex (https://github.com/shiftcmdk/PermaFlex) to Dopamine (1.0.5), and encountered a userspace reboot issue.

Situation:
1. Currently it works if no userspace reboot happen. When I install the tweak via theos/Sileo and it works after a respring. 
2. If an userspace reboot happens with tweak installed + tweak injection enabled, device stuck on apple logo for 1-2 minutes and eventually fully reboot.
3. If tweak gets uninstalled and/or tweak injection disabled then userspace reboots work.

Need help on:
1. Do you have idea of what could possibily go wrong? I guess the tweak might hooked something it shouldn't touch but can't figure out what it is.
2.  How can I diagnose this? 

p.s. tried to print a log of hooked processes upon userspace reboot, here is what I got: 
com.opa334.Dopamine
/var/containers/Bundle/Application/<uuid>/Dopamine.app/Dopamine
<- this is when I pressed the userspace reboot button
com.apple.springboard
/System/Library/CoreServices/SpringBoard.app/SpringBoard
com.apple.Preferences
/Applications/Preferences.app/Preferences
com.apple.springboard
/System/Library/CoreServices/SpringBoard.app/SpringBoard
com.apple.springboard
/System/Library/CoreServices/SpringBoard.app/SpringBoard
<- device reboots here

**Comment by opa334** [comment]
Try uncommenting all NSLog calls. If you try calling that inside logd itself it will make the process stuck. Other than that, no idea.

**Comment by bgli100** [comment]
> Try commenting out all NSLog calls. If you try calling that inside logd itself it will make the process stuck. Other than that, no idea.

Tried and it still not work :(

Found a few logs in settings, seems watchdog killed a few SpringBoards due to timeout, but the problem still present even I commented out everything it does inside SpringBoard (including NSlogs).

**Comment by opa334** [comment]
https://github.com/shiftcmdk/PermaFlex/blob/master/Tweak.xm#L243 Instead of this, use this https://github.com/opa334/Choicy/blob/master/Tweak.x#L45

**Comment by bgli100** [comment]
> https://github.com/shiftcmdk/PermaFlex/blob/master/Tweak.xm#L243-L245 Instead of these, use these https://github.com/opa334/Choicy/blob/master/Tweak.x#L40-L55

Fixed using the save variant but no lock :-(

P.S. My modifications were available via this fork:
https://github.com/bgli100/PermaFlex

**Comment by bgli100** [comment]
> Also I feel like this is only supposed to be called for SpringBoard but the logic is wrong and it will be called for everything that's an app https://github.com/shiftcmdk/PermaFlex/blob/master/Tweak.xm#L261

It works correctly but it is bad code. I re-structured this part.
The method ``initForSpringBoard`` checks bundle identifier again inside itself and runs if it is springboard. Redundent.

**Comment by bgli100** [comment]
Update:

It seems SpringBoard is not related to the fault. I played with the .plist file and found if the tweak injects to any of the following 2 bundle, userspace reboot fails (now sure why, it fails when the tweak does not run anything):

com.apple.UIKit
com.apple.security

But it works when injecting both com.apple.springboard and com.apple.AdSupport.

At least I have a partial fix now

**Comment by opa334** [comment]
I will test this soon. You probably make some daemon lock up.

**Comment by dollarystem** [comment]
I had similar issue and this fixed it, please try and if it helps you Opa is going to finally fix this issue!!

1)Download and Install Xina 1.1.8 from TrollStore and Filza Trollstore edition and hit Jailbreak it will proccess it and it will work with Dopamine
2)You dont need Xina, Reboot, Go to Xina settings hit safe mode hit jailbreak
3)Now you can delete everything from /var/jb/Application!!!! in Filza but don't do it since there will be nothing because you are on Xina so
4)Go to /private/preboot/(YOUR SPECIAL ID)/jb-(some letters)/procursus/Application and delete every file inside there
If you need TrollStore version of Sileo until Opa fixes it, I can give it to you and Zebra too

**Comment by opa334** [comment]
> I had similar issue and this fixed it, please try and if it helps you Opa is going to finally fix this issue!!
> 
> 1)Download and Install Xina 1.1.8 from TrollStore and Filza Trollstore edition and hit Jailbreak it will proccess it and it will work with Dopamine 2)You dont need Xina, Reboot, Go to Xina settings hit safe mode hit jailbreak 3)Now you can delete everything from /var/jb/Application!!!! in Filza but don't do it since there will be nothing because you are on Xina so 4)Go to /private/preboot/(YOUR SPECIAL ID)/jb-(some letters)/procursus/Application and delete every file inside there If you need TrollStore version of Sileo until Opa fixes it, I can give it to you and Zebra too

you really want to get blocked, do you?

**Comment by dollarystem** [comment]
> > I had similar issue and this fixed it, please try and if it helps you Opa is going to finally fix this issue!!
> > 1)Download and Install Xina 1.1.8 from TrollStore and Filza Trollstore edition and hit Jailbreak it will proccess it and it will work with Dopamine 2)You dont need Xina, Reboot, Go to Xina settings hit safe mode hit jailbreak 3)Now you can delete everything from /var/jb/Application!!!! in Filza but don't do it since there will be nothing because you are on Xina so 4)Go to /private/preboot/(YOUR SPECIAL ID)/jb-(some letters)/procursus/Application and delete every file inside there If you need TrollStore version of Sileo until Opa fixes it, I can give it to you and Zebra too
> 
> you really want to get blocked, do you? your bs has NOTHING to do with this issue so keep it out of it please

I mean if this fix works for many people, than I might be just right, why don't you consider that?

**Comment by dollarystem** [comment]
Right now Im flawless Dopamine user with Trollstored all apps because of this issue and its fine

**Comment by Cryptiiiic** [comment]
the real question is when did we even ask, we didn't

**Comment by bgli100** [comment]
no successful checkins from backboardd since load
service: backboardd, no successful checkins since load (180 seconds ago)
service: mediaserverd, no successful checkins since load (180 seconds ago)
service: logd, total successful checkins since load (180 seconds ago): 19, last successful checkin: 0 seconds ago
service: thermalmonitord, no successful checkins since load (180 seconds ago)
service: runningboardd, no successful checkins since load (180 seconds ago)
service: wifid, total successful checkins since load (180 seconds ago): 13, last successful checkin: 0 seconds ago


This panic was prevented by Dopamine and jailbreakd triggered a userspace reboot instead.

**Comment by bgli100** [comment]
Tried to add com.apple.UIKit back in 1.1 and it seems Dopamine collects more info on failure now.
Not sure if it helps or gives hint on what I am breaking. (Or, how to avoid injecting those deamons?)

**Comment by bgli100** [comment]
Figured out the issue.

1. A silly mistake, I used theos' default SDK (for 14.5) for compiling tweak which is intended for 15.0+.
2. Tweak should have BOTH `arm64` and `arm64e` for `ARCH`. It is not gonna work if you only have one.

By viewing crash log of Mail/News app, it seems dyld refuse to work with such dylibs and choose to crash (not sure if it is the same issue for userspace reboot).
