### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by karlvoigt** [opa334/Dopamine#191]
I've been using Dopamin for about a week after switching from Xina and although I have had some irritating random reboots, nothing major. Tonight however, the phone randomly respringed and hung on the respring logo with audio still continuing to play via airpods. After a while I decided to reboot the phone manually. At first the restore iphone screen popped up (phone was plugged in to official apple wall brick and not laptop) then after I rebooted again, the lock screen appeared. As soon as I logged in however, the phone rebooted again. It appears I am in a bootloop where I cant get past the lock screen.

The phone was locked when this happened, with youtube playing in the background on a sideloaded you+ app if this is of any use. I received a low storage notification just before the bootloop started, so this might have had an affect.

I don't expect that there will be any fix except restoring, but I thought I should open an issue as it is mentioned that there are no known cases of Dopamine causing a bootloop.

Some extra info:
No changes to the filesystem were made by myself (with the exception of running the latest rootless compatible version of iCleaner)
Very few tweaks were installed (all checked to be compatible with rootless jailbreaks before installing).

**Comment by opa334** [comment]
Yeah low storage bootloop is known and a stock issue. It might be worth to keep your phone rebooting for a few days and hope it fixes itself, it sometimes does.

**Comment by Ijustplaymc** [comment]
If you cant get past the lockscreen, try opening camera (swipe to the side), tapping photos to unlock the phone, open controlcenter and hold wifi icon, now tap more settings and now you are in settings and can delete apps to save storage!
