### ISSUE TITLE
After switching from Xina back and forth I got an issue.

### ISSUE THREAD

**Issue by dollarystem** [opa334/Dopamine#193]
After switching from Xina back and forth I got an issue. So if I got anything in /prucursus/Applications of any of the 2 jailbreaks I will get a bootloop. Soo to use Dopamine I had to figure out myself this fix.

1)Dopamine JB, Hard reboot out of bootloop
2) Safe mode xina and using Filza trollstored in order to clean /Applications
3) JB works
4) Some .app are convertable to trollstore by putting them in Payload and creating an archive
5) That is how I use Sileo and it is the only one that works that way, altho it only allows to install tweaks and add only stock repos
6) So I have to get debs somewhere to give them to Sileo to install
7) That is really enoying

Hope there is a solution. I think it is connected to TrollStore somehow idk, sometimes it deletes itself and just bootloops my device until hard reset. When I refresh my packages in Troll bootloop happens everytime but when I hard reset out of it, everything is fine and TrollStore is back working.

Please help me :)

Same issue on Xina, identical.

**Comment by opa334** [comment]
Do you have Sileo installed through TrollStore? If so, uninstall it.

**Comment by dollarystem** [comment]
![image](https://github.com/opa334/Dopamine/assets/122636582/85b260f8-1913-4a79-9b7e-bfc93c281212)![image](https://github.com/opa334/Dopamine/assets/122636582/d32c9843-2855-4b8f-ae58-26e74ecc8d17)![image](https://github.com/opa334/Dopamine/assets/122636582/64b8916c-cdf0-4240-aac2-5dfc3608da3f)![image](https://github.com/opa334/Dopamine/assets/122636582/eb012acc-d0f2-47c3-9c77-4969cb633118)![image](https://github.com/opa334/Dopamine/assets/122636582/2fd61fb0-f897-4041-ad54-8744de4e8ce8)![Uploading 242648411...]![image](https://github.com/opa334/Dopamine/assets/122636582/b736800f-ece5-47bd-a4c2-0ee5e58c7afe)![image](https://github.com/opa334/Dopamine/assets/122636582/1395b65f-38ef-4a2d-a119-b6550b923807)![image](https://github.com/opa334/Dopamine/assets/122636582/1dced93e-8a7f-4491-8653-baa3aa4da362)![image](https://github.com/opa334/Dopamine/assets/122636582/e79e3bbd-cc71-4118-b193-484eed50b641)![image](https://github.com/opa334/Dopamine/assets/122636582/95af9884-6f5e-437c-b7b4-9df952983ddd)

**Comment by dollarystem** [comment]
I had to install them in trollstore because of the problem, I did not have them there before the problem.

**Comment by dollarystem** [comment]
Okay, now my device is just bootlooped again after a respring of installing one of the tweaks that create .app

**Comment by opa334** [comment]
Did you install a package that has an app with the same identifier as an app that you have already installed in TrollStore? This is completely unsupported and there is no way to fix this in the jailbreak.

**Comment by dollarystem** [comment]
Opa, I don't know maybe you got some problem with understanding English. I have never ever installed any jailbreak app through a TrollStore this is not my method of use, I had to start doing that in order for at least some apps to work. Do you understand??? If I have .app inside /jb/Application it will break my jb THE SAME HAPPENS WITH XINA TOO, but they have different jb/Application folders.

**Comment by opa334** [comment]
I'm not stupid, I understand what you're saying, but I can neither reproduce this, nor has anyone else had this issue before, so my suspicion is that you are installing an app that is already installed via TrollStore, making uicache lock up
