### ISSUE TITLE
Random reboots 1-2 times per day, iOS 15.1, 13 Pro, Dopamine 1.0.5

### ISSUE THREAD

**Issue by konstantin-saetskiy-voodoo** [opa334/Dopamine#195]
Random reboots 1-2 times per day, iOS 15.1, 13 Pro, Dopamine 1.0.5.

Logs: [text-F1551B4B2B97-1.txt](https://github.com/opa334/Dopamine/files/11633485/text-F1551B4B2B97-1.txt)

**Comment by opa334** [comment]
No such issue on my 13 Pro on 15.1.1 🤷‍♂️ Also the log you sent is unrelated

**Comment by Cryptiiiic** [comment]
this irony `SIMULATED (this is NOT a crash)`

**Comment by ChipSkylark37** [comment]
Same issue with iPhone 13 Pro Max on 15.0.1. Reboots occur either same day, or next day. Never able to get more the 2 days of uptime. 

Saw it happen when not using, screen off, and then a reboot with apple logo, on strong WiFi. 

This happens with no tweaks installed outside of Pods2Grant, but have also tried without that tweak, and without tweak injection enabled (tweak injection disabled, can get 3-4 days before a random reboot)

What logs would help to locate the issue?

**Comment by opa334** [comment]
There is no way to locate this issue

**Comment by kratos9394** [comment]
reboot anytime
