### ISSUE TITLE
5G fell back to 4G

### ISSUE THREAD

**Issue by nydykl** [opa334/Dopamine#197]
13Pro、15.3.1、Dopamine1.0.5

1. Chinese telecommunications operator, 5G continued to operate before prison break, and after prison break, 5G fell back to 4G

2. The mobile phone is connected to the zepp sports watch software, and the message push is normal. When the iceanerPro is cleared and logged off, the message cannot be pushed. Restarting the user space does not know whether it has any effect, but restarting the mobile phone to reactivate the prison break environment is effective

**Comment by opa334** [comment]
Most likely a stock issue.
