### ISSUE TITLE
popen is broken

### ISSUE THREAD

**Issue by swigger** [opa334/Dopamine#198]
## abstract

popen is broken in dopamine jailbroken 15.4.1 iphone11.

## details

write a small C program:

```C
#include <stdio.h>
#include <stdlib.h>
int main() {
    FILE *fp;
    char path[1035];
    fp = popen("ls -a", "r");
    if (fp == NULL) {
        printf("Failed to run command\n");
        exit(1);
    }
    while (fgets(path, sizeof(path), fp) != NULL) {
        printf("%s", path);
    }
    pclose(fp);
    return 0;
}
```

compile it, ldid Sign it, copy to iphone and run it. it will print out nothing.
but compile it on any other os, it will print files in current dir. since -a is used, it will output at list . and .. if there is no file in current dir.

## conclusion
the borken  popen will return a valid FILE* but can never be read. it always return NULL on first fgets.

## environment
IOS: 15.4.1
Dopamine version: 1.0.5
iPhone 11 64G: iPhone12,1 (A2223)

## other info
I compile the above C code and attach it here:
[popen.gz](https://github.com/opa334/Dopamine/files/11650220/popen.gz)

**Comment by swigger** [comment]
NO. the root cause is popen borken. that is it.

I'm a c++ programmer with 20 years of exp. I have other real code failed and I dig into that case, finally found popen is the reason.

The command `ls` is definitely in PATH. 

And you can change the command from "ls -a" to "echo hello",  and you would also get nothing.

I changed to code to this:

```
#include <stdio.h>
#include <stdlib.h>

int main() {
    FILE *fp;
    char path[1035];

    fp = popen("echo hello", "r");
    if (fp == NULL) {
        printf("Failed to run command\n");
        exit(1);
    } else {
        printf("got fp=%p\n", fp);
    }
    while (fgets(path, sizeof(path), fp) != NULL) {
        printf("%s", path);
    }
    printf("closing fp...\n");
    pclose(fp);
    return 0;
}
```

and got this:

![image](https://github.com/opa334/Dopamine/assets/12627791/ed48b0f1-89d6-4a50-987d-fea6dc941137)

**Comment by swigger** [comment]
NO. the reason popen is broken is not related to whether `ls` in $PATH or not.

to prove this ,let me change the code to this:
```C
#include <stdio.h>
#include <stdlib.h>

int main() {
    FILE *fp;
    char path[1035];

    fp = popen("BlueTool -h", "r");
    if (fp == NULL) {
        printf("Failed to run command\n");
        return 1;
    } else {
        printf("got fp=%p\n", fp);
    }
    while (fgets(path, sizeof(path), fp) != NULL) {
        printf("%s", path);
    }
    printf("closing fp...\n");
    pclose(fp);
    return 0;
}
```

I changed `ls` to `BlueTool -h` where `BlueTool` is a program found in /usr/sbin/ shipped by Apple.
And function `fgets` also gets nothing.
![image](https://github.com/opa334/Dopamine/assets/12627791/79726fa3-4858-49b3-af64-11fcd74a80de)

Yes I can use posix_spawn or other things to work around this issue.
But popen is a POSIX api and is widely used , I cant fix all other programs failed in jailbroken ios.

**Comment by opa334** [comment]
There is nothing inside Dopamine that would prevent popen from working on Apple binaries at least. Just it's questionable whether the systemhook injects but this shouldn't matter all too much. Are you sure this exact binary works on another jailbreak?

**Comment by swigger** [comment]
Yes, this exact popen I uploaded works on an iphone X 256G with ios 14.3 jailbroken by unc0ver v8.0.2.

```
iPhone:~ root# which popen
/usr/games/popen
iPhone:~ root# md5sum /usr/games/popen
41cccecb0c29b1713885028659ea8af4  /usr/games/popen
iPhone:~ root# popen
.
..
.aks_migrate
.aks_whitelist
.bash_history
.bootstrapped
.mkb_seshat_health
.ssh
.viminfo
Library
Media
bin
``` 

However, this  does not mean  there is a bug in dopamine.
It may also be something changed between IOS 14.3 and 15.4.1.

I wonder if there is some hided kernel options controling this different behavior.

I wish I have enough time so that I am able to dig depth into how popen is implemented instruction by instruction.
In that case I may discover how to fix this. 

I wish there are other clever guys to help find the solution and make dopamine better.

**Comment by blanxd** [comment]
why is this a topic... if you look at `man popen` on a mac, it says clearly `command is passed to /bin/sh, using the -c flag`, this is where I learned it's pointless on rootless and forgot about it. Reading this here I took the time to look it up, it's in [https://github.com/apple-oss-distributions/Libc/blob/main/gen/FreeBSD/popen.c](https://github.com/apple-oss-distributions/Libc/blob/main/gen/FreeBSD/popen.c), it's in essence a wrapper to `posix_spawn` itself (I suppose fork() & friends in the past). And it's using "sh" which is being looked for in `_PATH_BSHELL`, which in turn is hardcore defined "/bin/sh" anywhere you look. Well, this is how I explain it for myself, could be I'm totally mistaken if apple is building this differently for iOS, please do apologize and do correct me in that case.
