### ISSUE TITLE
PPLRW ~1000 times faster on average maybe cause spinlock？

### ISSUE THREAD

**Issue by HuChundong** [opa334/Dopamine#202]
Hello opa334, the version 1.0.5 is very stable on my phone. After I compiled the latest develop branch (commit: https://github.com/opa334/Dopamine/commit/8b01e1e9584ebf92106d960d91caeca73c0bd6c9), the performance has improved significantly, but the stability has noticeably decreased, with problems related to spinlock. Is it possible that this problem is related to the code related to ppl or fork fix?

**Comment by HuChundong** [comment]
but i can confirm after 1.0.5, spinlock seems appear.

**Comment by Cryptiiiic** [comment]
I've been spinlocking since alpha builds its not caused by 1.0.5 specifically but maybe it is. It seems to be random. I'm going on back to back 11 day runs. 11 is my current record

**Comment by HuChundong** [comment]
I used version 1.0.5 of uptime to record 8 days. However, since I switched to the alpha version after 1.0.5, I can only last up to 24 hours at most, and even the spinlock situation occurred within 2 hours. Currently, I am running the latest alpha version based on the current time, and it has been running for 22 hours.

**Comment by 1825469427** [comment]
I also had a random spin lock after updating the PPLRW version 1000 times faster. The previous version 1.0.5 with opa334 did not have this issue

**Comment by 1825469427** [comment]
I also had a random spin lock after updating the PPLRW version 1000 times faster. The previous version 1.0.5 with opa334 did not have this issue

**Comment by limi586** [comment]
I also had a random spin lock after updating the PPLRW version 1000 times faster. The previous version 1.0.5 with opa334 did not have this issue.

**Comment by cupiditys** [comment]
Had around 20 days of uptime on 1.0.5, restarted and updated this morning and have panicked 3 times so far today

**Comment by HuChundong** [comment]
> Had around 20 days of uptime on 1.0.5, restarted and updated this morning and have panicked 3 times so far today

Yes, I have a few friends who are using the latest 1.1 version and have also experienced reboot issues within a few hours.

**Comment by HuChundong** [comment]
compiled https://github.com/opa334/Dopamine/commit/8b01e1e9584ebf92106d960d91caeca73c0bd6c9 without https://github.com/opa334/Dopamine/commit/067b873b2ff195f80b1ec07bb418a457927c2ee0 looks like very stable. so pplrw maybe is not the cause. uptime 8 hours now. 1.1 only uptime 2 hour for me and some of my friends. @opa334

**Comment by midkin** [comment]
I don't know if it's related but v1.1 is the first version that I face random reboots. This never happened for my device before 1.1.

**Comment by HuChundong** [comment]
> I don't know if it's related but v1.1 is the first version that I face random reboots. This never happened for my device before 1.1.

could you help test the 1.0.5-pplrw version？

**Comment by midkin** [comment]
> > I don't know if it's related but v1.1 is the first version that I face random reboots. This never happened for my device before 1.1.
> 
> 
> 
> could you help test the 1.0.5-pplrw version？

Will do!

**Comment by ChipSkylark37** [comment]
> > I don't know if it's related but v1.1 is the first version that I face random reboots. This never happened for my device before 1.1.
> 
> 
> 
> could you help test the 1.0.5-pplrw version？

Figured I would give this a try since I've had reboot issues (within the same day) since the first version. With version 1.1 I can get upwards of a day before a reboot (most of the time PSOD), and testing out the 1.0.5-pplrw, I only got around 8 hours of uptime. 

My issue may be somewhat different as I've never had good uptime. Only one tweak installed Pods2Grant but has also been tested without any tweaks installed.

**Comment by opa334** [comment]
the pplrw solution in that commit is almost 1:1 identical to the one that's in 1.1, I only removed some parts of the code that would never be hit to begin with

**Comment by midkin** [comment]
> the pplrw solution in that commit is almost 1:1 identical to the one that's in 1.1, I only removed some parts of the code that would never be hit to begin with

I can confirm at least for my device (iPhone XS Max, iOS 15.1.1) the pplrw makes no change to random reboots! v1.0 was zero reboots for me. Both 1.2 and 1.05 pplrw cause reboots

**Comment by ChipSkylark37** [comment]
> > the pplrw solution in that commit is almost 1:1 identical to the one that's in 1.1, I only removed some parts of the code that would never be hit to begin with
> 
> I can confirm at least for my device (iPhone XS Max, iOS 15.1.1) the pplrw makes no change to random reboots! v1.0 was zero reboots for me. Both 1.1 and 1.05 pplrw cause reboots

There was no public 1.0 release?

Is there something else we can be doing to troubleshoot the reboots - Providing panic logs, etc?

**Comment by HuChundong** [comment]
> the pplrw solution in that commit is almost 1:1 identical to the one that's in 1.1, I only removed some parts of the code that would never be hit to begin with

But 1.05-pplrw has been running for 3 days and 4 hours on my end (15.1, 13mini ), so this is very strange. 
if it reboot, i'm going to use another version contain https://github.com/opa334/Dopamine/commit/067b873b2ff195f80b1ec07bb418a457927c2ee0

**Comment by HuChundong** [comment]
int kalloc(uint64_t *addr, uint64_t size)
{
	uint64_t kalloc_data_external = bootInfo_getSlidUInt64(@"kalloc_data_external");
	uint64_t allocation = kcall(kalloc_data_external, 2, (uint64_t[]){size, 1});
	if (allocation != 0) {
		if (addr) *addr = allocation;
		return 0;
	}
         //  *addr = ? ;   If memory allocation fails, and the variable "addr" is not assigned any value. Will this have any impact here? 
	return 1;
}

**Comment by opa334** [comment]
> > the pplrw solution in that commit is almost 1:1 identical to the one that's in 1.1, I only removed some parts of the code that would never be hit to begin with
> 
> I can confirm at least for my device (iPhone XS Max, iOS 15.1.1) the pplrw makes no change to random reboots! v1.0 was zero reboots for me. Both 1.1 and 1.05 pplrw cause reboots

That's going to be coincedence because nothing that could have introduced these spinlock panics was added in 1.0 - 1.0.5 and also spinlock panics where happening for some people on private betas even.

**Comment by HuChundong** [comment]
> > > the pplrw solution in that commit is almost 1:1 identical to the one that's in 1.1, I only removed some parts of the code that would never be hit to begin with
> > 
> > 
> > I can confirm at least for my device (iPhone XS Max, iOS 15.1.1) the pplrw makes no change to random reboots! v1.0 was zero reboots for me. Both 1.1 and 1.05 pplrw cause reboots
> 
> That's going to be coincedence because nothing that could have introduced these spinlock panics was added in 1.0 - 1.0.5 and also spinlock panics where happening for some people on private betas even.

in 1.1, If calling the kcall method returns equals to 0, then addr will not be assigned. Before refactoring the code, addr will be assigned to the 0  from kcall.

**Comment by opa334** [comment]
> > > > the pplrw solution in that commit is almost 1:1 identical to the one that's in 1.1, I only removed some parts of the code that would never be hit to begin with
> > > 
> > > 
> > > I can confirm at least for my device (iPhone XS Max, iOS 15.1.1) the pplrw makes no change to random reboots! v1.0 was zero reboots for me. Both 1.1 and 1.05 pplrw cause reboots
> > 
> > 
> > That's going to be coincedence because nothing that could have introduced these spinlock panics was added in 1.0 - 1.0.5 and also spinlock panics where happening for some people on private betas even.
> 
> in 1.1, If calling the kcall method returns equals to 0, then addr will not be assigned. Before refactoring the code, addr will be assigned to the 0 from kcall.

what specifically are you refering to? please send me the line of code

**Comment by HuChundong** [comment]
https://github.com/opa334/Dopamine/blob/23ae3723f8c4812d05ac3ad83aa03db53e855359/BaseBin/libjailbreak/src/util.m#L60

**Comment by opa334** [comment]
> https://github.com/opa334/Dopamine/blob/23ae3723f8c4812d05ac3ad83aa03db53e855359/BaseBin/libjailbreak/src/util.m#L60

Yeah but the return value takes care of that, you can't expect it to null out addr if it fails

**Comment by HuChundong** [comment]
> kalloc

*addr = 0;  // add this line
return 1;

before return, i set the addr to 0, and 1.1 version works uptime 4.5 days. the origin 1.1 uptime is 3 hours.  if i meet reboot, i will install orig 1.1 to test if it was a accidental event.

**Comment by opa334** [comment]
While I don't think this should have any impact, I did some testing a while ago and did notice that kalloc sometimes returns 0 on random occasions so maybe it could be a good idea to protect against this

**Comment by HuChundong** [comment]
> While I don't think this should have any impact, I did some testing a while ago and did notice that kalloc sometimes returns 0 on random occasions so maybe it could be a good idea to protect against this

Although we still don't know what triggers the spinlock, version 1.0.5 simply commits PPLRW, which noticeably increases the likelihood of a spinlock occurring on some devices（15.1，13mini）. Could we refactor PPLRW to maintain high performance while reverting to the stability of version 1.0.5? Or is there a correlation between the probability of a spinlock occurrence and the performance improvement of PPLRW?

**Comment by opa334** [comment]
13 Pro on 15.1.1 here - No difference

I don't see a correlation, but spinlock panics do not make any sense to begin with, only god knows what causes them.

**Comment by opa334** [comment]
This has been disproven, forkfix hooking every single process is what made spinlock panics worse.
