### ISSUE TITLE
Please make dopamine jailbreak for A15 ios 16.3

### ISSUE THREAD

**Issue by Legend7269** [opa334/Dopamine#205]
People can sideload it from the app Scarlet instead of trollstore also.

**Comment by Cryptiiiic** [comment]
12 year old behavior, believing without question for which you do not understand

**Comment by Legend7269** [comment]
Im saying that when it becomes possible can you make one not to just do all of that work lol. Wtf you mean I dont understand

**Comment by Cryptiiiic** [comment]
You have no idea how rare this was. And to think it will happen again? It will take people not caring about public safety for it to happen again. Not all security researchers will release to the public. We got lucky with linus releasing stuff publicly twice.

We need two rare bugs + two tradition kernel bugs for jailbreaks in this day and age. Best of luck hoping 👍🏻

**Comment by Legend7269** [comment]
Damn srry
