### ISSUE TITLE
Kcall in rare cases results in "Invalid Kernel Stack Pointer" panic

### ISSUE THREAD

**Issue by Liam0205** [opa334/Dopamine#207]
## Environment

* iPhone XR
* iOS 15.1
* Dopamine 1.1

## Reproduction

* not able to reproduce stabilily

## Panic Log

see: https://gist.github.com/01040827b6ba06ff209ffade88894aba

**Comment by oOJohn6Oo** [comment]
Since upgrading to a new version, I've had at least three user space reboots, about every 3 hours.

And I've never experienced it once in all previous versions.

**Comment by Liam0205** [comment]
> 

While I understand your feelings when encountering a problem, does what you said have anything to do with the issue I raised? Or is it that you also encountered a crash issue similar to mine?

**Comment by oOJohn6Oo** [comment]
> While I understand your feelings when encountering a problem, does what you said have anything to do with the issue I raised? Or is it that you also encountered a crash issue similar to mine?

Sorry, I don't know if it's related to the Panic, I just saw the title "1.1" and think it's maybe related.

**Comment by opa334** [comment]
Unlike spinlock panics, this is actually some sort of bug with kcall in Dopamine and afaik has been a thing since the early betas. I have no idea what causes it however.

**Comment by Liam0205** [comment]
Another case, collected from community chat group.

----

* iPhone 13
* iOS 15.3.1
* Dopamine 1.1.10 (official version; oobPCI)
* Panic log: https://gist.github.com/Liam0205/a1c4cea018bb3cab82c3e21e6518beee

**Comment by opa334** [comment]
Fixed in 1.1.11.
