### ISSUE TITLE
can't rebuild JB or initializing JB 

### ISSUE THREAD

**Issue by hughyangadm** [opa334/Dopamine#211]
iPhone 13PM Ios 15.4.1.

Dopamine setting show that i already have in JB even though new install or reboot device . and i can see JB-xxxx in /Privite/preboot but no JB folder in /var. but i can't delete them coz i don't have premission.

now JB will failure every time .i guess coz i have some cache in system so that JB can't successed. any suggestion? Thanks!
![1](https://github.com/opa334/Dopamine/assets/135193084/0f6be796-dde1-47e0-90a2-598d441b7cf0)

**Comment by Liam0205** [comment]
Please follow the steps below:

1. Restart your iPhone.
2. Open the Dopamine app.
3. Go to "Settings".
4. Tap on "Uninstall Jailbreak" and wait for about 5 seconds.
5. Return to the main interface of Dopamine.
6. Tap on the "Jailbreak" button.
