### ISSUE TITLE
Ipad just crashed and it don't turn on

### ISSUE THREAD

**Issue by Urdadan** [opa334/Dopamine#219]
Yesterday i jailbroke my M1 ipad pro, and now i was playing a game and it just crashed, then it turned on 2 times and then crashed and completely died, i tried to reboot it but the pc don't even see it, i tried to enter dfu mode but it not worked too.

**Comment by lukar-debug** [comment]
Hi is the M1 still working?

**Comment by opa334** [comment]
if DFU mode doesn't work, it's a hardware issue and unrelated to Dopamine.
