### ISSUE TITLE
The configuration file should still be hooked up after injection is prohibited.

### ISSUE THREAD

**Issue by invalidunit** [opa334/Dopamine#221]
Could you consider still hooking up the configuration file path in Dopamine while disabling injection plugins? Because Sileo or Filza would write to /private/var/mobile/Library/Preferences at this time. 
Additionally, if plugins are already disabled, it should also cancel the subsequent restart of the user space. This is because a problem with the daemon process may result in repeated logouts or restarts of the user space. Alternatively, could you consider adding a button in the Dopamine settings menu for users to confirm before restarting the user space? This button can be manually triggered by the user.

**Comment by opa334** [comment]
I tried that before but couldn't get it working :/ I think the /private/preboot path might be too long for the weird cfprefsd api.

I don't see how a daemon problem would prevent userspace reboots from working.

**Comment by invalidunit** [comment]
> I tried that before but couldn't get it working :/ I think the /private/preboot path might be too long for the weird cfprefsd api.
> 
> I don't see how a daemon problem would prevent userspace reboots from working.

I'm sorry, I misunderstood yesterday. (yesterday, i wrote a faulty shell daemon process, and an incorrect file judgment caused 'launchctl reboot userspace' to execute after the daemon process started.)
So now I'm revising my previous statement, suggesting that we should follow Taurine's approach of starting only the OpenSSH daemon process and not other daemon processes when preventing plug-in injection.

**Comment by opa334** [comment]
I don't get what's the problem here - When tweaks are disabled Dopamine will already not do a userspace reboot.
