### ISSUE TITLE
Device brightness is lower than normal after jailbreaking

### ISSUE THREAD

**Issue by sshrmr** [opa334/Dopamine#223]
Im using iPhone 12 Pro Max 15.4.1.
After a successful jailbreak, the device brightness is super low that i can barely see anything (even tho its set on maximum in control center). I always have to respring after jailbreaking to fix this.

happens on 1.0.5 and still not fixed on 1.1.1

**Comment by Aftended** [comment]
Lol, same to me on iPhone 13 Pro Max 15.0.2 dopamine

**Comment by opa334** [comment]
Duplicate of #123
