### ISSUE TITLE
Allow beta channel OTA updates

### ISSUE THREAD

**Issue by Xarth-Mai** [opa334/Dopamine#225]
Add an option in the settings to enable Dopamine to detect Beta channel updates and perform OTA updates.

**Comment by Xarth-Mai** [comment]
The current version requires users to manually check for updates on GitHub, then manually install them through TrollStore, and finally restart the device to re-jailbreak and update the environment. Moreover, during the re-jailbreaking process, multiple kernel crashes can occur, which is quite inconvenient.

**Comment by Xarth-Mai** [comment]
IPA file from GitHub Action

**Comment by opa334** [comment]
Non release builds are entirely unsupported and are not recommended to be used by anyone.
