### ISSUE TITLE
How can I use iDownload?

### ISSUE THREAD

**Issue by gandizm** [opa334/Dopamine#229]
I just came from Fugu15, and I’d like to know if I can use iDownload’s krw option.

I tried using ssh and I don’t know the password (I’ve already tried ‘alpine’),
And I tried ‘nc 127.1 1337’ in LibTerm which used to work in Fugu15.
They all failed and what I’m wondering is that how can I use it?

**Comment by opa334** [comment]
`nc 127.1 1337` is supposed to work but now that you mention it, it doesn't seem to work for me either :/ maybe I broke it somehow

**Comment by gandizm** [comment]
Thanks.
