### ISSUE TITLE
Userspace reboot loop.

### ISSUE THREAD

**Issue by chrisharper22** [opa334/Dopamine#231]
I've constantly had issues with Dopamine during the jailbreak process, but those were PAC/PPL issues that seem to have been addressed in the 1.1+ releases.

However, since the newer releases, I have been unable to jailbreak successfully. The jailbreak process itself completes, but the device then enters a reboot loop that causes the device to gradually get warmer. Prior to these updates, the initial user space reboot would take 2-3 minutes, but now after each reboot, it instantly begins another reboot. I've narrowed this down to when the option for **tweak injection** is enabled. When off, the reboot loop cycle stops. (Will probably test this more)

Troubleshooting steps I've tried:

- Downgrading Dopamine (now this issues occurs no matter what? - probably needs more testing)
- Several hard reboots before jailbreaking (fwiw, I can break the loop by hard rebooting)
- Using airplane mode
- Leaving the device in the loop overnight (was still rebooting 5-6+ hours later)
- Deleting the jailbreak environment and jailbreaking from a fresh Dopamine install

I have an iPhone XR (Product red) on 15.1.1.

Attached is one of the logs from Analytics & Improvements.
[userspace-panic-2023-07-13_09-32-44.ips.zip](https://github.com/opa334/Dopamine/files/12040163/userspace-panic-2023-07-13_09-32-44.ips.zip)

**Comment by opa334** [comment]
Might be an icon cache issue, where you have Sileo or Zebra already installed via TrollStore?

**Comment by chrisharper22** [comment]
> Might be an icon cache issue, where you have Sileo or Zebra already installed via TrollStore?

I didn't have Sileo or Zebra through TrollStore, but I did have Filza. I removed that and cleaned the icon cache. That seemed to have helped? Would that have been an issue?

I also had NewTerm bug out and somehow uninstall itself as an app and would leave a ghost icon... perhaps that was an issue as well?
