### ISSUE TITLE
Wi-Fi / cellular delay connection issue on iPhone 13 Pro Max - 15.4.1

### ISSUE THREAD

**Issue by SametChan** [opa334/Dopamine#237]
I've installed the latest version of Dopamine in jailbroken or without jailbroken mode.

Both have issues with a delay connection in less than 10-15 seconds to load the website browser Safari and Chrome and all apps.

If dopamine is uninstalled and Wi-Fi & Cellular are back to normal and fast much in less than 1-2 seconds to load the website and any apps.

Are there any logs that cause delay issues from the path that I should send to the logs file?

**Comment by nintendowii111** [comment]
I second this. On exact same iphone and ios combo. Sometimes, connecting to discord or a website on safari takes forever or doesn't ever load at all. Restarting the app one or two times typically fixes the issue but it is a bug and annoying to say the least.

**Comment by opa334** [comment]
This is most likely just a side-effect of adding DYLD_INSERT_LIBRARIES system wide, which will void some dyld optimizations.
