### ISSUE TITLE
"Dopamine" is no longer available after unsuccessful jailbreak

### ISSUE THREAD

**Issue by mbs0ft** [opa334/Dopamine#238]
I can't open Dopamine after unsuccessful jailbreak, app version is 1.1.3
Rebooting iPhone doesn't fix the problem

![IMG_6360](https://github.com/opa334/Dopamine/assets/22106304/c044adc8-995b-4812-b656-629549d7fcd8)

**Comment by mbs0ft** [comment]
My actions was:
1. Updated Dopamine from 1.1.2 to 1.1.3 while iPhone is jailbroken
2. Dopamine updated itself and rebooted an iPhone
3. I tried to jailbreak again but I got panic and this bug appeared

**Comment by Lunascaped** [comment]
Refresh your app registrations in trollstore by opening whatever system app you set to control that, its Tips by default iirc

**Comment by rml9ty** [comment]
Same thing for me. Even TrollStore is not available anymore and has to be reinstalled.

**Comment by mbs0ft** [comment]
> Refresh your app registrations in trollstore 

yep, that worked, thanks!
