### ISSUE TITLE
Handy wird heiß und random Reboots

### ISSUE THREAD

**Issue by mudi47** [opa334/Dopamine#239]
Random Neustarts nach dem man gejailbreakt handy hängt auch. 
im normalen Modus bleibt alles normal nur in gejailbreakten Modus reboots, handy wird heiß und hängt
iPhone 12 iOS 15.2 
Bitte beheben
Mit freundlichen Grüßen

**Comment by opa334** [comment]
bra das ist hier kein wunschkonzert wir bleiben schön bei englisch
