### ISSUE TITLE
Sileo/Zebra choice not offered on jailbreaking with Dopamine 1.1.3

### ISSUE THREAD

**Issue by Aberdyfi** [opa334/Dopamine#240]
I just updated Dopamine to 1.1.3, but when I jailbroke I was not offered the usual Sileo/Zebra choice. (Sileo was removed from my device when I removed the older version of Dopamine using Trollstore.) It would not surprise me if I am doing something wrong, but I cannot figure it out. Thanks for any help!
Device: iPad Pro (12.9in, 5th Gen) running iPadOS 15.4.1.

**Comment by opa334** [comment]
there is a button to reinstall package managers in the app under settings when you're already jailbroken

**Comment by Aberdyfi** [comment]
Thanks for your help! (I am still having issues trying to upgrade from 1.1 to 1.1.3, but I am trying to characterize the issues more accurately before commenting further.)
