### ISSUE TITLE
Trying to update from 1.1.3 to 1.1.4 results in magnifier opening

### ISSUE THREAD

**Issue by Aberdyfi** [opa334/Dopamine#248]
I apologise for raising another issue. The situation is this. Initially I was able to jailbreak with no issues using Dopamine 1.1. I managed to upgrade to 1.1.3 manually, by adding Dopamine 1.1.3 direct to Trollstore. (I was unable to use the "automatic" upgrade, because when I tried it the iPad just switched to magnifier and did not actually upgrade.) But 1.1.3 never worked fully, in the sense that I could not enable tweak injection. Now, when I try to upgrade automatically to 1.1.4, I get the magnifier issue again.
Is it possible that there is some corruption of the file system? Could I have caused problems by switching the persistence system app from Tips to Home? 
A possibly related issue is that Sileo disappeared off my screen even though I was jailbroken (as witnessed by the fact that I could still navigate the file system). It could not be recovered by using the persistence app, which otherwise appeared to be working.
Device: iPad Pro (12.9in, 5th Gen) running iPadOS 15.4.1.

**Comment by opa334** [comment]
you need to enable the URL scheme in TrollStore
