### ISSUE TITLE
[bug report] iPhone failed to register 5G signal since beta.8

### ISSUE THREAD

**Issue by Liam0205** [opa334/Dopamine#25]
Hi @opa334 

This might be a bug since beta.8, hence this report.

A friend of mine complains that his iPhone 12 Pro Max/iOS 15.1.1 failed to register 5G signal with the China Telecom carrier. This problem emerges first on beta.8, please kindly give a check when you're available.

**Comment by xvklove** [comment]
Settings - Cellular network - Cellular number - Enable this number - Off - On, just do it once

**Comment by Lengran1992** [comment]
> Settings - Cellular network - Cellular number - Enable this number - Off - On, just do it once

It works！
Thank you.
