### ISSUE TITLE
Zebra needs more default repos

### ISSUE THREAD

**Issue by CubeBag** [opa334/Dopamine#250]
At the moment Dopamine ships with an old Zebra version, and the only default repo upon installation is getzbra. It should ideally have the same default repos as Sileo, but it needs Ellekit at the bare minimum.

Also worth mentioning is Zebra's shipped version is 1.1.31 which still has some problems telling the difference between rootless and non-rootless tweaks, so even though it's an easy update to 1.1.35, it would still be nice for Dopamine to ship the latest Zebra

**Comment by opa334** [comment]
What does that have to do with Dopamine???
