### ISSUE TITLE
After dopamine is jailbroken, the application background process is often killed. Unable to maintain many background programs and often need to restart applications.

### ISSUE THREAD

**Issue by varjay** [opa334/Dopamine#251]
After dopamine is jailbroken, the application background process is often killed. Unable to maintain many background programs and often need to restart applications.

It's normal without jailbreak. Some netizens said that the virtual memory will become invalid within a few hours after jailbreaking. Can this problem be solved?
Thank you for your contribution to jailbreak, salute!

iPhone13 128G
15.4.1
dopamine1.1.5/1.1.2

**Comment by opa334** [comment]
This is unsolvable due to needing to lower jetsam restrictions to do system wide injection, this will cause daemons to occupy more RAM and leave apps with less overall.
