### ISSUE TITLE
System apps registration reset after userspace panic

### ISSUE THREAD

**Issue by Hanze-Li** [opa334/Dopamine#253]
iPhone 13 Pro
iOS 15.0.1
Dopamine 1.8
 ![image](https://github.com/opa334/Dopamine/assets/68322089/423caf16-63ba-4a5b-ba42-009ecb98e904)
![image](https://github.com/opa334/Dopamine/assets/68322089/312012fb-bcfa-4fdd-9195-0eaa1be7b345)![image](https://github.com/opa334/Dopamine/assets/68322089/79abf8cc-01e3-46fc-b860-a6c025a616d3)

**Comment by Hanze-Li** [comment]
Sometimes this strange thing happens. I kept my phone charged last night and when I opened it the next morning, it went unjailbroken. I saw the "UserSpace Panic" notify which says Dopamine has protected me from a UserSpace panic, then aome system apps notified me with "WLAN has been disabled for xxxxxx". Then I found that all the sideloaded apps I installed by TrollStore(including TrollStore itself) cannot be opened(notify"no longer available"). So I used TrollStore persistence helper to refresh apps registration. Then I opened tweak injection from Dopamine. And everything was all right then.(Except that I have to switch all the "closed" registration to "WLAN and cellular" in Settings--Cellular)
[log.zip](https://github.com/opa334/Dopamine/files/12635003/log.zip)
This zip file includes SpringBoard, installd, bulletin(I don't know what it is so I uploaded it), userspace-panic, SystemMemoryReset. There are many SpringBoard logs within these 3 minutes, so I put the last one.If you want me to send others, feel free to ask me.

**Comment by opa334** [comment]
There is absolutely no way to influence this as it's done by iOS itself and not by any part of the jaiilbreak.

The SpringBoard crash looks like it's coming from Ellekit's MobileSafety.dylib, so probably something crashed SpringBoard, it entered safe mode and from there was crash looping, unfortunately the log isn't symbolicated so it's hard to say what exactly caused it...
