### ISSUE TITLE
No Zebra or Sileo

### ISSUE THREAD

**Issue by norehman** [opa334/Dopamine#255]
iPhone 13 Pro, 15.0

Using the latest version of Dopamine I had Sileo appear once when I installed the updates Sileo has disappeared and never come back. I've tried removing Dopamine and re-jailbreaking and still doesn't work. Reinstallation of Package Managers doesn't do anything. I've rebooted and tried again but it says my phone is in a jailbroken state but I have no package manager so I can't do anything.

Have now installed Xina which works ok but would rather use Dopamine if I can get it working.

**Comment by opa334** [comment]
If you were jailbroken with Xina before you have to uninstall Sileo from TrollStore before jailbreaking with Dopamine, besides that I don't see what could cause this.

**Comment by opa334** [comment]
Can't reproduce.

**Comment by Slaurits** [comment]
Had the same type of thing, The fix I found is to respring after jailbreaking, but the only way I could make it perma work, was to reset my phone.

**Comment by emadahmed22333** [comment]
same here no sileo and zebra  when i click hide jailbreak
