### ISSUE TITLE
Is it normal to have to rejailbreak after reboot?

### ISSUE THREAD

**Issue by mi7chy** [opa334/Dopamine#258]
11" M1 iPad Pro 512GB running iPadOS 15.0.1

After 'erase all content and settings' on device and installing TrollStore successfully then attempting jailbreak with Dopamine 1.1.6 it usually isn't successful the first attempt but displays a few lines, screen flashes magenta then reboots.  Second Dopamine jailbreak attempt usually works and shows jailbroken but manually rebooting device after that and running Dopamine it shows 'jailbreak' instead of 'jailbroken'.  Is it normal to have to rejailbreak after reboot or is there a way to make it permanent?  Also, image for Sileo is missing so it's just a white icon with lines.  Thank you in advance.

**Comment by opa334** [comment]
Being unjailbroken after restart is normal.

Sileo icon missing is not normal.
