### ISSUE TITLE
Tweaks not showing in settings

### ISSUE THREAD

**Issue by nemzn** [opa334/Dopamine#26]

**Comment by qq2519157** [comment]
you should install "ellekit" first

**Comment by opa334** [comment]
Can you check if `/var/jb/MobileSubstrate/DynamicLibraries` is a symlink to `/var/jb/usr/lib/TweakInject`?

**Comment by taylorsouzza** [comment]
same here, disint find the mobilesubstrate folder

**Comment by nemzn** [comment]
> same here, didn't find the mobilesubstrate folder

I fixed it just add Dhinak's repo and install preference loader, ur welcome
