### ISSUE TITLE
Rootful Dopamine?

### ISSUE THREAD

**Issue by SMFB7** [opa334/Dopamine#262]
https://github.com/pinauten/Fugu15_Rootful

**Comment by opa334** [comment]
I have known this was possible for quite some it, however due to it taking 8GB off of your device and rootless being better in any way, I have no plans to make Dopamine rootful.

**Comment by HanJiaChen854** [comment]
No, this is bad news.

**Comment by jhu7600codes** [comment]
please make rootful
