### ISSUE TITLE
Sileo and Zebra Unable to obtain add library

### ISSUE THREAD

**Issue by 814747889** [opa334/Dopamine#264]
![B9E128E4-C6E4-4F20-A0C8-AA4921A31020](https://github.com/opa334/Dopamine/assets/40017028/fa0bdb46-fd60-453f-9b5e-
![0451B2BF-76AE-4C83-B9B5-56C86CC846E0](https://github.com/opa334/Dopamine/assets/40017028/06ac48d8-89c1-4797-83c7-1e9d685a3be2)
eab5d2e12aeb)
![FDD23B03-7228-4604-BA1A-A69A542BA712](https://github.com/opa334/Dopamine/assets/40017028/a891274f-161a-4917-9189-09de5200b80c)
Sileo and Zebra Unable to obtain add library

**Comment by 814747889** [comment]
![Uploading 2DA3F136-1B42-4B7F-B55C-89E81CDDC1AC.jpeg…]()

**Comment by 814747889** [comment]
![1899696C-F150-4DCA-B219-464558ECFB5C](https://github.com/opa334/Dopamine/assets/40017028/c3e2b171-bf41-4333-9cc4-80ee8ca99acd)

**Comment by opa334** [comment]
Has nothing to do with Dopamine
