### ISSUE TITLE
Crashes on Patchfinding stage - IPhone SE2 Ios 15.1

### ISSUE THREAD

**Issue by PlumpoChicken56** [opa334/Dopamine#27]
Whilst jailbreaking on beta 8, the phone crashes during the patchfinding stage. Since I’m on 15.1, I have Wi-Fi turned off but I still can’t figure out the problem. Thanks

**Comment by axsel144** [comment]
I have similar problem on iPhone XR iOS 15.1, Fugu 15 installed via trollstore.
Fugu 15 beta 8, crash on jailbreak process. After crash - phone restarting and next time of trying of jailbreak - Fugu complete jailbreak without crash, but after userspace reboot - Fugu don't detect status of jailbreak.
And in that case - previously  installed tweak is active.

I recorded video of this issue https://youtu.be/pJE-gLrOLFM

**Comment by opa334** [comment]
The Fugu app generally does not remember if the device was jailbroken or not. That's not an issue.

**Comment by axsel144** [comment]
> The Fugu app generally does not remember if the device was jailbroken or not. That's not an issue.

Thank you!) Fugu 15 UI confused me with status of jailbreak :) Hope you can make more stability of injection
