### ISSUE TITLE
Search bar missing

### ISSUE THREAD

**Issue by bierbaron2** [opa334/Dopamine#275]
Since the update to 1.1.9, the search bar has disappeared in various apps: e.g. in Mails, Podcasts, Music, Signal, Sileo basically missing everywhere. The problem was not fixed with the update to 1.1.10. 
Dopamine version 1.1.10
Version 15.0 (Build 19A344)

**Comment by opa334** [comment]
Sorry, but that cannot possibly be caused by Dopamine.

**Comment by bierbaron2** [comment]
Well I had no problem with 1.1.8 only since a couple of days ago when I updated to 1.1.9 and when I remove the Dopamine Jailbreak the search bar is there. Only when I jailbreak it's missing.
