### ISSUE TITLE
Bootloop after userspace reboot

### ISSUE THREAD

**Issue by Leeksov** [opa334/Dopamine#278]
This problem occurs on three versions: 1.1.5, 1.1.9, 1.1.10. After installing ElleKit and rebooting the device, it does not boot. After force reset and jailbreak, device does not boot after userspace reboot

iOS 15.2.1 A13

**Comment by opa334** [comment]
Does it work when you don't install Ellekit?

The only problem I'm aware of currently is that on some devices this will happen due to apps being added to uicache, I have no idea why yet however.

**Comment by Leeksov** [comment]
I think this is a problem with uicache, but now I have a different problem with KFD, after Patchfinding, a reboot just happens

**Comment by Leeksov** [comment]
So any way for fix it?

**Comment by opa334** [comment]
no
