### ISSUE TITLE
Boot loop after enable hide jailbreak feature 

### ISSUE THREAD

**Issue by aboelhassan65** [opa334/Dopamine#279]
hello
my iPhone 13 pro max iOS 15.1 now is stuck in infinite boot loop (jailbroken with dopamine latest version )

what i did is:

1. I enabled hide jailbreak feature to do something with bank app
2. pressed reboot userspace button
3. device refreshed then worked normally then I used bank app normally
4. I disabled hide jailbreak feature ( by pressing unhide jailbreak button )
5. pressed reboot userspace button 
6.device stuck in apple logo boot loop

i tried rebooting my iPhone enter recovery mode and dfu mode and exit 
nothing helped me 

is there any chance to fix boot loop without losing my iOS version ?

i noticed something : if someone called me the device vibrates and I can hear my ringtone while apple logo still exist

**Comment by aboelhassan65** [comment]
you advice me to wait for any possible solution or to upgrade and lose my iOS version and jailbreak

**Comment by opa334** [comment]
Your icon cache is probably corrupted, which triggers a stock SpringBoard crash loop. I don't think this is fixable unfortunately, I also cannot see how this happened.

What you could try is using iCloud to reset your device, if that works it'd save the version but loose the data.

**Comment by aboelhassan65** [comment]
what do you mean by using icloud to reset my device

**Comment by opa334** [comment]
If your device is logged into iCloud there is an option to trigger a remote device wipe when logged in on icloud.com.

**Comment by aboelhassan65** [comment]
about loosing my data , you mean i will loose it permenantly ? or i can restore it from iCloud after fixing the problem

**Comment by aboelhassan65** [comment]
my question is : wiping the device from icloud site will only wipe the local data in the device but will keep the date stored in icloud storage such as ( photos and whatsapp backup) , so i can restore it after the phone works again

**Comment by aboelhassan65** [comment]
![image](https://github.com/opa334/Dopamine/assets/132671660/87b5a2c0-7f02-41dc-a1cc-fc750b2f549c)
i cant even erase my iphone from icloud site

**Comment by aboelhassan65** [comment]
![image](https://github.com/opa334/Dopamine/assets/132671660/379835ff-deb6-4f63-8003-a7e3302fb8a8)
erased successfully after putting Sim card with cellular data internet enabled

**Comment by aboelhassan65** [comment]
it worked and I didn't lose my iOS version.

you are a hero.

thank you very much.

**Comment by opa334** [comment]
No problem, glad it worked!

I'm currently looking into options of redirecting the problematic file to a different location while jailbroken so the issue can't trigger, unfortunately it causes issues when you install apps while jailbroken where they won't appear when not jailbroken :/. So not yet sure how to solve this.
