### ISSUE TITLE
Random resprings / pay I'd issues

### ISSUE THREAD

**Issue by ExoTicZs** [opa334/Dopamine#280]
When playing music resprings go crazy and hard resprings too, Pay iD sometimes hard locks my phone I have to manually reset with volume and power buttons pls fix

**Comment by opa334** [comment]
Resprings are generally caused by tweaks, not by jailbreaks. Your other issue sounds like a tweak issue aswell.

**Comment by ExoTicZs** [comment]
Can I send you my tweak list please
