### ISSUE TITLE
Unable to use the Apple Store-Apple store因未知原因不工作了

### ISSUE THREAD

**Issue by Pawsedawa** [opa334/Dopamine#288]
My Apple store can't install any software. I don't know what caused it. I hope I can get a solution😭

我的Apple store无法安装任何软件，我不知道是因为什么操作导致的，我希望我能得到解决办法😭

**Comment by cupecups** [comment]
yes same issue, unable to install appstore apps

**Comment by Zhou-Shilin** [comment]
This is what seems to be the problem with TrollStore. Try erase the device data.

**Comment by opa334** [comment]
This is not a problem with either TrollStore or Dopamine, it just happens sometimes, no one knows why.
There are some supposed fixes circulating but the only one that works 100% of the time is to backup the device, reset it and restore the backup afterwards.

**Comment by cupecups** [comment]
> apps

i solve this issue cause some apps (appstore apps) has force install using trollstore apps tweaked, i manage to solve manually delete bundle identifiers of apps using filza then remove apps (tweaked apps) on trollstore then installing apps from appstore work again
