### ISSUE TITLE
(Testing-Success) dopamine 2.0 - XR 16.0.2 - full panic/restart/2.0.1 Fixed

### ISSUE THREAD

**Issue by P5-2005** [opa334/Dopamine#291]
using sideloadly, paid dev id, kfd landa
[A12-16.0.2-panic.txt](https://github.com/opa334/Dopamine/files/14313593/A12-16.0.2-panic.txt)

second try after reboot, after the app auto kill:
![16022024_204517_492](https://github.com/opa334/Dopamine/assets/36075275/43da3bf9-df7d-4bdc-999d-9ad0c6e5d23d)

more verbose:

![16022024_205302_800](https://github.com/opa334/Dopamine/assets/36075275/ca25fcdf-5ab9-498f-96a4-b9c6a029ae19)

EDIT:
2.0.1 fixed the issue

![16022024_215901_479](https://github.com/opa334/Dopamine/assets/36075275/1ebe12b5-bacb-468d-9fe3-1a655e41d565)

**Comment by ToneXum** [comment]
Same issue here. The app crashes after about 10 seconds.
Trollstore 2; iPadOS 16.2; M1 iPad Pro (5th gen)
Edit: Fixed by rebooting

**Comment by malhaar** [comment]
Reboot .. Respring
