### ISSUE TITLE
Packet manager not appearing after jailbreak

### ISSUE THREAD

**Issue by SpyGdev** [opa334/Dopamine#293]
iPhone XR 16.0, I have tried to reinstall, rebuild icon cache and re jailbreak. But Sileo or zebra won't appear. Thanks

**Comment by malhaar** [comment]
Wait few mins or reboot userspace .. it appears but few seconds or couple of mins later.

**Comment by SpyGdev** [comment]
Thanks, I have tried user space reboot and waited around 10 minutes but it still has not shown up
