### ISSUE TITLE
(Testing-Success) dopamine 2.0 - XS 16.1.1 - full panic/restart

### ISSUE THREAD

**Issue by P5-2005** [opa334/Dopamine#294]
[A12-16.1.1.txt](https://github.com/opa334/Dopamine/files/14313791/A12-16.1.1.txt)
after this panic and reboot, got success

![16022024_210309_611](https://github.com/opa334/Dopamine/assets/36075275/b691ba35-a8e1-473d-a11b-8996f0ced9f4)

**Comment by opa334** [comment]
yeah a little bit of unreliability is normal atm
