### ISSUE TITLE
[suggestion] rootless libraries link against other rootless libraries

### ISSUE THREAD

**Issue by H5GG** [opa334/Dopamine#30]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/74475614/233489485-ef3b52bb-de4b-4824-99d3-6261ea677d7f.png">

exampes: 
the install name of the first rootless libraries is "@rpath/usr/lib/libA/libA.dylib"
the install name of the second rootless libraries is "@rpath/usr/lib/libB/libB.dylib"

1:  libA.dylib link against libB.dylib with "@rpath/usr/lib/libB/libB.dylib"
2: add rpath "@loader_path/../../../" to libA.dylib

so the rpath does not need to contain any fixed path, and we can use the complete subpath of the library in the jb root directory for the install name. And this method is also officially supported by Apple.

**Comment by CRKatri** [comment]
This was discussed when Procursus was first implementing rootless, but `@loader_path` works off of the symlink path, not the realpath, which means if you symlink a binary, it won't be able to find its dependencies.

**Comment by CRKatri** [comment]
I just performed my own tests on this, and you're right, they seem to have fixed it since. In any case, this is not the place for issues like this to be opened, please move this to ProcursusTeam/Procursus#
