### ISSUE TITLE
Packet manager disapeara after restart

### ISSUE THREAD

**Issue by SpyGdev** [opa334/Dopamine#302]
Using 2.2 with iOS 16 iPhone XR. I was able to open with shortcuts but after updating or restarting.

**Comment by bradleytechman** [comment]
see https://github.com/opa334/Dopamine/issues/304#issuecomment-1949110119

**Comment by opa334** [comment]
it might take a while for them to reappear after the userspace reboot, the icon cache implementation is horrible
