### ISSUE TITLE
Dopamine 2.0 alle Tweaks weg

### ISSUE THREAD

**Issue by ghost** [opa334/Dopamine#303]
Hallo, 

nach dem Update auf Dopamine 2.0.1 am IPhone 13 Pro Max mit iOS 15.1.1 kam eine Abfrage das ich ein Passwort für Sudo vergeben soll. Das habe ich getan. Danach waren alle Tweaks wie Watusi,Crane usw weg und ich hatte direkt 33 Updates in Sileo. Nach Downgrade auf Dopamine 1.0.5 weiterhin alle Tweaks weg. Wie bekomme ich das nun wieder repariert ? wenn ich zb versuche crane in sileo zu installieren ist installieren ausgegraut

**Comment by bradleytechman** [comment]
Translation:

Hello,

After the update to Dopamine 2.0.1 on the IPhone 13 Pro Max with iOS 15.1.1, a query came that I should assign a password for Sudo. I did that. After that, all tweaks such as Watusi, Crane, etc. were gone and I immediately had 33 updates in Sileo. After downgrading to Dopamine 1.0.5, all tweaks are still gone. How can I get it fixed again? For example, when I try to install crane in sileo, install is grayed out

**Comment by ghost** [comment]
Update: ich habe jetzt manuell einige Tweaks neu installiert. Gibt es eine Möglichkeit das komplett zu reparieren so das alles wieder da ist? Watusi Settings usw wurden nach der Installation direkt richtig eingestellt

**Comment by bradleytechman** [comment]
Installieren Sie die Updates für die 33 Pakete und springen Sie dann erneut.

**Comment by opa334** [comment]
2.0.1 hatte einen bug und hat mit jedem rejailbreak einen weiteren dopamine ordner erstellt, wenn 2.0.1 die erste version war die du benutzt hast dann mussst du einfach nur mit 2.0.3 jailbreaken und den jailbreak in den einstellungen entfernen, dann neustarten und wieder jailbreaken und es sollte die alten daten in den neuen pfad transferieren.

falls du mit 2.0.0 das erste mal gejailbreakt hast sind die daten bereits in einem dopamine ordner, in dem fall einfach so lange rejailbreaken und den jailbreak in den einstellungen entfernen bis der jailbreak die richtigen daten wieder benutzt.
