### ISSUE TITLE
Package Managers do not install

### ISSUE THREAD

**Issue by JoshuaDup** [opa334/Dopamine#304]
Sileo and Zebra do not install

Iphone 12 Pro Max
iOS 16.2
Dopamine 2.0.2

**Comment by ZASAonSK** [comment]
same iPhone X 16.6.1
Dopamine 2.0.2

**Comment by bradleytechman** [comment]
Open Dopamine
Tap Settings
Tap refresh jailbreak apps
wait
Profit 


if it still won't work

open shortcuts
create a new shortcut
add the open app action
change the app to sileo
run it
profit

**Comment by ZASAonSK** [comment]
shortcut method worked thanks

**Comment by opa334** [comment]
respring might be needed on some devices, other than that I'm not aware of any issues like this
