### ISSUE TITLE
iOS 16.6 A13

### ISSUE THREAD

**Issue by Klopi1337** [opa334/Dopamine#305]
Please add support ios 16.6 arm64e

**Comment by mucookul** [comment]
Really would appreciate this

**Comment by Aftended** [comment]
**Please**! STOP 🛑 _**making meaningless requests.**_  
!**Why** _do you need to do that?_ 
It **clutters** the **topic** and makes it **hard** to **read** and **find** valuable **information**. 
**### _______________________________**
@opa334, please! _**Avoid useless posts.**_ 
parcer checker or something like that. 
(**before user clutter request**)
