### ISSUE TITLE
Clash of Clans crashing

### ISSUE THREAD

**Issue by JoelHauser** [opa334/Dopamine#309]
On the latest version of Dopamine, iPhone 14 pro max on 16.4.1. Clash of clans crashes when opening the app. Anybody else having these issues?

**Comment by TeslaMan3092** [comment]
Try installing the choicy tweak, on bigboss (http://apt.thebigboss.org/repofiles/cydia/dists/stable) repo. then  disabling tweak injection for clash of clans

**Comment by opa334** [comment]
choicy might work, also not a dopamine issue, it's just jailbreak detection
