### ISSUE TITLE
Install button is disabled in Sileo

### ISSUE THREAD

**Issue by duckdurak** [opa334/Dopamine#310]
![photo_2024-02-16_22-15-44](https://github.com/opa334/Dopamine/assets/122701173/afcc11d4-6757-4d19-b079-d289190470fa)

**Comment by duckdurak** [comment]
Apps from "Featured" are installing successfully

**Comment by 4193883-eng** [comment]
the havoc repo has been having some issues lately, wait a bit and then check

**Comment by opa334** [comment]
havoc went down, should be back up now though
