### ISSUE TITLE
Jailbreak Crashes and Dopamine refuses to open

### ISSUE THREAD

**Issue by 0xC10** [opa334/Dopamine#311]
After installing a tweak with Sileo, the device crashed entirely. After re-jailbreaking, nothing is working. No service, no apps opening, etc. After rebooting, Dopamine refuses to open when pressed.

**Comment by 0xC10** [comment]
This issue has been resolved and should not be looked into unless similar issues have been spotted on your hardware. I recommend deleting the tweak **Crane** as it broke everything on my device.

**Comment by opa334** [comment]
Crane works just fine on Dopamine 2.x, just ensure it is up to date. Only the latest version will work.
