### ISSUE TITLE
High RAM devices need a memory hogger for kfd

### ISSUE THREAD

**Issue by Airmancooma** [opa334/Dopamine#313]
![IMG_4390](https://github.com/opa334/Dopamine/assets/107194958/d757cde5-d660-475b-a0ac-650952fd3fff)

I always got this error (picture). Sometimes I can set a password but after that my ipad crashes. Any idea?

**Comment by m1337v** [comment]
you got too much RAM. Try to open a lot of apps that take a lot of RAM e.g. games

**Comment by opa334** [comment]
yeah 16GB is flaky atm, will be addressed in a later update. For now you have to make the device use a lot of RAM before jailbreaking, then it might work.

**Comment by Airmancooma** [comment]
> you got too much RAM. Try to open a lot of apps that take a lot of RAM e.g. games

Thx it worked!

**Comment by Airmancooma** [comment]
.
