### ISSUE TITLE
Safe mode when using a keyboard

### ISSUE THREAD

**Issue by 4193883-eng** [opa334/Dopamine#315]
Hi opa! First of all I would like to tell you how I appreciate all of the work you have put in the jb community. But this issue is an absolute deal breaker for Dopamine. The issue is whenever I use my Magic Keyboard on an iPad Air 5(ios 16.5), the jailbreak crashes and exits out in the safe mode. If you need any crash logs, please tell me how to get them because I don't know where to get them.

**Comment by opa334** [comment]
this sounds like a tweak issue to me, install KrashKop and send a SpringBoard crash log from that

**Comment by 4193883-eng** [comment]
here is the springboard crash: https://pastebin.com/EX7rN8Sw

**Comment by opa334** [comment]
caused by snowboard

**Comment by 4193883-eng** [comment]
thanks for getting back at me, i thought it was the same issue as serotonin's, the serotonin app didn't even open with the keyboard. currently typing this with my magic keyboard!
