### ISSUE TITLE
I created three different Bootstraps, how should I clean them?

### ISSUE THREAD

**Issue by Margele** [opa334/Dopamine#319]
2.0.1 Bug.

/private/preboot/[random string]/dopamine-[random string]

Can I just delete the redundant dopamine folders?

**Comment by opa334** [comment]
Yes, you can delete the redundant folders. Do not delete anything not starting with dopamine- though.
On iOS 15 this isn't trivial however as /private/preboot is read-only by default.

**Comment by Margele** [comment]
done, thanks!
