### ISSUE TITLE
Updating dopamine via the app causes it to change to a user install type in trollstore

### ISSUE THREAD

**Issue by RUGMJ** [opa334/Dopamine#322]
This, for some reason, prevents jailbreak apps from displaying. manually fixed by changing dopamine back to a system install via troll store and after respringing the jailbreak apps re appear.

**Comment by libr2** [comment]
> This, for some reason, prevents jailbreak apps from displaying. manually fixed by changing dopamine back to a system install via troll store and after respringing the jailbreak apps re appear.

yup im having this problem too.![image](https://github.com/opa334/Dopamine/assets/157130969/0f317b86-d914-4687-9298-27873cab19b8)

**Comment by opa334** [comment]
that's normal and not really an issue, just stock iOS being shit.
just run refresh in persistence helper afterwards.
