### ISSUE TITLE
Camera does not work in external apps

### ISSUE THREAD

**Issue by zhekch** [opa334/Dopamine#326]
When using any app that requires a camera (such as Snapchat, Telegram, or Dazz), it does not appear to be able to process any input. The image is either completely black or you can not even press the shutter. The stock camera app appears to work properly. Also, it doesn't work in the safe mode either, so i don't think the tweaks do anything. 
Would love to provide any logs required, as for now i don't know where to even get these types of logs.

**Comment by zhekch** [comment]
Fixed by a userspace reboot. 

Although it had appeared a few times before, so I suppose it is recurring + seen some users in discord having the same problem.

**Comment by Thyssenkrupp234** [comment]
@zhekch Same issue here, installed choicy and disabled tweak injection on Camera fixed it. Likely a bad tweak - lmk if it works for you
