### ISSUE TITLE
[A8] please add support for A8

### ISSUE THREAD

**Issue by WinnieTheKing** [opa334/Dopamine#327]
iPad mini 4 on iPadOS 15

**Comment by Zhou-Shilin** [comment]
> iPad mini 4 on iPadOS 15

Use [palera1n](https://palera1n.com/) instead.
palera1n is a developer-oriented jailbreak for checkm8 devices (A8-A11) on iOS 15.0-16.5.1

**Comment by opa334** [comment]
A8 support is planned
