### ISSUE TITLE
ipad5(gen) A9 16.6.1 touch broken after jailbreak

### ISSUE THREAD

**Issue by sanstale6** [opa334/Dopamine#328]
Hello! After jailbreaking my iPad 5 using Dopamine 2.0.4, I’ve encountered an issue where the touchscreen is unresponsive (however, it recovers after a forced restart). Could you please advise on how to solve this problem? Is there any additional information needed from me?

**Comment by SternXD** [comment]
I have the same issue on my iPhone 8 on 16.6 Beta 1 and I've tried to troubleshoot for hours it seems to be an issue with replacing the display **_though other jailbreaks work and it works unjailbroken_**

**Comment by eglacias** [comment]
Disable all of your tweaks, Does it still happen?
Definitely interested in this as I’m thinking of updating then futurerestoring an 8+ to this version from a working iOS 14 jailbreak just a test this

**Comment by sanstale6** [comment]
> Disable all of your tweaks, Does it still happen?
> Definitely interested in this as I’m thinking of updating then futurerestoring an 8+ to this version from a working iOS 14 jailbreak just a test this

I haven’t installed any tweaks through dopamine jailbreak (touch issues preventing me from installing tweaks), and yet, this issue still occurs
If you are referring to Bootstrap, I have cleared out Bootstrap, but I am not sure if this is related to the issue

**Comment by SternXD** [comment]
> Disable all of your tweaks, Does it still happen?
> 
> Definitely interested in this as I’m thinking of updating then futurerestoring an 8+ to this version from a working iOS 14 jailbreak just a test this

If you go to #296 I tested this thoroughly on my iPhone 8

**Comment by opa334** [comment]
Duplicate of #296
