### ISSUE TITLE
Dopamine Jailbreak cannot progress: error "Failed to grab free pages goal"

### ISSUE THREAD

**Issue by Snaxolotl71** [opa334/Dopamine#333]
I'm on an iPad Pro 12.9" M1 and the following verbose log keeps repeating when trying to jailbreak:
![IMG_0186](https://github.com/opa334/Dopamine/assets/112205782/41d1b2dd-d589-4099-a0e5-3e5fcf7c49ba)
I have tried rebooting, clearing all recent apps from the app switcher & reinstalling Dopamine

**Comment by Zhou-Shilin** [comment]
ios version?

**Comment by dpmaycry** [comment]
iOS 16.5 A9 iPad5 got same error with dopamine 2.0.4

**Comment by Snaxolotl71** [comment]
> ios version?

16.1.1

**Comment by opa334** [comment]
try again in 2.0.5

**Comment by dpmaycry** [comment]
same error with 2.0.4（iPad5 A9 iOS 16.5）

Spawning jbctl failed with error code 85
----
查找地址
System Info:
0xfffffff00784d180 <- kernelSymbol.cdevsw
0xfffffff00788e928 <- kernelSymbol.perfmon_devices
0xfffffff0070d1908 <- kernelSymbol.pv_head_table
0x0000000000000019 <- kernelConstant.T1SZ_BOOT
0xfffffff00733b9bc <- kernelSymbol.vn_kqfilter
0xffffff8000000000 <- kernelSymbol.vm_last_phys
0xfffffff00788df70 <- kernelSymbol.vm_first_phys_ppnum
0xfffffff00788df68 <- kernelSymbol.vm_page_array_ending_addr
0xfffffff0070d1938 <- kernelSymbol.vm_page_array_beginning_addr
0xfffffff00711fc00 <- kernelSymbol.gPhysBase
0xfffffff0070f4010 <- kernelSymbol.cpu_ttep
0xfffffff006d20b48 <- kernelSymbol.kalloc_data_external
0xfffffff0072eedb4 <- kernelSymbol.perfmon_dev_open
0x0000000000000040 <- kernelStruct.vm_map.pmap
0xfffffff007110c10 <- kernelSymbol.ppl_trust_cache_rt
0xfffffff007107110 <- kernelSymbol.mach_kobj_count
0xfffffff00711fc08 <- kernelSymbol.gPhysSize
0x0000000000000001 <- kernelConstant.kernel_el
0xfffffff007004000 <- kernelConstant.staticBase
0x0000000000000730 <- kernelStruct.proc.struct_size
0xfffffff0070f4148 <- kernelSymbol.vm_first_phys
0x000000000000022c <- kernelConstant.nsysent
0xffffff8000000000 <- kernelSymbol.pp_attr_table
0x0000000000000080 <- kernelConstant.mach_trap_count
0x0000000000000300 <- kernelStruct.task.itk_space
0x0000000000000001 <- kernelConstant.PT_INDEX_MAX
0xfffffff0070d28a0 <- kernelSymbol.ptov_table
0x0000007000000000 <- kernelConstant.ARM_TT_L1_INDEX_MASK
0xfffffff0078acc78 <- kernelSymbol.allproc
0xffffff8000000000 <- kernelConstant.pointer_mask
0xfffffff00711de18 <- kernelSymbol.gVirtBase
0xfffffff006d20b80 <- kernelSymbol.kfree_data_external
System Info libjailbreak:
0x0000000000000020 <- kernelStruct.pt_desc.ptd_info
0x0000000000000008 <- kernelStruct.pmap.ttep
0x0000000000000020 <- kernelStruct.ipc_space.table
0x0000000000000018 <- kernelStruct.proc.proc_ro
0xfffffff0070d1908 <- kernelSymbol.pv_head_table
0xfffffff00784d180 <- kernelSymbol.cdevsw
0xfffffff00788e928 <- kernelSymbol.perfmon_devices
0x0000000000000019 <- kernelConstant.T1SZ_BOOT
0x0000000000000028 <- kernelStruct.trustcache.struct_size
0x0000000000000094 <- kernelStruct.pmap.type
0x0000000000000010 <- kernelStruct.vm_map_links.min
0x000000000000006c <- kernelStruct.ucred.svgid
0x0000000000000020 <- kernelStruct.ucred.svuid
0x0000000000000020 <- kernelStruct.filedesc.ofiles_start
0x0000000000000068 <- kernelStruct.proc_ro.mach_trap_filter_mask
利用内核漏洞 (kfd, landa)
0x00000000000000d8 <- kernelStruct.proc.fd
0x0000000000000040 <- kernelStruct.proc.svgid
0x000000000000003c <- kernelStruct.proc.svuid
0xfffffff00788df68 <- kernelSymbol.vm_page_array_ending_addr
0xfffffff0070d1938 <- kernelSymbol.vm_page_array_beginning_addr
0xffffff8000000000 <- kernelSymbol.vm_last_phys
0xfffffff00788df70 <- kernelSymbol.vm_first_phys_ppnum
0xfffffff0070f4010 <- kernelSymbol.cpu_ttep
0xfffffff00711fc00 <- kernelSymbol.gPhysBase
0xfffffff006d20b48 <- kernelSymbol.kalloc_data_external
0xfffffff00733b9bc <- kernelSymbol.vn_kqfilter
0x0000000000000010 <- kernelStruct.pt_desc.pmap
0x0000000000000008 <- kernelStruct.vm_map_links.next
0x0000000000000040 <- kernelStruct.vm_map.pmap
0x0000000000000018 <- kernelStruct.ipc_entry.struct_size
0x0000000000000068 <- kernelStruct.ucred.rgid
0x000000000000001c <- kernelStruct.ucred.ruid
0x0000000000000454 <- kernelStruct.proc.flag
0x0000000000000010 <- kernelStruct.proc.pptr
0x0000000000000008 <- kernelStruct.proc.list_prev
0xfffffff007107110 <- kernelSymbol.mach_kobj_count
0xfffffff007110c10 <- kernelSymbol.ppl_trust_cache_rt
0xfffffff00711fc08 <- kernelSymbol.gPhysSize
0xfffffff0072eedb4 <- kernelSymbol.perfmon_dev_open
0x0000000000000001 <- kernelConstant.kernel_el
0x0000000000000008 <- kernelStruct.trustcache.prevptr
0x00000000000000b4 <- kernelStruct.vm_map.flags
0x0000000000000060 <- kernelStruct.task.threads
0x0000000000000070 <- kernelStruct.proc_ro.mach_kobj_filter_mask
0x0000000000000730 <- kernelStruct.proc.struct_size
0xfffffff0070f4148 <- kernelSymbol.vm_first_phys
0x000000000000022c <- kernelConstant.nsysent
0xfffffff007004000 <- kernelConstant.staticBase
0x0000000000000020 <- kernelStruct.trustcache.fileptr
0x0000000000000018 <- kernelStruct.pt_desc.va
0x0000000000000028 <- kernelStruct.task.map
0x0000000000000078 <- kernelStruct.ucred.label
0x0000000000000018 <- kernelStruct.ucred.uid
0xffffff8000000000 <- kernelSymbol.pp_attr_table
0x0000000000000080 <- kernelConstant.mach_trap_count
0x0000000000000018 <- kernelStruct.trustcache.size
0x000000000000008e <- kernelStruct.pmap.sw_asid
0x0000000000000010 <- kernelStruct.vm_map.hdr
0x0000000000000048 <- kernelStruct.ipc_port.kobject
0x0000000000000300 <- kernelStruct.task.itk_space
0x000000000000001c <- kernelStruct.proc_ro.csflags
0xfffffff0070d28a0 <- kernelSymbol.ptov_table
0xfffffff0078acc78 <- kernelSymbol.allproc
0x0000000000000001 <- kernelConstant.PT_INDEX_MAX
0x0000000000000002 <- kernelConstant.smdBase
0x0000007000000000 <- kernelConstant.ARM_TT_L1_INDEX_MASK
0x0000000000000018 <- kernelStruct.vm_map_links.max
0x0000000000000048 <- kernelStruct.vm_map_entry.flags
0x0000000000000528 <- kernelStruct.task.task_can_transfer_memory_ownership
0x0000000000000028 <- kernelStruct.ucred.groups
0x0000000000000028 <- kernelStruct.proc_ro.syscall_filter_mask
0x0000000000000020 <- kernelStruct.proc_ro.ucred
0x0000000000000548 <- kernelStruct.proc.textvp
0x0000000000000060 <- kernelStruct.proc.pid
0xfffffff00711de18 <- kernelSymbol.gVirtBase
0xfffffff006d20b80 <- kernelSymbol.kfree_data_external
0xffffff8000000000 <- kernelConstant.pointer_mask
device info: CPU family: 0x92fb37c8, RAM: 0x7bbe4000, available: 0x5a1bbc00
PUAF pages: 160, hogger memory: 0x39f3bc00
[info_init]: kfd->info.env.pid = 419
[info_init]: kfd->info.env.tid = 7615
[info_init]: kfd->info.env.maxfilesperproc = 10240
[puaf_init]: method_name = landa
[krkw_init]: method_name = kread_sem_open
[krkw_init]: method_name = kwrite_sem_open
[puaf_helper_give_ppl_pages]: given_ppl_pages = 1698
[puaf_helper_give_ppl_pages]: 🟢 0s 47ms 647us
[puaf_run]: 🟢 0s 32ms 556us
RAM size: 0x7bbe4000, free pages max: 0x13880
[krkw_helper_grab_free_pages]: 🟡 failed to grab free pages goal (goal 40, max 80000, RAM size 0x7bbe4000)
[info_init]: kfd->info.env.pid = 419
[info_init]: kfd->info.env.tid = 7615
[info_init]: kfd->info.env.maxfilesperproc = 10240
[puaf_init]: method_name = landa
[krkw_init]: method_name = kread_sem_open
[krkw_init]: method_name = kwrite_sem_open
[puaf_helper_give_ppl_pages]: given_ppl_pages = 1698
[puaf_helper_give_ppl_pages]: 🟢 0s 24ms 301us
[puaf_run]: 🟢 0s 32ms 728us
RAM size: 0x7bbe4000, free pages max: 0x13880
[krkw_helper_grab_free_pages]: 🟡 failed to grab free pages goal (goal 40, max 80000, RAM size 0x7bbe4000)
[info_init]: kfd->info.env.pid = 419
[info_init]: kfd->info.env.tid = 7615
[info_init]: kfd->info.env.maxfilesperproc = 10240
[puaf_init]: method_name = landa
[krkw_init]: method_name = kread_sem_open
[krkw_init]: method_name = kwrite_sem_open
[puaf_helper_give_ppl_pages]: given_ppl_pages = 1698
[puaf_helper_give_ppl_pages]: 🟢 0s 25ms 924us
[puaf_run]: 🟢 0s 32ms 908us
RAM size: 0x7bbe4000, free pages max: 0x13880
[krkw_helper_grab_free_pages]: 🟡 failed to grab free pages goal (goal 40, max 80000, RAM size 0x7bbe4000)
[info_init]: kfd->info.env.pid = 419
[info_init]: kfd->info.env.tid = 7615
[info_init]: kfd->info.env.maxfilesperproc = 10240
[puaf_init]: method_name = landa
[krkw_init]: method_name = kread_sem_open
[krkw_init]: method_name = kwrite_sem_open
[puaf_helper_give_ppl_pages]: given_ppl_pages = 1698
[puaf_helper_give_ppl_pages]: 🟢 0s 23ms 454us
[puaf_run]: 🟢 0s 33ms 763us
RAM size: 0x7bbe4000, free pages max: 0x13880
[krkw_helper_grab_free_pages]: 🟡 failed to grab free pages goal (goal 40, max 80000, RAM size 0x7bbe4000)
[info_init]: kfd->info.env.pid = 419
[info_init]: kfd->info.env.tid = 7615
[info_init]: kfd->info.env.maxfilesperproc = 10240
[puaf_init]: method_name = landa
[krkw_init]: method_name = kread_sem_open
[krkw_init]: method_name = kwrite_sem_open
[puaf_helper_give_ppl_pages]: given_ppl_pages = 1698
[puaf_helper_give_ppl_pages]: 🟢 0s 24ms 107us
[puaf_run]: 🟢 0s 32ms 332us
RAM size: 0x7bbe4000, free pages max: 0x13880
构建硬件读写条件
清理环境
提升权限
Updating BaseBin
将基础套件加载至信任缓存（TrustCache）
初始化环境
Jailbreak failed with error: Error Domain=JBErrorDomain Code=-11 "Spawning jbctl failed with error code 85" UserInfo={NSLocalizedDescription=Spawning jbctl failed with error code 85}

**Comment by opa334** [comment]
Enable developer mode. @dpmaycry

**Comment by dpmaycry** [comment]
> try again in 2.0.5
Same error with 2.0.5（iPad5 A9 iOS 16.5）
Spawning jbctl failed with error code 85
----
查找地址
System Info:
0xfffffff00784d180 <- kernelSymbol.cdevsw
0xfffffff00788e928 <- kernelSymbol.perfmon_devices
0xfffffff0070d1908 <- kernelSymbol.pv_head_table
0x0000000000000019 <- kernelConstant.T1SZ_BOOT
0xfffffff00733b9bc <- kernelSymbol.vn_kqfilter
0xffffff8000000000 <- kernelSymbol.vm_last_phys
0xfffffff00788df70 <- kernelSymbol.vm_first_phys_ppnum
0xfffffff00788df68 <- kernelSymbol.vm_page_array_ending_addr
0xfffffff0070d1938 <- kernelSymbol.vm_page_array_beginning_addr
0xfffffff00711fc00 <- kernelSymbol.gPhysBase
0xfffffff0070f4010 <- kernelSymbol.cpu_ttep
0xfffffff006d20b48 <- kernelSymbol.kalloc_data_external
0xfffffff0072eedb4 <- kernelSymbol.perfmon_dev_open
0x0000000000000040 <- kernelStruct.vm_map.pmap
0xfffffff007110c10 <- kernelSymbol.ppl_trust_cache_rt
0xfffffff007107110 <- kernelSymbol.mach_kobj_count
0xfffffff00711fc08 <- kernelSymbol.gPhysSize
0x0000000000000001 <- kernelConstant.kernel_el
0xfffffff007004000 <- kernelConstant.staticBase
0x0000000000000730 <- kernelStruct.proc.struct_size
0xfffffff0070f4148 <- kernelSymbol.vm_first_phys
0x000000000000022c <- kernelConstant.nsysent
0xffffff8000000000 <- kernelSymbol.pp_attr_table
0x0000000000000080 <- kernelConstant.mach_trap_count
0x0000000000000300 <- kernelStruct.task.itk_space
0x0000000000000001 <- kernelConstant.PT_INDEX_MAX
0xfffffff0070d28a0 <- kernelSymbol.ptov_table
0x0000007000000000 <- kernelConstant.ARM_TT_L1_INDEX_MASK
0xfffffff0078acc78 <- kernelSymbol.allproc
0xffffff8000000000 <- kernelConstant.pointer_mask
0xfffffff00711de18 <- kernelSymbol.gVirtBase
0xfffffff006d20b80 <- kernelSymbol.kfree_data_external
System Info libjailbreak:
0x0000000000000020 <- kernelStruct.pt_desc.ptd_info
0x0000000000000008 <- kernelStruct.pmap.ttep
0x0000000000000020 <- kernelStruct.ipc_space.table
0x0000000000000018 <- kernelStruct.proc.proc_ro
0xfffffff0070d1908 <- kernelSymbol.pv_head_table
0xfffffff00784d180 <- kernelSymbol.cdevsw
0xfffffff00788e928 <- kernelSymbol.perfmon_devices
0x0000000000000019 <- kernelConstant.T1SZ_BOOT
0x0000000000000028 <- kernelStruct.trustcache.struct_size
0x0000000000000094 <- kernelStruct.pmap.type
0x0000000000000010 <- kernelStruct.vm_map_links.min
0x000000000000006c <- kernelStruct.ucred.svgid
0x0000000000000020 <- kernelStruct.ucred.svuid
0x0000000000000020 <- kernelStruct.filedesc.ofiles_start
0x0000000000000068 <- kernelStruct.proc_ro.mach_trap_filter_mask
利用内核漏洞 (kfd, landa)
0x00000000000000d8 <- kernelStruct.proc.fd
0x0000000000000040 <- kernelStruct.proc.svgid
0x000000000000003c <- kernelStruct.proc.svuid
0xfffffff00788df68 <- kernelSymbol.vm_page_array_ending_addr
0xfffffff0070d1938 <- kernelSymbol.vm_page_array_beginning_addr
0xffffff8000000000 <- kernelSymbol.vm_last_phys
0xfffffff00788df70 <- kernelSymbol.vm_first_phys_ppnum
0xfffffff0070f4010 <- kernelSymbol.cpu_ttep
0xfffffff00711fc00 <- kernelSymbol.gPhysBase
0xfffffff006d20b48 <- kernelSymbol.kalloc_data_external
0xfffffff00733b9bc <- kernelSymbol.vn_kqfilter
0x0000000000000010 <- kernelStruct.pt_desc.pmap
0x0000000000000008 <- kernelStruct.vm_map_links.next
0x0000000000000040 <- kernelStruct.vm_map.pmap
0x0000000000000018 <- kernelStruct.ipc_entry.struct_size
0x0000000000000068 <- kernelStruct.ucred.rgid
0x000000000000001c <- kernelStruct.ucred.ruid
0x0000000000000454 <- kernelStruct.proc.flag
0x0000000000000010 <- kernelStruct.proc.pptr
0x0000000000000008 <- kernelStruct.proc.list_prev
0xfffffff007107110 <- kernelSymbol.mach_kobj_count
0xfffffff007110c10 <- kernelSymbol.ppl_trust_cache_rt
0xfffffff00711fc08 <- kernelSymbol.gPhysSize
0xfffffff0072eedb4 <- kernelSymbol.perfmon_dev_open
0x0000000000000001 <- kernelConstant.kernel_el
0x0000000000000008 <- kernelStruct.trustcache.prevptr
0x00000000000000b4 <- kernelStruct.vm_map.flags
0x0000000000000060 <- kernelStruct.task.threads
0x0000000000000070 <- kernelStruct.proc_ro.mach_kobj_filter_mask
0x0000000000000730 <- kernelStruct.proc.struct_size
0xfffffff0070f4148 <- kernelSymbol.vm_first_phys
0x000000000000022c <- kernelConstant.nsysent
0xfffffff007004000 <- kernelConstant.staticBase
0x0000000000000020 <- kernelStruct.trustcache.fileptr
0x0000000000000018 <- kernelStruct.pt_desc.va
0x0000000000000028 <- kernelStruct.task.map
0x0000000000000078 <- kernelStruct.ucred.label
0x0000000000000018 <- kernelStruct.ucred.uid
0xffffff8000000000 <- kernelSymbol.pp_attr_table
0x0000000000000080 <- kernelConstant.mach_trap_count
0x0000000000000018 <- kernelStruct.trustcache.size
0x000000000000008e <- kernelStruct.pmap.sw_asid
0x0000000000000010 <- kernelStruct.vm_map.hdr
0x0000000000000048 <- kernelStruct.ipc_port.kobject
0x0000000000000300 <- kernelStruct.task.itk_space
0x000000000000001c <- kernelStruct.proc_ro.csflags
0xfffffff0070d28a0 <- kernelSymbol.ptov_table
0xfffffff0078acc78 <- kernelSymbol.allproc
0x0000000000000001 <- kernelConstant.PT_INDEX_MAX
0x0000000000000002 <- kernelConstant.smdBase
0x0000007000000000 <- kernelConstant.ARM_TT_L1_INDEX_MASK
0x0000000000000018 <- kernelStruct.vm_map_links.max
0x0000000000000048 <- kernelStruct.vm_map_entry.flags
0x0000000000000528 <- kernelStruct.task.task_can_transfer_memory_ownership
0x0000000000000028 <- kernelStruct.ucred.groups
0x0000000000000028 <- kernelStruct.proc_ro.syscall_filter_mask
0x0000000000000020 <- kernelStruct.proc_ro.ucred
0x0000000000000548 <- kernelStruct.proc.textvp
0x0000000000000060 <- kernelStruct.proc.pid
0xfffffff00711de18 <- kernelSymbol.gVirtBase
0xfffffff006d20b80 <- kernelSymbol.kfree_data_external
0xffffff8000000000 <- kernelConstant.pointer_mask
device info: CPU family: 0x92fb37c8, RAM: 0x7bbe4000, available: 0x5a1bbc00
PUAF pages: 160, hogger memory: 0x39f3bc00
[info_init]: kfd->info.env.pid = 419
[info_init]: kfd->info.env.tid = 7615
[info_init]: kfd->info.env.maxfilesperproc = 10240
[puaf_init]: method_name = landa
[krkw_init]: method_name = kread_sem_open
[krkw_init]: method_name = kwrite_sem_open
[puaf_helper_give_ppl_pages]: given_ppl_pages = 1698
[puaf_helper_give_ppl_pages]: 🟢 0s 47ms 647us
[puaf_run]: 🟢 0s 32ms 556us
RAM size: 0x7bbe4000, free pages max: 0x13880
[krkw_helper_grab_free_pages]: 🟡 failed to grab free pages goal (goal 40, max 80000, RAM size 0x7bbe4000)
[info_init]: kfd->info.env.pid = 419
[info_init]: kfd->info.env.tid = 7615
[info_init]: kfd->info.env.maxfilesperproc = 10240
[puaf_init]: method_name = landa
[krkw_init]: method_name = kread_sem_open
[krkw_init]: method_name = kwrite_sem_open
[puaf_helper_give_ppl_pages]: given_ppl_pages = 1698
[puaf_helper_give_ppl_pages]: 🟢 0s 24ms 301us
[puaf_run]: 🟢 0s 32ms 728us
RAM size: 0x7bbe4000, free pages max: 0x13880
[krkw_helper_grab_free_pages]: 🟡 failed to grab free pages goal (goal 40, max 80000, RAM size 0x7bbe4000)
[info_init]: kfd->info.env.pid = 419
[info_init]: kfd->info.env.tid = 7615
[info_init]: kfd->info.env.maxfilesperproc = 10240
[puaf_init]: method_name = landa
[krkw_init]: method_name = kread_sem_open
[krkw_init]: method_name = kwrite_sem_open
[puaf_helper_give_ppl_pages]: given_ppl_pages = 1698
[puaf_helper_give_ppl_pages]: 🟢 0s 25ms 924us
[puaf_run]: 🟢 0s 32ms 908us
RAM size: 0x7bbe4000, free pages max: 0x13880
[krkw_helper_grab_free_pages]: 🟡 failed to grab free pages goal (goal 40, max 80000, RAM size 0x7bbe4000)
[info_init]: kfd->info.env.pid = 419
[info_init]: kfd->info.env.tid = 7615
[info_init]: kfd->info.env.maxfilesperproc = 10240
[puaf_init]: method_name = landa
[krkw_init]: method_name = kread_sem_open
[krkw_init]: method_name = kwrite_sem_open
[puaf_helper_give_ppl_pages]: given_ppl_pages = 1698
[puaf_helper_give_ppl_pages]: 🟢 0s 23ms 454us
[puaf_run]: 🟢 0s 33ms 763us
RAM size: 0x7bbe4000, free pages max: 0x13880
[krkw_helper_grab_free_pages]: 🟡 failed to grab free pages goal (goal 40, max 80000, RAM size 0x7bbe4000)
[info_init]: kfd->info.env.pid = 419
[info_init]: kfd->info.env.tid = 7615
[info_init]: kfd->info.env.maxfilesperproc = 10240
[puaf_init]: method_name = landa
[krkw_init]: method_name = kread_sem_open
[krkw_init]: method_name = kwrite_sem_open
[puaf_helper_give_ppl_pages]: given_ppl_pages = 1698
[puaf_helper_give_ppl_pages]: 🟢 0s 24ms 107us
[puaf_run]: 🟢 0s 32ms 332us
RAM size: 0x7bbe4000, free pages max: 0x13880
构建硬件读写条件
清理环境
提升权限
Updating BaseBin
将基础套件加载至信任缓存（TrustCache）
初始化环境
Jailbreak failed with error: Error Domain=JBErrorDomain Code=-11 "Spawning jbctl failed with error code 85" UserInfo={NSLocalizedDescription=Spawning jbctl failed with error code 85}

**Comment by dpmaycry** [comment]
> Enable developer mode. @dpmaycry 

Done successfully，thanku
