### ISSUE TITLE
你好多巴胺2，没有应用通知怎么搞

### ISSUE THREAD

**Issue by uuuukka** [opa334/Dopamine#335]
多巴胺2，没有应用通知怎么搞

**Comment by Zhou-Shilin** [comment]
please use english

**Comment by ChumbleDev** [comment]
> please use english

The title says: Hello, dopamine 2, what should I do if there is no application notification?

And the post says: Dopamine 2, what to do without an application notification?

**Comment by xianquu** [comment]
估计是装了乱七八糟的插件
