### ISSUE TITLE
My tweak not work with Dopamine

### ISSUE THREAD

**Issue by tdzard94** [opa334/Dopamine#342]
I make a simple tweak. It's worked on palrea1n
But it's not work when using dopamine
Maybe tweak not inject to any process

**Comment by Zhou-Shilin** [comment]
> I make a simple tweak. It's worked on palrea1n
> But it's not work when using dopamine
> Maybe tweak not inject to any process

palrea1n is a rootful jailbreak but dopamine is rootless
So you need to make your tweak support rootless jailbreak

**Comment by tdzard94** [comment]
> > I make a simple tweak. It's worked on palrea1n
> > But it's not work when using dopamine
> > Maybe tweak not inject to any process
> 
> palrea1n is a rootful jailbreak but dopamine is rootless So you need to make your tweak support rootless jailbreak

Yeah, i know 
My tweak build for rootless and worked on palera1n

**Comment by Zhou-Shilin** [comment]
> > > I make a simple tweak. It's worked on palrea1n
> > > But it's not work when using dopamine
> > > Maybe tweak not inject to any process
> > 
> > 
> > palrea1n is a rootful jailbreak but dopamine is rootless So you need to make your tweak support rootless jailbreak
> 
> Yeah, i know My tweak build for rootless and worked on palera1n

Does your tweak work in other **rootless** jailbreaks? Working in palera1n doesn't mean anything since it's **rootfull** jailbreak.

**Comment by tdzard94** [comment]
> > > > I make a simple tweak. It's worked on palrea1n
> > > > But it's not work when using dopamine
> > > > Maybe tweak not inject to any process
> > > 
> > > 
> > > palrea1n is a rootful jailbreak but dopamine is rootless So you need to make your tweak support rootless jailbreak
> > 
> > 
> > Yeah, i know My tweak build for rootless and worked on palera1n
> 
> Does your tweak work in other **rootless** jailbreaks? Working in palera1n doesn't mean anything since it's **rootfull** jailbreak.

i don't know, i only using palera1n
do u have any sample project that work on dopamine?

**Comment by opa334** [comment]
you gotta be a little more specific than that....
maybe you're missing an arm64e slice?

**Comment by tdzard94** [comment]
> you gotta be a little more specific than that.... maybe you're missing an arm64e slice?

im testing on iphone 6s ios 15.8.1
What i need to do?

**Comment by opa334** [comment]
no clue, also this isn't really a Dopamine issue
