### ISSUE TITLE
Always unsuccessful, tried 26 times iPhone 12 Pro Max(ios15.7.1)

### ISSUE THREAD

**Issue by wen-6** [opa334/Dopamine#344]
![2EBD501F-99F3-425A-B93B-1C9AAE392232](https://github.com/opa334/Dopamine/assets/32879338/044e3668-5c56-48d2-88bc-67fa7faf3c0e)

**Comment by gamer191** [comment]
2.0.5 will include some reliability improvements, wait for that

**Comment by opa334** [comment]
This is an issue with dpkg.
Uninstalling your jailbreak using the toggle/option and try again.
