### ISSUE TITLE
Important camera message after jail breaking with Dopamine 2.0

### ISSUE THREAD

**Issue by gameguru318** [opa334/Dopamine#346]
![image](https://github.com/opa334/Dopamine/assets/38931622/36cccdd2-b1a0-4376-bccc-0d43a365ed9f)
iPhone has never been repaired or taken apart. All parts are original. Camera app and anything else using the camera works properly.

iPhone 13 Pro 16.5

**Comment by opa334** [comment]
why closed? did you fix it?

**Comment by eglacias** [comment]
Interested to know if this is still an issue as well, as this is a piece of hardware I was thinking of buying just a to run this jailbreak
