### ISSUE TITLE
bug found on dopamine

### ISSUE THREAD

**Issue by likertuban** [opa334/Dopamine#347]
iphone X on iOS 16.3.1
1. newterm 3 su doesn't work UNIX authentication refused, unless I do sudo passwd and change the password? not sure if this is normal
2. vpn such as 1.1.1.1 doesn't work (doesn't want to connect, always disconnect, but works on stock/without jailbreak)
3. app such as filza/newterm 3 take a time before opening (black blank for some second before opening) this doesn't happened on palera1n

**Comment by opa334** [comment]
1. not a problem
2. can't reproduce
3. can't reproduce
