### ISSUE TITLE
Lost mobile phone signal

### ISSUE THREAD

**Issue by 1577223884** [opa334/Dopamine#348]
My phone loses signal after jailbreak, but data traffic can be used.in china named 中国电信，Sometimes it's normal, but the probability of normal is low.
![8EEDD2F8-B1B2-43D9-BD0D-26B5A9D84A57](https://github.com/opa334/Dopamine/assets/147258682/c8329288-fbcb-4edb-9838-9087c4b44914)

**Comment by qwer123wd** [comment]
这个外国人用鸡国电信么？他能像老中医一样给你开付中药就能把你治好？

**Comment by wurendao889** [comment]
把卡拿出来，再插就好了

**Comment by bewl87** [comment]
i'm guessing this is a tweak issue. before dopamine i used trollstore to install trolltools and tried to set a custom carrier, it didn't work and resulted in my phone being unable to receive signal. no calls, texts or data until i reverted the custom carrier setting back to default

**Comment by opa334** [comment]
assuming the last comment is right
