### ISSUE TITLE
A15 support issue

### ISSUE THREAD

**Issue by vvanikinvv** [opa334/Dopamine#349]
Hey opa. I know you closed my ticket and said there was support but on ellekit it said A12 and later devices are not supported on iOS 16.6 - 16.6.1, and A15-A16/M2 devices are not supported on iOS 16.5.1 - 16.6.1. I’m sorry cuz I really hate to be that guy but any help would be appreciated

**Comment by vvanikinvv** [comment]
Btw your work is amazing.

**Comment by opa334** [comment]
you initially asked about 16.5, which is supported

**Comment by vvanikinvv** [comment]
I’m currently on iOS 16.5.1 but cannot use dopamine. In the app it says unsupported. I dont really mind though cuz I can use serotonin. Thanks for the help though. Keep up the good work. Btw is there anyway I can donate to you
