### ISSUE TITLE
Issues when share  file from iCloud to Filza

### ISSUE THREAD

**Issue by TweaksDev22** [opa334/Dopamine#351]
Hey 👋 ,  when try to share file from files - icloud to filza  wont add item in filza  but when moving item to files- phone  its working i hope fixing it ... 

And second  problem its about  theos and  newterm the commands  and  installing  theos  not recognizing .zshr , i hope to fix it  .

Also there issues its about  icon app dopamine 2  when reboot device the icon disappears and  sometime  become white some time when click jailbreak get crashing  ..  but  really  this first  jailbreak a best  one  made  faster jailbreak never get crash or random reboot  congratulations opa344 for this hard work ,  keep it up !! We support you ;)

Iphone 13 pro , IOS 15.1

**Comment by opa334** [comment]
that sounds like a filza issue?

**Comment by TweaksDev22** [comment]
Hmm yeah and also its about theos .. ;(

**Comment by opa334** [comment]
regarding theos issue, try rejailbreaking with latest

**Comment by TweaksDev22** [comment]
I try bro nothing work ...
