### ISSUE TITLE
CarPlay

### ISSUE THREAD

**Issue by nahtedetihw** [opa334/Dopamine#353]
When jailbroken with Dopamine, Apple Music app doesn’t show up in CarPlay

**Comment by CangWeiohh** [comment]
After I jailbroke with Dopamine, the carplay car disappeared.

**Comment by nahtedetihw** [comment]
This issue was due to roothide Bootstrap, clicking uninstall in Bootstrap does not deactivate all the selected apps causing them to not work. I had to uninstall Dopamine, reinstall Bootstrap, deselect all apps, uninstall Bootstrap, rejailbreak with Dopamine. (This will remove all installed tweaks on device)
