### ISSUE TITLE
When will iOS 16.6 support A13

### ISSUE THREAD

**Issue by XEYt44** [opa334/Dopamine#354]
![1](https://github.com/opa334/Dopamine/assets/121798130/9f4493d3-7fdd-492b-b002-a3e701bab9c7)

**Comment by X1a0Yue** [comment]
😭😭😭😭�

**Comment by Thyssenkrupp234** [comment]
Not until a PPL bypass is discovered for these devices

**Comment by X1a0Yue** [comment]
Thank you for your answer.
