### ISSUE TITLE
Banking app blocking me

### ISSUE THREAD

**Issue by Bob4716** [opa334/Dopamine#355]
Hi my banking app blocking me. (I have Raiffeisen Bank and I from Czech Republic) is transferring me to banking site and say this:

SAFETY NOTICE

The Raiffeisen Banking application has been discontinued for security reasons.

What happened?

We discovered that a foreign code was inserted into the running mobile banking app that changes its behaviour.

and this:

You're running an app on a jailbroken device, and one of the installed apps tries to insert custom code into mobile banking that changes the app's behavior.

What do I do now?

Any jailbreak bypasses for dopamine?

**Comment by Bob4716** [comment]
I now trying shadow (tweak) but the banking app crashes :/ don't work if you have some experience with this problem and have fix please let me now.

**Comment by TheDoctor200** [comment]
Hiding option in the dopamine settings could work

**Comment by Bob4716** [comment]
Don't work :/ I click on hide jailbreak and try open app and don't work...

**Comment by K1llah03z** [comment]
In shadow turn On every essential Hook except dynamic Libraries. See if that solves the crash! Also should not have any other bypass tweak enabled for the same app

**Comment by malhaar** [comment]
Most of banking apps have jailbreak detection and every app employs different technique. So basically those apps detecting your devices are jailbroken and killing themselves. if you wanna use banking apps i think considering dopamine is rootless, just reboot device in non-jailbroken state and try.

**Comment by Bob4716** [comment]
> Most of banking apps have jailbreak detection and every app employs different technique. So basically those apps detecting your devices are jailbroken and killing themselves. if you wanna use banking apps i think considering dopamine is rootless, just reboot device in non-jailbroken state and try.

So don't exist any tweak to fix my problem?

**Comment by malhaar** [comment]
i dont think so, its really difficult to create one solution that works with all of them. as i explained above every app uses different technique.

**Comment by Bob4716** [comment]
> In shadow turn On every essential Hook except dynamic Libraries. See if that solves the crash! Also should not have any other bypass tweak enabled for the same app

Don't work the app crashes

**Comment by Bob4716** [comment]
> i dont think so, its really difficult to create one solution that works with all of them. as i explained above every app uses different technique.

So you're recommending me to test every single tweak?

**Comment by K1llah03z** [comment]
> > In shadow turn On every essential Hook except dynamic Libraries. See if that solves the crash! Also should not have any other bypass tweak enabled for the same app
> 
> Don't work the app crashes

Are you doing this under the application Settings of shadow? Then scroll to you bank app.. turn On everything but dynamite Libraries and The dangerous hooks at the bottom Of the table. I haD 2 apps that would crash and only these selected Items allowed it to Go through. If it won't Work I Don't know!

**Comment by opa334** [comment]
this is not a support channel

**Comment by roothider** [comment]
> Hi my banking app blocking me. (I have Raiffeisen Bank and I from Czech Republic) is transferring me to banking site and say this:
> 
> SAFETY NOTICE
> 
> The Raiffeisen Banking application has been discontinued for security reasons.
> 
> What happened?
> 
> We discovered that a foreign code was inserted into the running mobile banking app that changes its behaviour.
> 
> and this:
> 
> You're running an app on a jailbroken device, and one of the installed apps tries to insert custom code into mobile banking that changes the app's behavior.
> 
> What do I do now?
> 
> Any jailbreak bypasses for dopamine?

try roothide
