### ISSUE TITLE
Amazon Music Crashes

### ISSUE THREAD

**Issue by JosephFM96** [opa334/Dopamine#356]
All was fine then last night I did the jailbreak with the earlier release and get jb done but after that now my Amazon music app crashes every time I open it .. could it be something related like it detects the jailbroken state or something ???
 I did reinstall it but after the log in and tried to put a song starting to crash again pls any help..

**Comment by opa334** [comment]
either tweak issue or jailbreak detection

**Comment by JosephFM96** [comment]
Roothide could works for jailbreak detection or what can I use for solve it ?
