### ISSUE TITLE
Error iOS 16.0 iPhone 14 pro 

### ISSUE THREAD

**Issue by Fox5Kong** [opa334/Dopamine#357]
Failed to find kernelcache
----
Downloading Kernel
Jailbreak failed with error: Error Domain=JBErrorDomain Code=-1 "Failed to find kernelcache" UserInfo={NSLocalizedDescription=Failed to find kernelcache}

hello, I have this error when jailbreak

**Comment by opa334** [comment]
you need to install Dopamine using TrollStore as this is a factory firmware that has no ipsw
