### ISSUE TITLE
Front Camera works on first start then black screen on iPhone X

### ISSUE THREAD

**Issue by TheDoctor200** [opa334/Dopamine#358]
After 2.0.5 Dopamine Update the Camera isn't working anymore, main camera app works then freezes and gives a black screen afterwards. In all apps like What's App which use camera give black screen. 

Information: 
iOS Version: 16.5.1 
iPhone X

**Comment by TheDoctor200** [comment]
https://github.com/opa334/Dopamine/assets/88980346/500832b3-3b4e-4948-9e8c-194ed821a3fa

Here an example (Camera App)

**Comment by kok3shidoll** [comment]
Do you have a crash log or something?

**Comment by eglacias** [comment]
Camera comes back and all other camera apps which stopped then work fine too after Choicy installed and disable only iOS camera app and its CameraMessagesApp app plugin.
 
I put an issue on here with it, strange and intermittent but at least you can get the camera to work by disabling tweak injection

**Comment by opa334** [comment]
> Camera comes back and all other camera apps which stopped then work fine too after Choicy installed and disable only iOS camera app and its CameraMessagesApp app plugin.
> 
> I put an issue on here with it, strange and intermittent but at least you can get the camera to work by disabling tweak injection

Can you try setting an empty whitelist and see if it works with that aswell? and if it does try to identify what the culpit is by enabling tweaks one by one?

**Comment by Zhou-Shilin** [comment]
#339 duplicate

**Comment by opa334** [comment]
https://github.com/opa334/Dopamine/issues/339 duplicate

**Comment by TheDoctor200** [comment]
sorry for the duplicate issue havent noticed it. 
Thanks for providing the fix :)
@opa334
