### ISSUE TITLE
iOS 16.5.1 showing unsupported on A15 for arm64e

### ISSUE THREAD

**Issue by dontbanmeplz** [opa334/Dopamine#361]
![image](https://github.com/opa334/Dopamine/assets/59851616/3549713c-07ca-4794-acbc-29c48c3dcae3)
![image](https://github.com/opa334/Dopamine/assets/59851616/6e2929a1-1db0-432d-b370-dd797caf9751)

This is coming right from roothide, i did a varclean beforehand. Not sure what the problem is.

**Comment by malhaar** [comment]
From chart in jailbreak discord announcement, i dont think A15 supports 16.5.1, its 16-16.5 & 16.6 beta 1 & 2. So i dont think its an issue.

**Comment by dontbanmeplz** [comment]
Thank you
