### ISSUE TITLE
Dns and vpn cant trigger 

### ISSUE THREAD

**Issue by godsfx** [opa334/Dopamine#367]
Im using dopamine 2.05 on iphone x 1651 but have issue cant trigger/use vpn and dns at first i wonder if its wrong with my isp but i have restarting phone and have found maybe its bug from dopamine

**Comment by Zhou-Shilin** [comment]
Today my proxy suddenly didn't work, but it showed that the proxy was on. I restarted the springboard (“重新启动SpringBoard”) and then everything was fine.

**Comment by WYK15** [comment]
same here, when jailbroken by Dopamine, Shadowrocket cannot trigger. and Shadowrocket works well after reboot

**Comment by EpicSimplyEpic** [comment]
Same here. Related or not, but Find My is also affected; when searching for an individual’s location, soon after it will prevent sms or iMessage to open until the device is rebooted or userspace reboot.

**Comment by Lizynz** [comment]
Same here. Any solution other than reinstalling jailbreak? iPhone X iOS 16.6

**Comment by EpicSimplyEpic** [comment]
> Same here. Related or not, but Find My is also affected; when searching for an individual’s location, soon after it will prevent sms or iMessage to open until the device is rebooted or userspace reboot.

Update: I managed to get VPN’s to work using vnodebypass; I reinstalled SpeedTest with it enabled and managed to get it connected. Disabling vnode went back to not working. Not sure if this applies to DNS settings but an improvement

**Comment by godsfx** [comment]
Thank you so much opa its already fixed on version 2.0.8
