### ISSUE TITLE
Problems after update

### ISSUE THREAD

**Issue by zrsstar** [opa334/Dopamine#368]
dopamine update after demand tollstore respring, then demand switch to "system" registration.Can these operations be automated without manual intervention?

**Comment by Vorshim92** [comment]
![0EB4D8C7-033B-4674-8040-F65B6ABFD45D](https://github.com/opa334/Dopamine/assets/7747380/623e4bff-9af8-4c17-9bc1-b615e5790cfd)
Yes I found this bug yesterday , I think will be fixed soon

**Comment by Zhou-Shilin** [comment]
same issue

**Comment by opa334** [comment]
this is a stock problem just use persistence helper to fix it
