### ISSUE TITLE
2.0.5 update safemode

### ISSUE THREAD

**Issue by neneneche** [opa334/Dopamine#371]
2.0.2 works just fine, when i update to 2.0.5 it instantly sends me in the safemode. when i downgrade back to 2.0.2 apollo needs to be reinstalled because otherwise i keep staying in safemode. I attached the crashlog i got after the update.
[Text.txt](https://github.com/opa334/Dopamine/files/14321965/Text.txt)

**Comment by opa334** [comment]
there is no difference in this between 2.0.2 and 2.0.5.
