### ISSUE TITLE
Unable to Jailbreak 

### ISSUE THREAD

**Issue by UpperType** [opa334/Dopamine#377]
iPhone 11 iOS 15 beta Build: 15.0 (19A5281h)
Latest Dopamine Version via TrollStore. 

Unable to jailbreak with error:

XPF failed with error: (Set "sandbox" failed on "kernelConstant.nsysent")
----
Patchfinding
Jailbreak failed with error: Error Domain=JBErrorDomain Code=-2 "XPF failed with error: (Set "sandbox" failed on "kernelConstant.nsysent")" UserInfo={NSLocalizedDescription=XPF failed with error: (Set "sandbox" failed on "kernelConstant.nsysent")}

**Comment by UpperType** [comment]
Same error with the new version.


Patchfinding
Jailbreak failed with error: Error Domain=JBErrorDomain Code=-2 "XPF failed with error: (Set "sandbox" failed on "kernelConstant.nsysent")" UserInfo={NSLocalizedDescription=XPF failed with error: (Set "sandbox" failed on "kernelConstant.nsysent")}

**Comment by opa334** [comment]
Forgot about this...

**Comment by UpperType** [comment]
New update still not working. Same error.

**Comment by UpperType** [comment]
2.0.8 still does not work

Jailbreak failed with error: Error Domain=JBErrorDomain Code=-2 "XPF failed with error: (Set "badRecovery" failed on "kernelStruct.thread.machine_kstackptr")" UserInfo={NSLocalizedDescription=XPF failed with error: (Set "badRecovery" failed on "kernelStruct.thread.machine_kstackptr")}
Patchfinding

**Comment by UpperType** [comment]
![3317023B-856C-4DCA-97C5-70402D3B31FD](https://github.com/opa334/Dopamine/assets/134170530/076009a6-ab85-44e3-8a5e-bd05a2e2df2e)

I was able to jailbreak. But was not able to install any packages at all. Zebra was the only package manager that worked. The other one did not wanna open. 

Seems like this iOS broke a lot of things.

**Comment by opa334** [comment]
Yeah early 15.0 betas are likely missing symbol exports of important stuff, so most tools do not work. There is nothing that can be done about this afaik.
