### ISSUE TITLE
Cannot install deb through Sileo 

### ISSUE THREAD

**Issue by HRst123** [opa334/Dopamine#379]
Can you help to fix this error? I checked on internet it says that need to make the file system/remount the file system into read and write. I tried using terminal to do that but it denied (IPAD 2021pro M1 arm64e iOS 15.7.1)
![06AD7762-75EF-4D72-A1BF-53F0F60FE3B3](https://github.com/opa334/Dopamine/assets/158029016/df4db387-b8e8-4061-81e0-6f8b73480d4b)

**Comment by TheGamingGallifreyan** [comment]
Whatever that tweak is it hasn't been updated for rootless. You can try to patch it, but it most likely won't work until it gets updated. This isn't a Dopamine problem.

**Comment by HRst123** [comment]
Fixed it Thanks
