### ISSUE TITLE
(A15) iPhone 13 Siri does not work

### ISSUE THREAD

**Issue by Seeike** [opa334/Dopamine#381]
https://github.com/opa334/Dopamine/assets/122684677/90fdf4c3-0b20-45ef-9b89-10d208a34be0

Also can not disable Siri in settings.

**Comment by opa334** [comment]
Please install KrashKop and check for any Siri related crash logs and send them here.

**Comment by Seeike** [comment]
There is no crash with Siri and the latest one is springboard. Also she doesn’t work even out of the jailbroken state. 
[springboard crash.txt](https://github.com/opa334/Dopamine/files/14334551/text.txt)

**Comment by opa334** [comment]
if siri does not work when jailed, this is not an issue with dopamine
