### ISSUE TITLE
Jailbreak detection

### ISSUE THREAD

**Issue by andrewhulse1981** [opa334/Dopamine#383]
Getting the following message when openening RSA Authenticator app. 

![E88D5453-5F81-4C6E-A614-1B914465EA0D](https://github.com/opa334/Dopamine/assets/80646237/d9938f86-c751-4952-8623-521dc5d076ce)

Started doing it when there was an update for dopamine and worked after updating dopamine and opening the app but now just keeps coming up with that message. Tried choice and shadow tweaks but they don’t seem to work with it

thanks

**Comment by bewl87** [comment]
the only two appstore apps i've found that detect jailbreak so far are 'clearscore' and 'hastings direct'. both those apps detected jailbreak when jailed with filza installed but the nourl version of filza didn't trigger detection. hopefully roothide will get an update shortly and fix detection issues

**Comment by Zhou-Shilin** [comment]
There is a lot more to be done for jailbreak hiding. This is the detection I got using Reveil (a sandboxed app).
![E5BE8986-8899-4CD6-986D-2173FB3F1BAF](https://github.com/opa334/Dopamine/assets/86581525/0c438886-d902-4b1f-94fd-46843936731a)

**Comment by opa334** [comment]
There is no work to be done at all interms of jailbreak hiding, because Dopamine does not intend to be undetectable.

**Comment by roothider** [comment]
> Getting the following message when openening RSA Authenticator app.
> 
> ![E88D5453-5F81-4C6E-A614-1B914465EA0D](https://private-user-images.githubusercontent.com/80646237/305756428-d9938f86-c751-4952-8623-521dc5d076ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjUwODIsIm5iZiI6MTczMTY2NDc4MiwicGF0aCI6Ii84MDY0NjIzNy8zMDU3NTY0MjgtZDk5MzhmODYtYzc1MS00OTUyLTg2MjMtNTIxZGM1ZDA3NmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA5NTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MWMyYzc0ZjY5Y2I5YTIxYzFkNzQyODEyMWQ0NGViOTFlYjBkYTY4YjczM2I0ZmNjMTc1YmM0MTA4Y2M1NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZgkQb4dMVsLzGS4LaNuCAjzt0-ORD8dE7Zy0QB3IeGc)
> 
> Started doing it when there was an update for dopamine and worked after updating dopamine and opening the app but now just keeps coming up with that message. Tried choice and shadow tweaks but they don’t seem to work with it
> 
> thanks

try roothide
