### ISSUE TITLE
Dopamine 2.05 breaks appstore purchasing

### ISSUE THREAD

**Issue by The-Crow-Den** [opa334/Dopamine#385]
Currently have 2 devices with dopamine an iPad on 16.1.1 using dopamine 2.0.5 it doesn't allow me to get or purchase apps. On my phone with ios 16.1.1 with dopamine 2.0.4 I have full functionality. I haven't disabled any daemon nor have passbook disabled, tried signing out and signing in. Making me believe this is issue with dopamine thank you for reading this.

**Comment by opa334** [comment]
no it doesn't, it's just some file permissions might be wrong causing app store to no longer work, what exactly is responsible for this no one knows
