### ISSUE TITLE
Boomerang zombie processes getting created on userspace reboot

### ISSUE THREAD

**Issue by ssdsl0126** [opa334/Dopamine#386]
After each reboot userspace, using Cocoatop reveals an additional Boomerang process, which seems to result in extra memory usage

**Comment by opa334** [comment]
that shouldn't happen, can you show a screenshot?

**Comment by cakarlen** [comment]
Can confirm this is also happening on iPhone 14, iOS 16.1

**Comment by TheGamingGallifreyan** [comment]
Also can confirm this issue. Just rebooted userspace twice and sure enough.

iPhone 14 Pro Max 16.4.1

![image](https://github.com/opa334/Dopamine/assets/28023086/26b35108-e4e8-41ee-bb78-d2b1fb0096d7)

However in NewTerm they show up as < defunct >. Attempting to kill them does not work, the processes remain.

![image](https://github.com/opa334/Dopamine/assets/28023086/e2299dfa-2914-455e-9a57-19963e499cbe)

**Comment by ssdsl0126** [comment]
> that shouldn't happen, can you show a screenshot?
![image](https://github.com/opa334/Dopamine/assets/35905829/09c8457b-01c8-4219-8dff-0b6716780a80)
![image](https://github.com/opa334/Dopamine/assets/35905829/66ee274b-ef11-469b-9ea2-d1030cfcba59)
iphone7 plus 15.8.1
Dopamine2.0.5

Just tested, and each time the user space is restarted, an additional one is added.

**Comment by narcyzzo** [comment]
![83A476D0-4752-4DE4-A092-1C3C1AF3FA69](https://github.com/opa334/Dopamine/assets/54555731/6b98e90d-5f16-443d-a63e-541a62dd081e)
Same, 15.1.1 12 Pro

**Comment by opa334** [comment]
I think I fixed it, test latest nightly build:
https://nightly.link/opa334/Dopamine/actions/runs/7978865650/Dopamine.zip
(rejailbreak with it and then do a few userspace reboots)

**Comment by narcyzzo** [comment]
![84A2630A-E7E6-4A2B-BA36-5E3EA32AE174](https://github.com/opa334/Dopamine/assets/54555731/6eafb6e4-fef0-4ee4-92a2-03f8a9ced34c)
Can confirm Its fixed

**Comment by ssdsl0126** [comment]
> I think I fixed it, test latest nightly build:
> 
> https://nightly.link/opa334/Dopamine/actions/runs/7978865650/Dopamine.zip
> 
> (rejailbreak with it and then do a few userspace reboots)

![image](https://github.com/opa334/Dopamine/assets/35905829/c751f683-6134-49f1-9f0e-866d4b742c93)
Fixed
