### ISSUE TITLE
The phone app is not opening when tweak injection is enabled.

### ISSUE THREAD

**Issue by asqude** [opa334/Dopamine#393]
First of all, a very big thank you to everyone who helped develop this jailbreak.

Unfortunately, my phone app does not launch when I have Tweak Injection enabled in the Dopamine App. Even when I disable Tweak injection in Choicy. If there is any information missing, please let me know.
[crash_log.zip](https://github.com/opa334/Dopamine/files/14337390/crash_log.zip)

**Comment by opa334** [comment]
Latest nightly had a fix for an arm64 specific issue, please test and check if this is fixed now:
https://github.com/opa334/Dopamine/actions/runs/8023037614/artifacts/1270506846

**Comment by asqude** [comment]
Apparently everything is working now :) Thank you for the fix ;)
