### ISSUE TITLE
Dopamine failed and Black screen

### ISSUE THREAD

**Issue by znexo** [opa334/Dopamine#397]
iPhone 14 Pro iOS 16.2
After hitting jailbreak, sometimes it will seem like it succeeds, it asks to set a password and install Sileo or Zebra. But after doing those two, Dopamine will fade into a black screen, and I would have to force restart, unless I want to wait the whole (2 minutes and 43) until it panics and reboots on its own. It boots back into stock OS.
Next, since setting a password and choosing Sileo is no longer needed, it doesn’t ask for it. But it does not make it past this point (attached below).
I am unsure how to fetch more useful logs or information, I apologize. Thanks for the hard work
![ECE8D71B-00A0-467B-A891-5489267D146B](https://github.com/opa334/Dopamine/assets/155475413/2e357f7d-64a5-4c08-b88c-0c578bde6ca0)

**Comment by opa334** [comment]
the image did not finish uploading....

**Comment by znexo** [comment]
😅 Lol thanks. I fixed the comment

**Comment by dhinakg** [comment]
Please try this build, it adjusts some parameters to improve kfd success again
https://www.mediafire.com/file/jjc7gbxst6sllle/Dopamine_kfd_tweaks.tipa/file

**Comment by znexo** [comment]
> Please try this build, it adjusts some parameters to improve kfd success again
> https://www.mediafire.com/file/jjc7gbxst6sllle/Dopamine_kfd_tweaks.tipa/file

This seems to work without any problem, I will mess around with it, install a few tweaks, then I’ll mark this solved. Thanks In advance! 😁
