### ISSUE TITLE
Issue with Jailbreak Apps icons not displaying

### ISSUE THREAD

**Issue by ssdsl0126** [opa334/Dopamine#403]
After restarting the phone and jailbreaking for the first time or after a userspace reboot, there is a chance that the jailbreak app icon won't appear. You must refresh the jailbreak app in Dopamine for it to show up.

After refreshing the Jailbreak App, the icons on the desktop will appear in a different layout.

**Comment by Zhou-Shilin** [comment]
> After refreshing the Jailbreak App, the icons on the desktop will appear in a different layout.

same issue

**Comment by opa334** [comment]
You normally don't need to refresh apps in the Dopamine app, in some cases it just takes longer for the jailbreak apps to appear after a userspace reboot because the icon cache is horrendous.
