### ISSUE TITLE
[BUG] Filza is unable to transfer debs into Sileo while using Dynamic Stage.

### ISSUE THREAD

**Issue by korboybeats** [opa334/Dopamine#405]
While using Sileo and Filza together with Dynamic Stage, Filza is unable to import debs into Sileo. When clicking on a deb file, it does nothing and just shows the loading circle for a split second. This is not a tweak issue because I do this all the time on Xina 1 and Xina 2 with no problems.

https://github.com/opa334/Dopamine/assets/80824905/16ee5fc2-bb83-47fa-9a67-970d18f52a66

**Comment by opa334** [comment]
I don't see how this is not a tweak issue.

**Comment by korboybeats** [comment]
> I don't see how this is not a tweak issue.

Because I can do this on Xina 1 and Xina 2? Same versions of the tweaks.
