### ISSUE TITLE
Unable to Install/Uninstall Tweaks with Sileo and Zebra

### ISSUE THREAD

**Issue by Bob4716** [opa334/Dopamine#410]
The error message says: `An unknown error occurred.
APT was unable to find this package.
Please try refreshing your sources
E: Zkomolen'y r'adek 4 v sources
souboru /var/jb/etc/apt/sources.list.d/
sileo.sources (URI parse)
E: Nelze prec'ist seznam zdroju`

This error occurs every time I try to install or uninstall any tweak. I've tried everything, but nothing seems to work. I've searched on Google for fixes, but none of them have worked for me. Both Sileo and Zebra are not functioning properly. Please help

**Comment by Bob4716** [comment]
full translate to en: `An unknown error occurred.
APT was unable to find this package.
Please try refreshing your sources
E: Corrupted line 4 in sources
file /var/jb/etc/apt/sources.list.d/
sileo.sources (URI parse)
E: Unable to parse source list.`

I try to refreshing sources but nothing happen. And I don't have the option to check the files because I don't have Filza or any other file manager. I've tried rejailbreaking... but nothing works :/

**Comment by opa334** [comment]
user error, it tells you line 4 in `/var/jb/etc/apt/sources.list.d/sileo.sources` is corrupted
