### ISSUE TITLE
Jailbreak loop +jb detection problem 

### ISSUE THREAD

**Issue by simdog765** [opa334/Dopamine#411]
I will say the jb worked the first time 
After that I had an issue 
I’m on iPhone 14 pro max 16.2
I have bootstrap, misaka, TrollStore, 
Installed 
With bootstrap I can open my was with no issues 
With dopamine it acts like it kicks you out of app

the big issue I Had 
I couldn’t get into my apps so I rebooted my phone 
After that I kept getting an error (see picture)
So I tried to resolve the issues/conflict 
After that the jb tries to JB but keeps crashing or false jb… sometimes getting to the point asking to make a password 
I uninstalled the jb and reinstalled with no luck 
I removed all other jb tools except TrollStore 
Still no luck
I tried to video record the issues but it never saved 
after hours of messing with it 
I fully uninstalled it from TrollStore 
And reinstalled it with success 

![A4A8F5CC-E149-476E-82F5-BDA8DBB7D3DE](https://github.com/opa334/Dopamine/assets/80208083/256595c8-72b9-4a90-aef1-aaebd439c489)

**Comment by opa334** [comment]
user error, it tells you the issue.
