### ISSUE TITLE
ios 15.4.1 xs max jailbreak not fully working

### ISSUE THREAD

**Issue by hohoho123456** [opa334/Dopamine#412]
I’m using the latest version (dopamine 2.0.6) The jailbreak sends an error message after jailbreak and my tweaks are not fully functioning. Please help. Thanks.

![CEAB5DA8-369B-4561-A0D3-0CB075D1463F](https://github.com/opa334/Dopamine/assets/44559677/e6186ec4-b537-406c-aa45-b62ebd48fa1c)

![F9A7E756-4E0E-44E7-82B5-9E1D447EB4B4](https://github.com/opa334/Dopamine/assets/44559677/ffd8b84c-0687-4c26-b8f2-7d1c89578679)

**Comment by opa334** [comment]
tweak issue
