### ISSUE TITLE
idownloadd not respecting toggle and starts anyway after userspace reboot

### ISSUE THREAD

**Issue by TheGamingGallifreyan** [opa334/Dopamine#413]
idownloadd starts running after jailbreaking, even though the toggle is turned off. 

Toggling it on and back off will end the process.

https://github.com/opa334/Dopamine/assets/28023086/a2985ab5-35c6-49de-9078-4f670c623dba

I'm assuming this isn't intended behavior?

**Comment by cakarlen** [comment]
Can confirm same issue on iPhone 14, iOS 16.1

**Comment by opa334** [comment]
Yeah can reproduce aswell (I swear I tested this at least once and it worked though...)

**Comment by opa334** [comment]
Should be fixed in latest nightly build, please test

https://github.com/opa334/Dopamine/actions/runs/8012495537/artifacts/1268238652

**Comment by narcyzzo** [comment]
![FE94D7D1-4E54-45B4-8017-7F45E1576890](https://github.com/opa334/Dopamine/assets/54555731/c7f57de4-de43-424f-880d-90273272caf5)
Fixed
