### ISSUE TITLE
Urgent！！ 2.0.6 Infinite reboot occurs on multiple devices

### ISSUE THREAD

**Issue by huami1314** [opa334/Dopamine#416]
Three minutes after it was released, my friend and I updated version 2.0.6 and found ourselves unable to enter the system after infinite restarts. We needed to clear the jailbreak environment otherwise we could no longer jailbreak. It was normal to turn off plug-in injection. The problem all appeared in version 15.4.1. , even after switching vulnerabilities, jailbreak is still not possible, respectively 13pro and 13promax

**Comment by opa334** [comment]
There have been a total of 4 changes to the jailbreak environment.
All of them are very small fixes for isolated bugs and have been verified to work, there is no way for such a regression could exist.

**Comment by huami1314** [comment]
But as mentioned above, the same infinite restart problem occurred on both devices.

**Comment by huami1314** [comment]
Okay, is it possible that it's a plug-in problem?

**Comment by huami1314** [comment]
![9B730D15-67AF-438E-A944-21975E312673](https://github.com/opa334/Dopamine/assets/99124359/9c351179-16ec-4135-a148-e1a43aa2d085)
Supplement, multiple people have the same problem

**Comment by huami1314** [comment]
@opa334 Sorry to bother you, many people in the Chinese jailbreak community have reported that infinite restarts occur when using 15.4.1.

**Comment by opa334** [comment]
> Okay, is it possible that it's a plug-in problem?

yes
