### ISSUE TITLE
frida does not work in dopamine 2.0.6.

### ISSUE THREAD

**Issue by kargans** [opa334/Dopamine#417]
frida does not work in dopamine 2.0.6.

Frida ver : 16.2.1
Iphone X 15.2

Please fix it.

**Comment by opa334** [comment]
Can't reproduce, works fine on my end (Xs, 15.4.1).

**Comment by kargans** [comment]
![20240223_131727](https://github.com/opa334/Dopamine/assets/47530096/93da9a64-8a8d-4a67-bfa6-200c764fae6c)
![20240223_131832](https://github.com/opa334/Dopamine/assets/47530096/1b06fc65-23f9-4f4f-9341-0fc624acefd7)
Frida not working for me.
Spawn and attach both not working.
