### ISSUE TITLE
Apple daemon always crashing causing battery drain

### ISSUE THREAD

**Issue by xelahot** [opa334/Dopamine#421]
Since I started using Dopamine, my battery drains WAY faster. I figured out with CocoaTop that the   daemon ´/System/Library/PrivateFrameworks/SeymourServices.framework/fitcored" crashes right after launching then restarts, then crashes, in loop... This shows as the highest in the CPU usage % column of Cocoatop. I guess that's why my battery is drained so fast and I feel like it since I jailbroke. I tried disabling tweak injection with Dopamine to see if it is caused by a tweak but it stills crashes in loop. Maybe it have something to do with the jailbreak itself.

**Comment by opa334** [comment]
Check if KrashKop has any crash log for the daemon and if so, send it

**Comment by xelahot** [comment]
I saw crash logs for fitcore but they were from 2 days old (I tried converting tweaks to support rootless with Derootifier 2 days ago). But I saw no crash log for today. So I cleared the logs. Weird thing is it looks like it's crashing non-stop in CocoaTop. There's a new ID everytime it restarts. So I'm not sure why KrashKop doesnt show those crashes. It's still doing it. I'm not sure how I can help. I'm using  the 2.0.6 release. I also tried disabling all tweaks with Choicy instead of doing it with Dopamine. With Choicy I could see that the process would still have Ellekit loaded though. By disable tweak with the Dopamine app, Ellekit was also gone but the daemon was still crashing and consumming CPU.

**Comment by opa334** [comment]
any crash log will do it....

**Comment by xelahot** [comment]
There's no crash log right now but it's crashing non-stop. Look at the top of the list how every 5 seconds it tries to restart.
https://github.com/opa334/Dopamine/assets/44215345/2632a912-d18f-45f7-a91b-0d4df98e7dfb

**Comment by opa334** [comment]
That is completely useless to me, you should have just sent a crash log instead of clearing them. If you have access to a Mac, you could use Console.app to filter for fitcored and send me the output. Other than that, I don't really know how to help you.

**Comment by xelahot** [comment]
From what I see in CocoaTop when playing with columns, the daemon lives for 1 second. It's launched by launchd. And it goes from "at least one thread is running" to "all threads are sleeping".

**Comment by opa334** [comment]
that once again is very useless information. I read online that this might be a stock issue when removing the fitness app, maybe try redownlading that in case you deleted it?

**Comment by xelahot** [comment]
You're a genius! I indeed deleted that app. I reinstalled it and now the daemon stops crashing 😂 Nice job Apple. Seems lime it have nothing to do with Dopamine or tweak injection! Thanks you! 

nanotimekitcompaniond seems to do the same thing, I also deleted the Watch stock app. It fixes it too.
