### ISSUE TITLE
Issues with some applications after jailbreaking

### ISSUE THREAD

**Issue by v81d** [opa334/Dopamine#422]
## **Symbolab's colors corrupt after jailbreak**
**Before Jailbreaking:**

![Screenshot](https://github.com/opa334/Dopamine/assets/92650958/7258bca8-bf7b-4a13-977d-ce0bc256fac6)

**After Jailbreaking:**

![Screenshot](https://github.com/opa334/Dopamine/assets/92650958/836c347b-0890-485f-96f7-fa6d946888be)

- As depicted in the above images, the entire user interface of Symbolab corrupts on a jailbroken device. Meanwhile, no issues were prevalent in the app before the jailbreak.
- Both pictures were taken on the same device: iPad (9th generation), iPadOS 16.1.1 (20B101).
- Jailbroken with kfd, physpuppet using Dopamine version 2.0.6.

## **Sweatcoin crashes upon opening the app (unsupported in the App Store)**
- Sweatcoin crashes upon opening if it is already installed before the jailbreak.
- If not already installed, Sweatcoin appears incompatible with compatible devices in App Store ("Not compatible with this device. See full list of compatible devices.").

## These are all the issues I have encountered so far. However, more may exist on other services.

**Comment by bewl87** [comment]
disable tweak injection into sweatcoin with choicy

**Comment by bewl87** [comment]
and of course disable tweaks in symbolab 👌

**Comment by opa334** [comment]
sweatcoin is jailbreak detection, what the other app is I do not know however.
