### ISSUE TITLE
Error -6

### ISSUE THREAD

**Issue by trevmont65** [opa334/Dopamine#424]
![IMG_3896](https://github.com/opa334/Dopamine/assets/70174686/31ede077-021e-4e92-98d3-47864074ea13)

So after this error, I return to the dopamine app and it says jailbroken. I respring and I’m jb. But obviously something’s not right. Also my FaceTime doesn’t work but that could be due to a tweak.

**Comment by opa334** [comment]
I think this error is a fluke, just reboot + rejb until it works
