### ISSUE TITLE
Watchdog Timeout Warning

### ISSUE THREAD

**Issue by yanyaoli** [opa334/Dopamine#425]
**Dopamine Information:** Dopamine 2.06 

**Device Information:** iPhone XR 16.3

**Issue Description:**

I installed Crane-rootless from the following source: Crane(rootless) - sileo://package/com.hk.rootless.crane - from https://xiangfeidexiaohuo.github.io/. After successfully downloading Crane-rootless and restarting Springboard, my phone's desktop became unusable. 

I attempted a forced restart, but Dopamine became unavailable. I tried converting it to a System app in TrollStroe, then attempted to re-jailbreak. After the device went through multiple restarts and successfully entered the desktop, I received a Watchdog Timeout alert.

After waiting a few seconds, the jailbreak environment was restored. I immediately deleted the relevant software packages and dependencies in Sileo. However, a libkrw Plug-in(Dopamine) appeared in the Sileo program.

**Request for Help:**

Do I need to delete the libkrw Plug-in(Dopamine)? What further actions do I need to take to restore the safety and stability of the jailbreak environment?

I would like to express my gratitude and best wishes to the authors of the open-source repository. Your work is greatly appreciated.

![error](https://github.com/opa334/Dopamine/assets/120553430/c9570e80-441a-422f-b2f7-63d847cb5162)

**Comment by opa334** [comment]
You installed an outdated pirated Crane build that does not support the version you're running.

This also does not have anything to do with libkrw.
