### ISSUE TITLE
Dopamine 2.0.6越狱后，电池用量信息无法载入

### ISSUE THREAD

**Issue by abc1593373** [opa334/Dopamine#426]
![IMG_0479](https://github.com/opa334/Dopamine/assets/159170415/c0afca8e-95ac-4688-ae35-1d45b358eea9)

**Comment by abc1593373** [comment]
![IMG_0480](https://github.com/opa334/Dopamine/assets/159170415/a68be910-493e-4f0b-b599-bdaf12b9343c)

查阅资料后发现ios13越狱也有此问题，可通过插件修复，希望更新支持ios16系统

**Comment by opa334** [comment]
already fixed in latest nightly. no, powerlogHelperdFix has not been needed in years.
feel free to test: https://nightly.link/opa334/Dopamine/actions/runs/8024937100/Dopamine.zip
