### ISSUE TITLE
Problem with editing binary apps not working

### ISSUE THREAD

**Issue by maansial** [opa334/Dopamine#427]
On iPad mini 5 iPadOS 16.1.1 (20B101) Problem with editing binary apps not working,
I only edit one offset in filza hex editor app not run

Same app binary edit work fine on my iphone with palera1n
Please guide me

**Comment by opa334** [comment]
ldid -s <path/to/binary>

**Comment by maansial** [comment]
> ldid -s <path/to/binary>

iPad:~ root# ldid -s /var/containers/Bundle/Application/C1E2DD7F-8D9F-42ED-8AF6-BD224C2C2CE/ShadowTrackerExtra.app/ShadowTrackerExtra
1did.cpp (2178) :
_assert () : open(): /var/containers/Bundle/Application/C1E2DD7F-8D9F-42ED-8AF6-BD224FC2C2CE/ShadowTrackerExtra.
app/.ldid. ShadowTrackerExtra

No luck

**Comment by maansial** [comment]
> ldid -s <path/to/binary>

iPad:~ root# ldid -s /var/containers/Bundle/Application/C1E2DD7F-8D9F-42ED-8AF6-BD224C2C2CE/ShadowTrackerExtra.app/ShadowTrackerExtra
ldid.cpp (2178) :
_assert () : open(): /var/containers/Bundle/Application/C1E2DD7F-8D9F-42ED-8AF6-BD224FC2C2CE/ShadowTrackerExtra.
app/.ldid. ShadowTrackerExtra

**Comment by opa334** [comment]
Copy the binary elsewhere, resign it, copy it back.

**Comment by maansial** [comment]
> Copy the binary elsewhere, resign it, copy it back.

still same problem, 

should I remove jailbreak and reset to factory settings, and jailbreak again ?

**Comment by opa334** [comment]
> > Copy the binary elsewhere, resign it, copy it back.
> 
> still same problem,
> 
> should I remove jailbreak and reset to factory settings, and jailbreak again ?

What would that solve? the issue is simply that writing to /var/containers is locked behind the `com.apple.private.security.storage.AppBundles` entitlement, rejailbreaking will not solve this.

**Comment by maansial** [comment]
_> > > Copy the binary elsewhere, resign it, copy it back.
> > 
> > 
> > still same problem,
> > should I remove jailbreak and reset to factory settings, and jailbreak again ?
> 
> What would that solve? the issue is simply that writing to /var/containers is locked behind the `com.apple.private.security.storage.AppBundles` entitlement, rejailbreaking will not solve this._

i moved binary to **/var/mobile/Documents** then sign with ldid -s <binary path>
after signing file size changed 6mb less than original 
then i move back binary to original place run the app instant crash

**Comment by maansial** [comment]
> > > Copy the binary elsewhere, resign it, copy it back.
> > 
> > 
> > still same problem,
> > should I remove jailbreak and reset to factory settings, and jailbreak again ?
> 
> What would that solve? the issue is simply that writing to /var/containers is locked behind the `com.apple.private.security.storage.AppBundles` entitlement, rejailbreaking will not solve this.

i moved binary to /var/mobile/Documents then sign with _ldid -s <binary-path>_ 
after signing file size changed 6mb less than original
then i move back binary to original place run the app instant crash

**Comment by maansial** [comment]
> > > Copy the binary elsewhere, resign it, copy it back.
> > 
> > 
> > still same problem,
> > should I remove jailbreak and reset to factory settings, and jailbreak again ?
> 
> What would that solve? the issue is simply that writing to /var/containers is locked behind the `com.apple.private.security.storage.AppBundles` entitlement, rejailbreaking will not solve this.

i moved binary to /var/mobile/Documents then sign with _ldid -s binary-path_
after signing file size changed 5mb less than original
then i move back binary to original place run the app instant crash
