### ISSUE TITLE
cc module

### ISSUE THREAD

**Issue by 160255** [opa334/Dopamine#430]
24.02.24

Re:  Dopamine v2  

Ist es möglich, ein Dopamin v2 CC-Module zu erstellen?

Wenn ja, geben Sie dies bitte an.

Vielen Dank

Is it possible to create a Dopamine v2  CC Module ?

If so, please provide.

Thank you

**Comment by opa334** [comment]
Not sure what you want? "A CC module" sure, just as before.

A CC module shipped by Dopamine itself? no
