### ISSUE TITLE
[2.0.7/arm64 only] Proxy based VPNs break and iCloud services in Settings lose internet access

### ISSUE THREAD

**Issue by KikMyaz** [opa334/Dopamine#431]
Latest Dopamine 2.0.7 appears to cause VPNs to break on arm64 A11 devices

Other arm64e based devices and lower Dopamine versions seem unaffected. 

This bug is texted on a clean install of iOS with only a proxy based VPN app and Dopamine 2.0.7. Reverting back to 2.0.6 fixes everything.

**Comment by KikMyaz** [comment]
Regression potentially introduced here or after

https://github.com/opa334/Dopamine/commit/4152e961a4396afef4926acfff66a2e5acf8c9d6

Older versions and non-arm64 devices are not affected.

**Comment by opa334** [comment]
Please test the following three builds

https://github.com/opa334/Dopamine/actions/runs/8012495537/artifacts/1268238652

https://github.com/opa334/Dopamine/actions/runs/8023037614/artifacts/1270506846

https://github.com/opa334/Dopamine/actions/runs/8024937100/artifacts/1270945760

Which ones work, which ones don't?

**Comment by KikMyaz** [comment]
Only the first build (https://github.com/opa334/Dopamine/actions/runs/8012495537/artifacts/1268238652) appears to work - the others both have issues with VPN

**Comment by KikMyaz** [comment]
Yep this appears to be the last build that still has VPN and iCloud stuff fully functioning https://github.com/opa334/Dopamine/actions/runs/8012495537

**Comment by opa334** [comment]
this is annoying :/

**Comment by opa334** [comment]
Should be fixed in last nightly, please test https://github.com/opa334/Dopamine/actions/runs/8033545584/artifacts/1272369758

**Comment by KikMyaz** [comment]
Can confirm the VPN issue is fixed on that nightly build, thank you so much!

However iCloud services still appear to have issues on this build - would reckon this would be a different regression introduced in 2.0.7. The symptom is iCloud at top of Settings -> Sign out being greyed out when jailbroken. Similarly, this other issue was not present on 2.0.6 but only in 2.0.7 (including the nightly build above).

**Comment by KikMyaz** [comment]
Okay if I was to take a random guess, it could be another binary under /usr/libexec getting hooked by accident and broke stuff, not entirely sure where to go after that :/
