### ISSUE TITLE
Filza not working with Dopamine (IOS 15.5)

### ISSUE THREAD

**Issue by Smokey2418** [opa334/Dopamine#433]
Hi! 

Been trying to resolve this issue. Is it only me?? 

I’m running on iOS 15.5 iPhone XR. 

Have tried everything but can’t seem to find the problem. 

Happy for your help!!
![1A4360F2-A04B-46CE-9D0C-BE6D5CCD554E](https://github.com/opa334/Dopamine/assets/161165638/e8c550e1-88da-4543-b23c-8c7740208309)
![0D89169B-AFAF-4763-86C4-4E22B4BC66B2](https://github.com/opa334/Dopamine/assets/161165638/b9436ece-d9c0-4874-bb51-2e58205eaa1d)

**Comment by opa334** [comment]
installing rootful debs is not supported
