### ISSUE TITLE
2.0.7最新问题，Apple ID部分选项灰色。VPN无法连接

### ISSUE THREAD

**Issue by abc1593373** [opa334/Dopamine#435]
2.0.7，iPhonex16.4越狱后Apple ID部分选项灰色，vpn连接提示网络错误
![IMG_0514](https://github.com/opa334/Dopamine/assets/159170415/6130d20f-4f04-45cc-ac31-717a99a892bd)
![IMG_0515](https://github.com/opa334/Dopamine/assets/159170415/3b4a4e72-6d97-4dcc-9962-831dd410368f)
![IMG_0512](https://github.com/opa334/Dopamine/assets/159170415/82a44b38-76ef-43ab-831f-98f0cb99f0e0)

**Comment by opa334** [comment]
Fixed in 2.0.8
