### ISSUE TITLE
Dopamine 2.0.8

### ISSUE THREAD

**Issue by OverWatch-R** [opa334/Dopamine#437]
1- ive got freeze like 30s on Home Screen 
2-Translomatic tweak is asking for activation while it's already activated
2- settings took time to open a long time 
I did not have this issue in 2.0.6

**Comment by rasch3n** [comment]
I agree!
Settings doesn’t open at all. Trollstore also doesn’t open. And I saw in KrashKop that terminusd is constantly crashing

**Comment by Mehranullah2017** [comment]
2.0.8 battery drains alot
Should i wait for 2.0.9 or downgrade back to 2.0.6

**Comment by OverWatch-R** [comment]
⚠️ issues fixed 2.0.8

I’m so sorry about what I said earlier about issues in Dopamine 2.0.8 
Everything is working now fine since I’ve updated Twitter to latest version 
Translomatic is working 💯
 
Thanks opa334

**Comment by OverWatch-R** [comment]
Settings not opening and can go to 1 mn

**Comment by opa334** [comment]
terminusd issue should be fixed... if you OTA updated try reboot + rejailbreak

On my test device everything works now

**Comment by OverWatch-R** [comment]
40°C on my phone 🤯
And battery draining also 
Not using even 30% of the phone 🤷🏻‍♂️

**Comment by opa334** [comment]
Tested 2.0.8 on
iPhone SE, 15.7.9
iPhone X, 16.6

No battery drain on either of them, issue is therefore invalid.

**Comment by opa334** [comment]
Fixed in 2.0.10+
