### ISSUE TITLE
2.0.8, 6, etc. issues within SE 2nd edition 

### ISSUE THREAD

**Issue by jayk1961** [opa334/Dopamine#439]
iOS 16.3.1. Successfully JB’s, can install/update etc using Sileo or Zebra. Added Newterm3, OpenSSH, developer shell.

Can’t ssh in. Connects but closes. NewTerm immediately says Session Ended. Reset phone, removed JB, reinstalled system-cmds, openssh, etc. Same problem.

JB two iPhone 12s and iPad 9th gen with same IPA and Sideloadly without issue with ssh or newterm. Seems specific to 2nd Edition SE and/or iOS 16.3.1. Can’t log in to see what errors there might be.

**Comment by Mikasa-san** [comment]
Install Terminal from this repo - siieo.github.io

**Comment by Mikasa-san** [comment]
seems like you have to "chown root:wheel /private/preboot " or use Filza to change the ownership to root:wheel of preboot folder in /private

**Comment by opa334** [comment]
Fixed in 2.0.11
