### ISSUE TITLE
I try open Sileo then crash..then i open KrashKop

### ISSUE THREAD

**Issue by hagomoro333** [opa334/Dopamine#440]
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: DYLD 1 Library missing
Library not loaded: @rpath/libzstd.1.dylib
Referenced from: <63D2789A-9671-3432-BB12-A24EF4C7185A> /Volumes/VOLUME/*/Sileo.app/Sileo
Reason: tried: '/usr/lib/swift/libzstd.1.dylib' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/libzstd.1.dylib' (no such file), '/opt/procursus/lib/libzstd.1.dylib' (no such file), '/private/preboot/Cryptexes/OS/opt/procursus/lib/libzstd.1.dylib' (no such file), '/var/jb/usr/local/lib/libzstd.1.dylib' (no such file), '/private/preboot/Cryptexes/OS/var/jb/usr/local/lib/libzstd.1.dylib' (no such file), '/var/jb/usr/lib/libzstd.1.dylib' (no such file), '/private/preboot/Cryptexes/OS/var/jb/usr/lib/libzstd.1.dylib' (no such file), '/usr/lib/libswift/stable/libzstd.1.dylib' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/libswift/stable/libzstd.1.dylib' (no such file), '/usr/lib/swift/lib
(terminated at launch; ignore backtrace)

**Comment by opa334** [comment]
you removed some essential package / file. Remove jailbreak, the rejailbreak.
