### ISSUE TITLE
2.0.8 battery drains 

### ISSUE THREAD

**Issue by Mehranullah2017** [opa334/Dopamine#441]
2.0.8 battery drains alot
Should i wait for 2.0.9 or downgrade back to 2.0.6?

**Comment by opa334** [comment]
Out of the changes in 2.0.7 and 2.0.8 there is not a single one that could have introduced battery drain, especially not on arm64e.

**Comment by Mehranullah2017** [comment]
Thanks
I will review the new tweaks i installed i think there will be the problem
