### ISSUE TITLE
10 out of 10 times it panics

### ISSUE THREAD

**Issue by louisbenne** [opa334/Dopamine#442]
It panics when trying to jailbreak with dopamine 2. If it doesn't panic it will go into a watch dog time out and disables tweak injection. If I try to enable tweak injection it goes back into a watch dog time out and it goes on etc. also phone gets really hot.

iphone 14 pro max iOS 16.6 b1 
Older version did the same but got fixed then in latest update it have come back.

**Comment by opa334** [comment]
tweak issue
