### ISSUE TITLE
Duplicate Sileo Despite Proper Bootstrap Removal

### ISSUE THREAD

**Issue by pythonr0ck** [opa334/Dopamine#443]
I originally installed Dopamine 2.0.1 and I think I might have the multiple bootstraps issue, but I'm not sure because I may have installed 2.0.2 instead. I followed the steps in https://www.reddit.com/r/jailbreak/comments/1asderz/please_properly_uninstall_bootstrapserotonin_if/?sort=new, but I keep getting an error about how I have a duplicate sileo. I‘ve tried uninstalling dopamine through the interface and reinstalling roothide bootstrap to try to var clean again, but the error still persists. I don’t have a previous jb on this device and I’ve uninstalled bootstrap and serotonin properly, so I’m not sure why this error still persists.

Workaround: Seems like I can bypass this by moving Sileo.app out of /private/preboot/xxx/dopamine-mUnZU/procursus/Applications before jailbreak through ts filza and moving it back in after a rejailbreak and then refreshing jb apps with dopamine. The issue of the duplicate Sileo still exists after reboot and rejailbreak though.

The exact error says: The apps with the identifiers [org.coolstar.SileoStore] exist in Dopamines application directory ("/private/preboot/xxx/dopamine-mUnZU/procursus/Applications") but are also installed separately on the system. Cannot continue.

**Comment by opa334** [comment]
This means you have an with the identifier `org.coolstar.SileoStore` installed in TrollStore or sideloaded. Remove that.
