### ISSUE TITLE
iphone 8 ios15.6 Jailbreak failed with error

### ISSUE THREAD

**Issue by fsleo** [opa334/Dopamine#445]
Jailbreak failed with error: Error Domain=JBErrorDomain Code=-1 "Failed to find kernelcache" UserInfo={NSLocalizedDescription=Failed to find kernelcache}
Downloading Kernel

**Comment by opa334** [comment]
If you're on a beta version, ensure you install Dopamine with TrollStore.

**Comment by yynag** [comment]
same issue, reboot device is a workaround.
