### ISSUE TITLE
The issue occurs after a userspace reboot.

### ISSUE THREAD

**Issue by ssdsl0126** [opa334/Dopamine#448]
After reboot, Dopamine automatically changes to "User," which prevents it from opening. It needs to be switched to "System" using Trollstore to function properly.

**Comment by ssdsl0126** [comment]
> After reboot, Dopamine automatically changes to "User," which prevents it from opening. It needs to be switched to "System" using Trollstore to function properly.

It should be said that it occurs after Dopamine OTA, not userspace reboot.

**Comment by opa334** [comment]
This is normal and can happen in some cases, it's why the persistence helper exists.
