### ISSUE TITLE
2.08 iphone 14 pro

### ISSUE THREAD

**Issue by User21907654** [opa334/Dopamine#449]
Hello!

since the beginning i have a « random issue. »

1/ My device : iphone 14 pro 16.2 
(I am always on dopamine last version i do all updates in the app itself)

2/ issue description : after a while i cant open mail app and real mails just a blank screen. My phone seems hanging and slow as if something big was using some big ressources after a while…
I am still in jailbreak mode when the issue occurs.
i cant open anymore dopamine app even after a repring with trollstore.

3/ How i manage to fix the issue :
i had to force restart uninstall dopamine with trollstore (dopamine app was blank) and install again jailbreak again and it is now working but maybe tomorrow morning i will have to do the same…

maybe i can send you some log file? Just tell me.

best regards.

**Comment by User21907654** [comment]
Hello opa did you check my issue please? Again everyday mail app is blank when i open it somerimes it is safari app… only fix is to force reboot and rejelbrek please help me

**Comment by User21907654** [comment]
Nos it is the calendar app i just had to restart environnement again because i had no more rdv in it. After restart environnement its ok… why it is occuring it is at least one time per day now…

**Comment by opa334** [comment]
> Hello opa did you check my issue please? Again everyday mail app is blank when i open it somerimes it is safari app… only fix is to force reboot and rejelbrek please help me

What do you expect me to do? What should I check? I am not aware of a single thing in Dopmaine that could cause something like this.

Maybe send me a sysdiagnose to opa334@protonmail.com right after the issue is happening https://it-training.apple.com/tutorials/support/sup075.

**Comment by User21907654** [comment]
I just sent you by mail two sys diagnoses… 
Problem is random : mail app wont open blanck screen until dopamine restart environment is done.

today two times problem occured its almost everydays…


 since i have jailbroken problem occurs since the first dopamine versions last monthes…

i hope you can help me

thanks for your time

**Comment by opa334** [comment]
This is caused by `WoNiuAlways120.dylib`, although the root cause may also be in ellekit. It seems to be deadlocking `maild`, which causes it to fail to respond to messages.

**Comment by User21907654** [comment]
Thanks a lot for your time for helping me !

I will try disable always 120 if you have an other possible fix please let me know

Have a good subday

Thanks again my friend

Le 20 avr. 2024 à 16:40, Lars Fröder ***@***.***> a écrit :

﻿

This is caused by WoNiuAlways120.dylib, although the root cause may also be in ellekit. It seems to be deadlocking maild, which causes it to fail to respond to messages.

**Comment by User21907654** [comment]
Hello sir !

I have a problem

I have ios phone 14pro ios 16.2 dopamine 2.4.5 (i had previously 2.2.2 since yesterday it was same problem i thought updating woule solve but not)

In cocoatop i see bulletindistributord and remindd every 5/10 sec i think it drains my battery

When i opened remind app it was blank screen only while jailbroken maybe it is related.

I deleted the remind app but its same problem.

Please can you help me i will send you what you need.

(For information : You already fixed a problem for me long time ago with always120 conflict see above thanks again for that now it is ok.)

Best regards



Le 20 avr. 2024 à 16:40, Lars Fröder ***@***.***> a écrit :

﻿

This is caused by WoNiuAlways120.dylib, although the root cause may also be in ellekit. It seems to be deadlocking maild, which causes it to fail to respond to messages.
