### ISSUE TITLE
Still cannot use VPN with iPhone X 16.6 Dopamine2.0.8

### ISSUE THREAD

**Issue by baoan7090** [opa334/Dopamine#454]
I've tried remove jailbreak and jailbreak again, and the vpn still cannot work. (It works on 2.0.6 and down)

Device: iPhone X (iPhone 10,3)
iOS: 16.6
Dopamine: 2.0.8

**Comment by opa334** [comment]
Works fine for me on exactly the same device.

**Comment by ioiy** [comment]
I have the same problem with my iPhone x, which is version 16.6.1

**Comment by 1048969852** [comment]
Uploading -2519024895271643364.mp4…

**Comment by baoan7090** [comment]
> Works fine for me on exactly the same device.

Thanks for your test.

I have tried about 3 times, the VPN still cannot open.

Have any other method can try?

**Comment by opa334** [comment]
> > Works fine for me on exactly the same device.
> 
> Thanks for your test.
> 
> I have tried about 3 times, the VPN still cannot open.
> 
> Have any other method can try?

Can you give me a list of packages you have installed? Can you check if it works if you reinstall the jailbreak environment and don't install anything?

**Comment by baoan7090** [comment]
> > > Works fine for me on exactly the same device.
> 
> > 
> 
> > Thanks for your test.
> 
> > 
> 
> > I have tried about 3 times, the VPN still cannot open.
> 
> > 
> 
> > Have any other method can try?
> 
> 
> 
> Can you give me a list of packages you have installed? Can you check if it works if you reinstall the jailbreak environment and don't install anything?

I have tried reinstall the jailbreak environment and don't install anything, the VPN still not working.
 
These are installed packages:

3DAppVersionSpoofer:(com.0xkuj.3dappversionspoofer) 2.0.4
ActionBar Reborn:(netskao.actionbarreborn) 1.1-2
AltList:(com.opa334.altlist) 1.0.10
AppData-Rootless:(netskao.appdata-rootless) 1.4.1
apt:(apt) 2.7.1
AutoFaceUnlock-Rootless:(netskao.autofaceunlock-rootless) 1.1-7
base:(base) 1-6
bash:(bash) 5.2.15
ca-certificates:(ca-certificates) 20230910
chariz-keyring:(chariz-keyring) 2021.07.18
coreutils:(coreutils) 9.4
darwintools:(darwintools) 1.6
dash:(dash) 0.5.12
debianutils:(debianutils) 5.7-1
diffutils:(diffutils) 3.9
diskdev-cmds:(diskdev-cmds) 697
Dopamine BaseBin Link:(dopamine-basebin-link) 1.0.0
dpkg:(dpkg) 1.22.0
ElleKit:(ellekit) 1.1.2
essential:(essential) 0-5
file-cmds:(file-cmds) 400-1
findutils:(findutils) 4.9.0
gpgv:(gpgv) 2.4.3
grep:(grep) 3.11
havoc-keyring:(havoc-keyring) 2022.06.03
launchctl:(launchctl) 1:1.1.1
libapt-pkg6.0:(libapt-pkg6.0) 2.7.1
libassuan0:(libassuan0) 2.5.6
libbrotli1:(libbrotli1) 1.1.0
libcrypt2:(libcrypt2) 4.4.36
libdimentio0:(libdimentio0) 1:0~20230202.7ffffff
libedit0:(libedit0) 3.1-20230828
libffi8:(libffi8) 3.4.4
libgcrypt20:(libgcrypt20) 1.10.2
libgmp10:(libgmp10) 6.3.0
libgnutls30:(libgnutls30) 3.8.1
libgpg-error0:(libgpg-error0) 1.47
libhogweed6:(libhogweed6) 3.9.1
libidn2-0:(libidn2-0) 2.3.4
libintl8:(libintl8) 0.22
libiosexec1:(libiosexec1) 1.3.1
libkrw Plug-in (Dopamine):(libkrw0-dopamine) 2.0.1
libkrw0:(libkrw0) 1.1.1
liblz4-1:(liblz4-1) 1.9.4
liblzma5:(liblzma5) 5.4.4
libmd0:(libmd0) 1.1.0
libncursesw6:(libncursesw6) 6.4
libnettle8:(libnettle8) 3.9.1
libnpth0:(libnpth0) 1.6-2
libp11-kit0:(libp11-kit0) 0.25.0
libpam-modules:(libpam-modules) 1000.0
libpam2:(libpam2) 20230627
libpcre1:(libpcre1) 8.45-1
libpcre2-8-0:(libpcre2-8-0) 10.42
libreadline8:(libreadline8) 8.2.0-1
libroot (Dopamine):(libroot-dopamine) 1.0.1
libssl3:(libssl3) 3.0.10
libtasn1-6:(libtasn1-6) 4.19.0
libunistring5:(libunistring5) 1.1
libxxhash0:(libxxhash0) 0.8.2
libz-ng2:(libz-ng2) 2.1.3
libzstd1:(libzstd1) 1.5.5
mineland:(com.34306.mineland) 2.0-6+debug
ncurses-bin:(ncurses-bin) 6.4
ncurses-term:(ncurses-term) 6.4
PerfectXTime-Rootless:(netskao.perfectxtime-rootless) 1.1-3
PreferenceLoader:(preferenceloader) 2.2.6-1
procursus-keyring:(procursus-keyring) 2020.05.09-4
profile.d:(profile.d) 0-7
sed:(sed) 4.9
shell-cmds:(shell-cmds) 278-2
shshd:(shshd) 1.1.1.1
Sileo:(org.coolstar.sileo) 2.5
snaputil:(snaputil) 12.3
sudo:(sudo) 1.9.14p3
System Info 系统信息-Rootless:(com.wxhbts.systeminfo.rootless) 2.7.2-3
system-cmds:(system-cmds) 950-2
tar:(tar) 1.35
uikittools:(uikittools) 2.1.6-1
vi:(vi) 070224
zsh:(zsh) 5.9
左滑返回-Rootless:(com.25mao.leftpan.rootless) 1.0-5

**Comment by opa334** [comment]
> > > > Works fine for me on exactly the same device.
> > 
> > 
> > > 
> > 
> > 
> > > Thanks for your test.
> > 
> > 
> > > 
> > 
> > 
> > > I have tried about 3 times, the VPN still cannot open.
> > 
> > 
> > > 
> > 
> > 
> > > Have any other method can try?
> > 
> > 
> > Can you give me a list of packages you have installed? Can you check if it works if you reinstall the jailbreak environment and don't install anything?
> 
> I have tried reinstall the jailbreak environment and don't install anything, the VPN still not working.
> 
> These are installed packages:
> 
> 3DAppVersionSpoofer:(com.0xkuj.3dappversionspoofer) 2.0.4 ActionBar Reborn:(netskao.actionbarreborn) 1.1-2 AltList:(com.opa334.altlist) 1.0.10 AppData-Rootless:(netskao.appdata-rootless) 1.4.1 apt:(apt) 2.7.1 AutoFaceUnlock-Rootless:(netskao.autofaceunlock-rootless) 1.1-7 base:(base) 1-6 bash:(bash) 5.2.15 ca-certificates:(ca-certificates) 20230910 chariz-keyring:(chariz-keyring) 2021.07.18 coreutils:(coreutils) 9.4 darwintools:(darwintools) 1.6 dash:(dash) 0.5.12 debianutils:(debianutils) 5.7-1 diffutils:(diffutils) 3.9 diskdev-cmds:(diskdev-cmds) 697 Dopamine BaseBin Link:(dopamine-basebin-link) 1.0.0 dpkg:(dpkg) 1.22.0 ElleKit:(ellekit) 1.1.2 essential:(essential) 0-5 file-cmds:(file-cmds) 400-1 findutils:(findutils) 4.9.0 gpgv:(gpgv) 2.4.3 grep:(grep) 3.11 havoc-keyring:(havoc-keyring) 2022.06.03 launchctl:(launchctl) 1:1.1.1 libapt-pkg6.0:(libapt-pkg6.0) 2.7.1 libassuan0:(libassuan0) 2.5.6 libbrotli1:(libbrotli1) 1.1.0 libcrypt2:(libcrypt2) 4.4.36 libdimentio0:(libdimentio0) 1:0~20230202.7ffffff libedit0:(libedit0) 3.1-20230828 libffi8:(libffi8) 3.4.4 libgcrypt20:(libgcrypt20) 1.10.2 libgmp10:(libgmp10) 6.3.0 libgnutls30:(libgnutls30) 3.8.1 libgpg-error0:(libgpg-error0) 1.47 libhogweed6:(libhogweed6) 3.9.1 libidn2-0:(libidn2-0) 2.3.4 libintl8:(libintl8) 0.22 libiosexec1:(libiosexec1) 1.3.1 libkrw Plug-in (Dopamine):(libkrw0-dopamine) 2.0.1 libkrw0:(libkrw0) 1.1.1 liblz4-1:(liblz4-1) 1.9.4 liblzma5:(liblzma5) 5.4.4 libmd0:(libmd0) 1.1.0 libncursesw6:(libncursesw6) 6.4 libnettle8:(libnettle8) 3.9.1 libnpth0:(libnpth0) 1.6-2 libp11-kit0:(libp11-kit0) 0.25.0 libpam-modules:(libpam-modules) 1000.0 libpam2:(libpam2) 20230627 libpcre1:(libpcre1) 8.45-1 libpcre2-8-0:(libpcre2-8-0) 10.42 libreadline8:(libreadline8) 8.2.0-1 libroot (Dopamine):(libroot-dopamine) 1.0.1 libssl3:(libssl3) 3.0.10 libtasn1-6:(libtasn1-6) 4.19.0 libunistring5:(libunistring5) 1.1 libxxhash0:(libxxhash0) 0.8.2 libz-ng2:(libz-ng2) 2.1.3 libzstd1:(libzstd1) 1.5.5 mineland:(com.34306.mineland) 2.0-6+debug ncurses-bin:(ncurses-bin) 6.4 ncurses-term:(ncurses-term) 6.4 PerfectXTime-Rootless:(netskao.perfectxtime-rootless) 1.1-3 PreferenceLoader:(preferenceloader) 2.2.6-1 procursus-keyring:(procursus-keyring) 2020.05.09-4 profile.d:(profile.d) 0-7 sed:(sed) 4.9 shell-cmds:(shell-cmds) 278-2 shshd:(shshd) 1.1.1.1 Sileo:(org.coolstar.sileo) 2.5 snaputil:(snaputil) 12.3 sudo:(sudo) 1.9.14p3 System Info 系统信息-Rootless:(com.wxhbts.systeminfo.rootless) 2.7.2-3 system-cmds:(system-cmds) 950-2 tar:(tar) 1.35 uikittools:(uikittools) 2.1.6-1 vi:(vi) 070224 zsh:(zsh) 5.9 左滑返回-Rootless:(com.25mao.leftpan.rootless) 1.0-5

That's weird, I don't understand why it works for me then.

**Comment by baoan7090** [comment]
> > > > > Works fine for me on exactly the same device.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Thanks for your test.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I have tried about 3 times, the VPN still cannot open.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Have any other method can try?
> 
> > > 
> 
> > > 
> 
> > > Can you give me a list of packages you have installed? Can you check if it works if you reinstall the jailbreak environment and don't install anything?
> 
> > 
> 
> > I have tried reinstall the jailbreak environment and don't install anything, the VPN still not working.
> 
> > 
> 
> > These are installed packages:
> 
> > 
> 
> > 3DAppVersionSpoofer:(com.0xkuj.3dappversionspoofer) 2.0.4 ActionBar Reborn:(netskao.actionbarreborn) 1.1-2 AltList:(com.opa334.altlist) 1.0.10 AppData-Rootless:(netskao.appdata-rootless) 1.4.1 apt:(apt) 2.7.1 AutoFaceUnlock-Rootless:(netskao.autofaceunlock-rootless) 1.1-7 base:(base) 1-6 bash:(bash) 5.2.15 ca-certificates:(ca-certificates) 20230910 chariz-keyring:(chariz-keyring) 2021.07.18 coreutils:(coreutils) 9.4 darwintools:(darwintools) 1.6 dash:(dash) 0.5.12 debianutils:(debianutils) 5.7-1 diffutils:(diffutils) 3.9 diskdev-cmds:(diskdev-cmds) 697 Dopamine BaseBin Link:(dopamine-basebin-link) 1.0.0 dpkg:(dpkg) 1.22.0 ElleKit:(ellekit) 1.1.2 essential:(essential) 0-5 file-cmds:(file-cmds) 400-1 findutils:(findutils) 4.9.0 gpgv:(gpgv) 2.4.3 grep:(grep) 3.11 havoc-keyring:(havoc-keyring) 2022.06.03 launchctl:(launchctl) 1:1.1.1 libapt-pkg6.0:(libapt-pkg6.0) 2.7.1 libassuan0:(libassuan0) 2.5.6 libbrotli1:(libbrotli1) 1.1.0 libcrypt2:(libcrypt2) 4.4.36 libdimentio0:(libdimentio0) 1:0~20230202.7ffffff libedit0:(libedit0) 3.1-20230828 libffi8:(libffi8) 3.4.4 libgcrypt20:(libgcrypt20) 1.10.2 libgmp10:(libgmp10) 6.3.0 libgnutls30:(libgnutls30) 3.8.1 libgpg-error0:(libgpg-error0) 1.47 libhogweed6:(libhogweed6) 3.9.1 libidn2-0:(libidn2-0) 2.3.4 libintl8:(libintl8) 0.22 libiosexec1:(libiosexec1) 1.3.1 libkrw Plug-in (Dopamine):(libkrw0-dopamine) 2.0.1 libkrw0:(libkrw0) 1.1.1 liblz4-1:(liblz4-1) 1.9.4 liblzma5:(liblzma5) 5.4.4 libmd0:(libmd0) 1.1.0 libncursesw6:(libncursesw6) 6.4 libnettle8:(libnettle8) 3.9.1 libnpth0:(libnpth0) 1.6-2 libp11-kit0:(libp11-kit0) 0.25.0 libpam-modules:(libpam-modules) 1000.0 libpam2:(libpam2) 20230627 libpcre1:(libpcre1) 8.45-1 libpcre2-8-0:(libpcre2-8-0) 10.42 libreadline8:(libreadline8) 8.2.0-1 libroot (Dopamine):(libroot-dopamine) 1.0.1 libssl3:(libssl3) 3.0.10 libtasn1-6:(libtasn1-6) 4.19.0 libunistring5:(libunistring5) 1.1 libxxhash0:(libxxhash0) 0.8.2 libz-ng2:(libz-ng2) 2.1.3 libzstd1:(libzstd1) 1.5.5 mineland:(com.34306.mineland) 2.0-6+debug ncurses-bin:(ncurses-bin) 6.4 ncurses-term:(ncurses-term) 6.4 PerfectXTime-Rootless:(netskao.perfectxtime-rootless) 1.1-3 PreferenceLoader:(preferenceloader) 2.2.6-1 procursus-keyring:(procursus-keyring) 2020.05.09-4 profile.d:(profile.d) 0-7 sed:(sed) 4.9 shell-cmds:(shell-cmds) 278-2 shshd:(shshd) 1.1.1.1 Sileo:(org.coolstar.sileo) 2.5 snaputil:(snaputil) 12.3 sudo:(sudo) 1.9.14p3 System Info 系统信息-Rootless:(com.wxhbts.systeminfo.rootless) 2.7.2-3 system-cmds:(system-cmds) 950-2 tar:(tar) 1.35 uikittools:(uikittools) 2.1.6-1 vi:(vi) 070224 zsh:(zsh) 5.9 左滑返回-Rootless:(com.25mao.leftpan.rootless) 1.0-5
> 
> 
> 
> That's weird, I don't understand why it works for me then.

I tried reinstall 1 minute ago, with 2.0.8, still not working.

Should I give more information?

**Comment by baoan7090** [comment]
> > > > > Works fine for me on exactly the same device.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Thanks for your test.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I have tried about 3 times, the VPN still cannot open.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Have any other method can try?
> 
> > > 
> 
> > > 
> 
> > > Can you give me a list of packages you have installed? Can you check if it works if you reinstall the jailbreak environment and don't install anything?
> 
> > 
> 
> > I have tried reinstall the jailbreak environment and don't install anything, the VPN still not working.
> 
> > 
> 
> > These are installed packages:
> 
> > 
> 
> > 3DAppVersionSpoofer:(com.0xkuj.3dappversionspoofer) 2.0.4 ActionBar Reborn:(netskao.actionbarreborn) 1.1-2 AltList:(com.opa334.altlist) 1.0.10 AppData-Rootless:(netskao.appdata-rootless) 1.4.1 apt:(apt) 2.7.1 AutoFaceUnlock-Rootless:(netskao.autofaceunlock-rootless) 1.1-7 base:(base) 1-6 bash:(bash) 5.2.15 ca-certificates:(ca-certificates) 20230910 chariz-keyring:(chariz-keyring) 2021.07.18 coreutils:(coreutils) 9.4 darwintools:(darwintools) 1.6 dash:(dash) 0.5.12 debianutils:(debianutils) 5.7-1 diffutils:(diffutils) 3.9 diskdev-cmds:(diskdev-cmds) 697 Dopamine BaseBin Link:(dopamine-basebin-link) 1.0.0 dpkg:(dpkg) 1.22.0 ElleKit:(ellekit) 1.1.2 essential:(essential) 0-5 file-cmds:(file-cmds) 400-1 findutils:(findutils) 4.9.0 gpgv:(gpgv) 2.4.3 grep:(grep) 3.11 havoc-keyring:(havoc-keyring) 2022.06.03 launchctl:(launchctl) 1:1.1.1 libapt-pkg6.0:(libapt-pkg6.0) 2.7.1 libassuan0:(libassuan0) 2.5.6 libbrotli1:(libbrotli1) 1.1.0 libcrypt2:(libcrypt2) 4.4.36 libdimentio0:(libdimentio0) 1:0~20230202.7ffffff libedit0:(libedit0) 3.1-20230828 libffi8:(libffi8) 3.4.4 libgcrypt20:(libgcrypt20) 1.10.2 libgmp10:(libgmp10) 6.3.0 libgnutls30:(libgnutls30) 3.8.1 libgpg-error0:(libgpg-error0) 1.47 libhogweed6:(libhogweed6) 3.9.1 libidn2-0:(libidn2-0) 2.3.4 libintl8:(libintl8) 0.22 libiosexec1:(libiosexec1) 1.3.1 libkrw Plug-in (Dopamine):(libkrw0-dopamine) 2.0.1 libkrw0:(libkrw0) 1.1.1 liblz4-1:(liblz4-1) 1.9.4 liblzma5:(liblzma5) 5.4.4 libmd0:(libmd0) 1.1.0 libncursesw6:(libncursesw6) 6.4 libnettle8:(libnettle8) 3.9.1 libnpth0:(libnpth0) 1.6-2 libp11-kit0:(libp11-kit0) 0.25.0 libpam-modules:(libpam-modules) 1000.0 libpam2:(libpam2) 20230627 libpcre1:(libpcre1) 8.45-1 libpcre2-8-0:(libpcre2-8-0) 10.42 libreadline8:(libreadline8) 8.2.0-1 libroot (Dopamine):(libroot-dopamine) 1.0.1 libssl3:(libssl3) 3.0.10 libtasn1-6:(libtasn1-6) 4.19.0 libunistring5:(libunistring5) 1.1 libxxhash0:(libxxhash0) 0.8.2 libz-ng2:(libz-ng2) 2.1.3 libzstd1:(libzstd1) 1.5.5 mineland:(com.34306.mineland) 2.0-6+debug ncurses-bin:(ncurses-bin) 6.4 ncurses-term:(ncurses-term) 6.4 PerfectXTime-Rootless:(netskao.perfectxtime-rootless) 1.1-3 PreferenceLoader:(preferenceloader) 2.2.6-1 procursus-keyring:(procursus-keyring) 2020.05.09-4 profile.d:(profile.d) 0-7 sed:(sed) 4.9 shell-cmds:(shell-cmds) 278-2 shshd:(shshd) 1.1.1.1 Sileo:(org.coolstar.sileo) 2.5 snaputil:(snaputil) 12.3 sudo:(sudo) 1.9.14p3 System Info 系统信息-Rootless:(com.wxhbts.systeminfo.rootless) 2.7.2-3 system-cmds:(system-cmds) 950-2 tar:(tar) 1.35 uikittools:(uikittools) 2.1.6-1 vi:(vi) 070224 zsh:(zsh) 5.9 左滑返回-Rootless:(com.25mao.leftpan.rootless) 1.0-5
> 
> 
> 
> That's weird, I don't understand why it works for me then.

Hello, I just see that the VPN is on, then I try to reboot the userspace. It doesn't work again. Can you suggest my some method to check it?

**Comment by KikMyaz** [comment]
Can confirm VPN is broken again on 2.0.8 for arm64, although it used to work at this point after disabling injection to that binary. Manually blocking /usr/libexec/nesessionmanager via Choicy prefs also seems to work

https://github.com/opa334/Dopamine/actions/runs/8033545584

**Comment by opa334** [comment]
> Can confirm VPN is broken again on 2.0.8 for arm64, although it used to work at this point after disabling injection to that binary. Manually blocking /usr/libexec/nesessionmanager via Choicy prefs also seems to work
> 
> https://github.com/opa334/Dopamine/actions/runs/8033545584

That doesn't make much sense considering Choicy itself applies hooks to it too...

**Comment by KikMyaz** [comment]
> > Can confirm VPN is broken again on 2.0.8 for arm64, although it used to work at this point after disabling injection to that binary. Manually blocking /usr/libexec/nesessionmanager via Choicy prefs also seems to work
> > https://github.com/opa334/Dopamine/actions/runs/8033545584
> 
> That doesn't make much sense considering Choicy itself applies hooks to it too...

Could it be yet another one of those jetsam issues from the past? Although tbf I wasn't quite sure if it was rebooting userspace or adding nesessionmanager to additionalExecutables that fixed it - probs either one of those. 

Basically I had 2.0.8 running for a few days until VPN stopped working so I forcibly blocked nesessionmanager w/ Choicy by appending it to the plist and rebooted userspace. Now it's working again. Worth mentioning I also have one single tweak that hooks UIKit (probs bad practice) but I disabled it globally so shouldn't really matter.

**Comment by baoan7090** [comment]
> > > > > Works fine for me on exactly the same device.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Thanks for your test.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I have tried about 3 times, the VPN still cannot open.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Have any other method can try?
> 
> > > 
> 
> > > 
> 
> > > Can you give me a list of packages you have installed? Can you check if it works if you reinstall the jailbreak environment and don't install anything?
> 
> > 
> 
> > I have tried reinstall the jailbreak environment and don't install anything, the VPN still not working.
> 
> > 
> 
> > These are installed packages:
> 
> > 
> 
> > 3DAppVersionSpoofer:(com.0xkuj.3dappversionspoofer) 2.0.4 ActionBar Reborn:(netskao.actionbarreborn) 1.1-2 AltList:(com.opa334.altlist) 1.0.10 AppData-Rootless:(netskao.appdata-rootless) 1.4.1 apt:(apt) 2.7.1 AutoFaceUnlock-Rootless:(netskao.autofaceunlock-rootless) 1.1-7 base:(base) 1-6 bash:(bash) 5.2.15 ca-certificates:(ca-certificates) 20230910 chariz-keyring:(chariz-keyring) 2021.07.18 coreutils:(coreutils) 9.4 darwintools:(darwintools) 1.6 dash:(dash) 0.5.12 debianutils:(debianutils) 5.7-1 diffutils:(diffutils) 3.9 diskdev-cmds:(diskdev-cmds) 697 Dopamine BaseBin Link:(dopamine-basebin-link) 1.0.0 dpkg:(dpkg) 1.22.0 ElleKit:(ellekit) 1.1.2 essential:(essential) 0-5 file-cmds:(file-cmds) 400-1 findutils:(findutils) 4.9.0 gpgv:(gpgv) 2.4.3 grep:(grep) 3.11 havoc-keyring:(havoc-keyring) 2022.06.03 launchctl:(launchctl) 1:1.1.1 libapt-pkg6.0:(libapt-pkg6.0) 2.7.1 libassuan0:(libassuan0) 2.5.6 libbrotli1:(libbrotli1) 1.1.0 libcrypt2:(libcrypt2) 4.4.36 libdimentio0:(libdimentio0) 1:0~20230202.7ffffff libedit0:(libedit0) 3.1-20230828 libffi8:(libffi8) 3.4.4 libgcrypt20:(libgcrypt20) 1.10.2 libgmp10:(libgmp10) 6.3.0 libgnutls30:(libgnutls30) 3.8.1 libgpg-error0:(libgpg-error0) 1.47 libhogweed6:(libhogweed6) 3.9.1 libidn2-0:(libidn2-0) 2.3.4 libintl8:(libintl8) 0.22 libiosexec1:(libiosexec1) 1.3.1 libkrw Plug-in (Dopamine):(libkrw0-dopamine) 2.0.1 libkrw0:(libkrw0) 1.1.1 liblz4-1:(liblz4-1) 1.9.4 liblzma5:(liblzma5) 5.4.4 libmd0:(libmd0) 1.1.0 libncursesw6:(libncursesw6) 6.4 libnettle8:(libnettle8) 3.9.1 libnpth0:(libnpth0) 1.6-2 libp11-kit0:(libp11-kit0) 0.25.0 libpam-modules:(libpam-modules) 1000.0 libpam2:(libpam2) 20230627 libpcre1:(libpcre1) 8.45-1 libpcre2-8-0:(libpcre2-8-0) 10.42 libreadline8:(libreadline8) 8.2.0-1 libroot (Dopamine):(libroot-dopamine) 1.0.1 libssl3:(libssl3) 3.0.10 libtasn1-6:(libtasn1-6) 4.19.0 libunistring5:(libunistring5) 1.1 libxxhash0:(libxxhash0) 0.8.2 libz-ng2:(libz-ng2) 2.1.3 libzstd1:(libzstd1) 1.5.5 mineland:(com.34306.mineland) 2.0-6+debug ncurses-bin:(ncurses-bin) 6.4 ncurses-term:(ncurses-term) 6.4 PerfectXTime-Rootless:(netskao.perfectxtime-rootless) 1.1-3 PreferenceLoader:(preferenceloader) 2.2.6-1 procursus-keyring:(procursus-keyring) 2020.05.09-4 profile.d:(profile.d) 0-7 sed:(sed) 4.9 shell-cmds:(shell-cmds) 278-2 shshd:(shshd) 1.1.1.1 Sileo:(org.coolstar.sileo) 2.5 snaputil:(snaputil) 12.3 sudo:(sudo) 1.9.14p3 System Info 系统信息-Rootless:(com.wxhbts.systeminfo.rootless) 2.7.2-3 system-cmds:(system-cmds) 950-2 tar:(tar) 1.35 uikittools:(uikittools) 2.1.6-1 vi:(vi) 070224 zsh:(zsh) 5.9 左滑返回-Rootless:(com.25mao.leftpan.rootless) 1.0-5
> 
> 
> 
> That's weird, I don't understand why it works for me then.


~~Hello, I just see that the VPN is working again after I wake. I think that need a long time to work?~~ I use 2.0.6

**Comment by onmyodev** [comment]
I've had the same issue on 2.0.8 & 2.0.6, think I temporarily fixed my issue with 2.0.5. This is obviously a bad solution but only this worked for me.

(Sorry for the previous duplicate)

**Comment by opa334** [comment]
Please test again in 2.0.9.

**Comment by baoan7090** [comment]
> Please test again in 2.0.9.

I have re-jailbreak for twice, the VPN is now working. Thank you very much!

If there have any problem again, I will create a new issue. Thank you again.
