### ISSUE TITLE
Apple Watch Connectivity Issues on ARM64

### ISSUE THREAD

**Issue by InfernoWolf19** [opa334/Dopamine#458]
Anyone else facing Apple Watch connectivity issues? After updating to latest dopamine, 
Apple Watch keeps disconnecting and I have to reboot user space to get it to connect again. 

What I noticed is on my watch it keeps switching from Wi-Fi to just device connection quickly, resulting in the very quick battery drain. 

And when going into Bluetooth settings to connect to the already paired watch, it says connected but Apple Watch shows it’s not connected. 

iPhone 8+
Dopamine iOS 16.6 
Apple Watch Series 7 
Watch os 9.6.3

**Comment by opa334** [comment]
Should be fixed in latest nightly, please test

https://nightly.link/opa334/Dopamine/actions/runs/8165294582/Dopamine.zip

**Comment by InfernoWolf19** [comment]
> Should be fixed in latest nightly, please test
> 
> 
> 
> https://nightly.link/opa334/Dopamine/actions/runs/8165294582/Dopamine.zip

Will be trying this build right now. Thank you very much.

**Comment by InfernoWolf19** [comment]
So far no disconnection issues. iPhone notifications are not being mirrored to Apple Watch and Watch Faces not loading. If I reboot to stock iOS, both notifications and Watch faces are working but when jailbroken with the nightly build of Dopamine as well as any build of Dopamine, neither notifications nor Apple Watch faces work. Tried using legizmo, made no difference.

**Comment by bazikid** [comment]
would like to just second this as I am having the same problems listed above with notifications not being mirrored as well as watch faces not loading, which is all fixed by rebooting to stock iOS. Though I am having the issue on ARM64e

**Comment by opa334** [comment]
> would like to just second this as I am having the same problems listed above with notifications not being mirrored as well as watch faces not loading, which is all fixed by rebooting to stock iOS. Though I am having the issue on ARM64e

All known issues with this are fixed in 2.0.11.

**Comment by InfernoWolf19** [comment]
> > would like to just second this as I am having the same problems listed above with notifications not being mirrored as well as watch faces not loading, which is all fixed by rebooting to stock iOS. Though I am having the issue on ARM64e
> 
> 
> 
> All known issues with this are fixed in 2.0.11.

Unfortunately the Watch faces and notification issues are not fixed in 2.0.11.
