### ISSUE TITLE
Dopamine not reading tweaks/apps from another jailbreak

### ISSUE THREAD

**Issue by SonicandTailsCD** [opa334/Dopamine#459]
I just downloaded Dopamine ([1]) and jailbroke my iPhone.
As everyone may know, palera1n is the first jailbreak most people ([2]) use to jailbreak their device. I use it too, my favorite semi-tethered jailbreak of all ([6])!
I've installed like what, 120-200 tweaks? ([3])
Now, with `meowbrek2` ([4]) I didn’t have an issue other than slow speeds.
With Dopamine however, NONE of my tweaks or apps load. 
As well, Dopamine asked me to set up a `mobile` password? Asked me to install package managers again? But why? I already have a jailbreak and even ran the app with the jailbreak :( (besides I need the jailbreak. [5] explains this well.)

How do I solve this and make Dopamine load my currently installed tweaks and apps?
Apart from that annoying bug, keep going! Dopamine is so useful for us :)
(_Now I'd donate a lot but I'm poor + ugly + stupid, so…_)

_________________________________
*References ([_number goes here_])*:
1.- _used TrollStore of course_ ;) 
2.- people who even care to jailbreak as not many jailbreak their iPhone/iPad
3.- Yeah. I have 120 tweaks + 7 jailbroken apps. lol 😂 
4.- Yea, I also have `meowbrek2` even after it has been deprecated 😂 
5.- I require many jailbroken apps such as:
> Apps Manager
> Filza (glitched because TrollStore + palera1n have the same exact app IDs installed 😂)
> NewTerm 3 (I use SSH and code on the go with `nano`. I'm old and I know it :/)
> And much more…

6.- Yes, I'm a developer. How'd you know, mind reader? :P

**Comment by opa334** [comment]
Dopamine does not support bootstrap migration from meowbreak, only bootstrap migration from 1.x is supported. There is nothing you can do except reinstall the packages on Dopamine.

**Comment by SonicandTailsCD** [comment]
> Dopamine does not support bootstrap migration from meowbreak, only bootstrap migration from 1.x is supported. There is nothing you can do except reinstall the packages on Dopamine.

Thanks for letting me know palera1n/meowbrek2 packages can't be migrated to Dopamine. :)
Have a good day!
