### ISSUE TITLE
Stuck on Apple Logo after Jailbreak (Icon Cache problem)

### ISSUE THREAD

**Issue by lstone84** [opa334/Dopamine#464]
Stuck in bootloop after trying to jailbreak following resetting phone settings.

**Comment by C4rl0sG** [comment]
bootloop or respringloop ?

**Comment by lstone84** [comment]
It’s a bootloop. And I’ve since solved that problem. But the reason I encountered the bootloop issue was due to another issue, which remains. For some reason, the spotlight search function stopped working properly; apps wouldn’t show up. The search function in the settings app, as well as the search function in at least one other app, weren’t working properly either. I reset all settings and then the search function worked again. I completely deleted the jailbreak and reinstalled it. At some point the search function once again stopped working. I thought it may result from a certain tweak, but I went back and removed all the ones I had added since re jailbreaking, and the search function still didn’t work.

Luke

**Comment by C4rl0sG** [comment]
That sounds like the icon cache problem, fortunately it can be solved if I log into iCloud and remotely wipe the device. Although I don't know what causes it, I guess it must be things like themes and stuff.

**Comment by lstone84** [comment]
So I need to wipe it and set it up new?

**Comment by C4rl0sG** [comment]
bootloop: the phone turns on and restarts on the apple.  (usually unrecoverable)

So how do you say it had a bootloop? if you have access to the system

**Comment by lstone84** [comment]
Every time I tried to jailbreak it would get stuck on the Apple logo. Hard reset took it out.

**Comment by C4rl0sG** [comment]
that's not a bootloop -.-

that sounds more like a bad tweak

**Comment by lstone84** [comment]
ok, my bad. either way, that problem is fixed. any idea about the searching issue?

**Comment by opa334** [comment]
Let's track this in https://github.com/opa334/Dopamine/issues/533

**Comment by ewise209** [comment]
my ipad(9th generation) is stuck on the apple logo, it doesn't boot up or anything. I installed bootstrap and then serotonin and is stuck now, can i get some help please?
