### ISSUE TITLE
jit has some problem，can you fix it?

### ISSUE THREAD

**Issue by butenewbee** [opa334/Dopamine#471]
When i open ppsspp/retroarch(dc core)/ignited(nds core),jit can't really work:ppsspp can't choose “JIT MODE”;retroarch can't open dc games;ignited can't display "open wiht jit"...Can you fix it?Thanks(my idevices is iphonexr(ios15.6))

**Comment by opa334** [comment]
If I understand it correctly, this is something that the specific apps need to address. Although I will check if there is something I can improve on my end.

**Comment by butenewbee** [comment]
> 如果我理解正确的话，这是特定应用程序需要解决的问题。虽然我会检查一下我这边是否有可以改进的地方。
谢谢你的回复。but before your great tools published,there emu can be opened with jit mode in bootstrap.I’m really  hope you can fix it,thanks again.

**Comment by opa334** [comment]
Dopamine 2.1 has added the "Allow JIT in Apps" toggle which I assume should fix what you were complaining about.
