### ISSUE TITLE
Issue with Intercepting Application Traffic after jailbreak

### ISSUE THREAD

**Issue by staycyonline** [opa334/Dopamine#473]
Hi Dopamine team,

I have an iPhone 8 plus running on an A11 Chip and iOS Version 16.3.1. I am **able to setup a proxy** and intercept some traffic in burp suite when the phone **is not jailbroken.**

Unfortunately that is not the case after i perform the jailbreak using dopamine 2.0.9 (kfd,landa - it was the only one that worked). Any proxy set to my Wi-Fi is being ignored by my iPhone and I am unable to proxy traffic through my usual methods.

Requesting your help on the issue.

Really appreciate your hard work on this project. 💖

**Comment by opa334** [comment]
https://nightly.link/opa334/Dopamine/actions/runs/8165294582/Dopamine.zip

Should be fixed in latest nightly, please test.

**Comment by staycyonline** [comment]
Apologies for the delay in response.

I have checked for the issue in the latest release 2.0.11 and the issue seems to persist. Please have a look

**Comment by staycyonline** [comment]
Upon further research - it seems to be an iOS bug.
https://discussions.apple.com/thread/254569640?sortBy=best
