### ISSUE TITLE
Losing connection Apple Watch

### ISSUE THREAD

**Issue by richardpolder** [opa334/Dopamine#476]
When i had 2.0.6 i had no problems at all but when i updated to 2.0.8 and now 2.0.9 my Watch loses connection with my phone, my watch wants to reconect and so doing its battery drains like crazy. 
when i restart Userspace it works for a while but eventually it loses connection. 
i tried it without tweaks but its the same result. 
please help??

**Comment by Sparktion** [comment]
Legizmo 'Lighthouse' tweak might fix your issue. Take a look into it.

**Comment by richardpolder** [comment]
Like you said, it ‘might’ fix it, if not ive paid €4,99 for nothing😉
Thanks for thinking about it👊🏻

**Comment by Sparktion** [comment]
> Like you said, it ‘might’ fix it, if not ive paid €4,99 for nothing😉
> 
> Thanks for thinking about it👊🏻

Yeah. That's what I was concerned about 😂

**Comment by richardpolder** [comment]
🤣🤣🤣🤣
Im back on Dopamine 2.0.6 and that version works for me. Opa334 knows my problem but he told me its a lot of work to find something he can do about  it. I’ll wait for the next update, try that on and if its ‘fixed’ im happy and not, im going back to 2.0.6.

**Comment by opa334** [comment]
Should be actually fixed in latest nightly, please test!
https://nightly.link/opa334/Dopamine/actions/runs/8165294582/Dopamine.zip

**Comment by richardpolder** [comment]
I wanna test it out but i need a computer for that .zip file and have to wait for tonight. 
And i dont know how to install it on my iphone after that??
Im no computer wizard like you guys, if its hardware, no problem, software………….🤣

**Comment by richardpolder** [comment]
Never mind, i found it🤣🤣🤣🤣
Im gonna test it out today!👊🏻

**Comment by richardpolder** [comment]
Its still working, whoohooo🥳 but i wanna test it a little bit longer if possible??
I updated it this morning and i did everything with my watch what i normally do and checked it very regularly and it didnt lose the connection once👍🏻

**Comment by richardpolder** [comment]
I tested it intensive and its still working!!🥳
I tried everything and used my Watch like normal. I downloaded apps on it, tried a tweak on my phone for my watch and still the connectivity stayed!!! 
thanks @opa334 you fixed it for me👊🏻

**Comment by InfernoWolf19** [comment]
Are iPhone notifications being mirrored to your watch and are Watch faces loading in the Watch app for you?

**Comment by richardpolder** [comment]
My Watch works perfectly after the last update, no problems anymore.
