### ISSUE TITLE
Jailbroken Apps Disappeared after jailbreaking

### ISSUE THREAD

**Issue by Hanze-Li** [opa334/Dopamine#479]
iPhone13Pro
iOS15.0.2
Dopamine2.0.8

steps:
1.Reboot the jailbroken device
[Now the device is unjailbroken and the jailbroken apps like Sileo etc. disappear]
2.Jailbreak the device with Dopamine
[Now it is jailbroken again right?But the jailbroken apps don't automatically reappear, and after pressing the 'refresh jailbreak apps' button in settings of Dopamine and then restart springboard, they do reappear, but  without order (I mean I've put some apps in folders but they are out of the folders after the steps above)

**Comment by opa334** [comment]
Your problem might be that you're affected by the stock bug where newly added apps don't show up until a respring.

In that case al you need to do is respring yourself one time after jailbreaking.

**Comment by Hanze-Li** [comment]
No. In Dopamine 1.x it never occured to me. All the jailbroken apps automatically reappear again in the previous order.

And the disappearance of jailbroken apps seems to happen randomly, sometimes these apps disappear even if I didn't restart springboard. It just disappeared.And I have to restart springboard again by myself to let it reappear(but when these apps reappear, the order was totally changed randomly)
