### ISSUE TITLE
Camera app records static noise

### ISSUE THREAD

**Issue by Thyssenkrupp234** [opa334/Dopamine#482]
On my iPhone 8 + iOS 16.1, my camera app now records static/white noise while recording a video using the back camera. While using the front facing camera, it's fine, and recording a voice memo is normal. Only started having this issue recently with some more recent Dopamine updates.

Update: Front facing camera now has the same issue, voice memos is still fine. Hard reboot has already been done to no avail. Another update: FaceTime works as well, just camera app is screwed up

Update 2: After reviewing footage of my camera, it seems this issue started happening right after I installed Dopamine 2.0.0. I've tried jailbreaking with 2.0.6, and 2.0.9, and any video recorded has the noise. It even happens in stock iOS, which I don't know how is possible, but it's started on the same day I installed Dopamine 2.

**Comment by Thyssenkrupp234** [comment]
From what I've seen, the common issue on newer phones is "Record Stereo Sound", and turning it off fixes it. However, it's not an option on my phone. Is it possible that Dopamine has somehow force enabled this setting?

**Comment by opa334** [comment]
If it happens in stock OS it's not caused by Dopamine.
