### ISSUE TITLE
Full on reboot black screen and one line drawn at bottom right

### ISSUE THREAD

**Issue by eglacias** [opa334/Dopamine#483]
Just today after an entire 14 days of up time without a single respring or a single reboot on anything making this the most stable jailbreak yet,

I got the same reboot I got on day one.
The phone seem to lag trying to hit the dictate button to type a response to something. Well I was trying to get that work it finally did it. The screen turns black, a tiny little line is drawn near the bottom right, and then reboots.

Crash cop doesn’t show anything.
I know spontaneous reboots have been a feature of these jailbreaks, perhaps there’s nothing that can be done but if there’s anything I can try let me know.

OTA updated to 15.8 iPhone 6s Plus I latest dopamine, just before that was on the latest palerain rootless. And ages before this phone had been on iOS 12.4 using odyssey rain and chimera in before that uncover
[By the way this device would not even do a factory restore in iTunes to the latest signed version, there was no way to get it to do a full factory reset except through an OTA update!)

**Comment by opa334** [comment]
There should be a panic log inside System -> Privacy -> Analytics -> Analytics Data, send it here.

**Comment by eglacias** [comment]
There’s only one small one for today’s date. Attached

{"bug_type":"115","timestamp":"2024-03-02 13:03:34.00 -0800","name":"Reset count","os_version":"iPhone OS 15.8 (19H370)","incident_id":"4B4BFEB7-7319-4B35-A8E3-F4253A0FF1E0"}
Incident Identifier: 4B4BFEB7-7319-4B35-A8E3-F4253A0FF1E0
CrashReporter Key: cb5963af33260baea4b2eadb6ed1a0f85f614044
Date: 2024-03-02 13:03:34.46 -0800
Reset count: 0
Boot failure count: 1
Boot faults: wdog
Boot stage: 16
Boot app: 1474644888

Sent with Spark

**Comment by opa334** [comment]
that's not a panic.

**Comment by eglacias** [comment]
I just got this spontaneous reboot again.

This was in the middle of a line2 phone call.

The place that I am getting any crash report is under the settings app under Privacy/analyticsAnd improvements /analytics data

I’m not a programmer of iPhone jailbreak stuff I don’t know all the details of where everything is, is there somewhere else where something else is written because this is all that exists, and it has the exact timestamp of the catastrophic reboot.

There is no crash data in there for any application including the line2 phone application I was using

What is reset counter anyway…

Sent with Spark

**Comment by opa334** [comment]
There should be a "panic-full" file matching the time this occured on, please send that here.

**Comment by eglacias** [comment]
I can only access data through the settings app. I have no idea where those files are actually located nor were there any other logs in the app display area for that date when searching by date. Is this available somewhere other than what you can see under
settings privacy analytics &improvements analytics data?

I am now testing an iPhone 8+ on iOS 16.6.1 as that upgrade via futurerestore is available with blobs right now.

I got the first crash on this new test device today which looked like a crash of spark email. Three minute complete lock up incl physical buttons and then a complete shut down not even a reboot. Spark log and that reset counter thing attached.

Every other time but this time I get whatever the hell reset counter is, it’s the only thing in the logs and is at the exact time stamp the phone reboots.

Let me know if there’s some mysterious place or a way that I could locate any other panic logs. Sorry I’m not a programmer I’m just an “end loser” and I don’t know the programming details of the back end of the device!

Sent with Spark

**Comment by opa334** [comment]
> I can only access data through the settings app. I have no idea where those files are actually located nor were there any other logs in the app display area for that date when searching by date. Is this available somewhere other than what you can see under settings privacy analytics &improvements analytics data? I am now testing an iPhone 8+ on iOS 16.6.1 as that upgrade via futurerestore is available with blobs right now. I got the first crash on this new test device today which looked like a crash of spark email. Three minute complete lock up incl physical buttons and then a complete shut down not even a reboot. Spark log and that reset counter thing attached. Every other time but this time I get whatever the hell reset counter is, it’s the only thing in the logs and is at the exact time stamp the phone reboots. Let me know if there’s some mysterious place or a way that I could locate any other panic logs. Sorry I’m not a programmer I’m just an “end loser” and I don’t know the programming details of the back end of the device! Sent with Spark
> […](#)
> On Mar 7, 2024 at 3:12 AM -0800, Lars Fröder ***@***.***>, wrote: There should be a "panic-full" file matching the time this occured on, please send that here. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

if there is no panic log then it wasn't a panic.
