### ISSUE TITLE
Slow buildup of phonecalls

### ISSUE THREAD

**Issue by rasch3n** [opa334/Dopamine#485]
I noticed that a call takes up to 20-30 seconds until it rings for the first time.
I often thought that I had no network, but that wasn't the case.
In normal mode, the connection is established immediately.

**Comment by opa334** [comment]
What device? What version?

**Comment by rasch3n** [comment]
> What device? What version?

iPhone X
16.6

**Comment by opa334** [comment]
Test in latest nightly: https://nightly.link/opa334/Dopamine/actions/runs/8165294582/Dopamine.zip

**Comment by rasch3n** [comment]
> Test in latest nightly: https://nightly.link/opa334/Dopamine/actions/runs/8165294582/Dopamine.zip

So far it seems to be working.
All my calls went through immediately.
I'll keep watching it.
