### ISSUE TITLE
Its possible to call task_for_pid() in a tweak not an application with ent?

### ISSUE THREAD

**Issue by camenling** [opa334/Dopamine#488]
Sorry to disturb u guys. I hooked springboard and want to get the task of an application but task_for_pid return 5(kernel/os failed). I have no idea about this.I have spent many days about this. Pls help…(a tweak only contains dylib so cannot sign with task for pid allow)

**Comment by opa334** [comment]
No, libraries cannot have entitlements and will run with the entitlements of the process they inject into.
