### ISSUE TITLE
battery status

### ISSUE THREAD

**Issue by alwwwd** [opa334/Dopamine#489]
Hi! why I don't see battery status in settings?

device: iPhone 11
iOS: 16.0.0
Dopamine 2.0.9

safe mode don't fix it

**Comment by opa334** [comment]
Does it work if you jailbreak with tweak injection disabled in Dopamine settings?

**Comment by alwwwd** [comment]
> Does it work if you jailbreak with tweak injection disabled in Dopamine settings?

Hi! No

**Comment by opa334** [comment]
But it works when not jailbroken, right?

**Comment by alwwwd** [comment]
> But it works when not jailbroken, right?

In non-jailbroken state same problem

**Comment by opa334** [comment]
then not an issue with dopamine, you probably disabled some important daemon.
