### ISSUE TITLE
Jailbreak apps disappear when icon cache is reloaded

### ISSUE THREAD

**Issue by 6a6179** [opa334/Dopamine#496]
Title

Also, the only way to fix it is to reinstall the package manager through the dopamine app and all the apps will reappear

**Comment by opa334** [comment]
That's normal on rootless jailbreaks currently. Last time I tried fixing it I almost bootlooped...

**Comment by 6a6179** [comment]
i see. thanks for the answer

**Comment by opa334** [comment]
Fixed in 2.1.

**Comment by 6a6179** [comment]
> Fixed in 2.1.

Thanks opa
