### ISSUE TITLE
Help wanted: just bump version causes my app failed to show its icon

### ISSUE THREAD

**Issue by Lessica** [opa334/Dopamine#498]
Sorry to create an issue here but I really need your help. @opa334 

Here is my Issue: https://github.com/Lessica/TrollSpeed/issues/32

If I build and install my package with version A and its icon appeared normally, then I bumped its version to A+1 its icon will not show after installation. What's wrong with my package?

My packages are here, just bumped version without any modification to source code: [packages.zip](https://github.com/opa334/Dopamine/files/14527773/packages.zip)

If I rollback to version A and compile my app again, the icon appeared again.

I guess there's something wrong with `uicache-ng`? But if I create a new app project and test, the issue gone.

Environment: Dopamine 1.11.1/2.0.9 (both tested), iOS 15.4.1

TrollStore version does not have the issue above. That's interesting.

**Comment by Lessica** [comment]
I found there are some similar issues, and my cases are easy to reproduce. I've working on this problem for couples of days... Still no idea.

**Comment by Lessica** [comment]
The error during installation (Only the first time error occurred, printed out by uicache):
```
Error: Unable to register /private/preboot/4B206E78C962519095F04705E0D39B78D527FF58FB58DE1F33FAAF076C1B76725274F6B00F306BA26B196A4761BDB16C/jb-9zI59U/procursus/Applications/TrollSpeed.app
```

I did not see any difference except `Info.plist`. But on my device, only version 1.11.8 is able to show its icon.

**Comment by xxasfxx** [comment]
Same issue here I can find the apps that has disappeared in the Spotlight search but its not on the home screen.

it's been 2 days with very few sleep please help!!!

I am using Iphone 14 pro dopamine [2.0.10] and [2.0.9] installed through Trollstar.

**Comment by opa334** [comment]
The version number is not the issue, I have found just repacking it fixes the problem:

```
dpkg-deb -R ch.xxtou.hudapp_1.11.9_iphoneos-arm64.deb ./work2
dpkg-deb -b work2 new.deb
```

The resulting new.deb will work just fine (note that this does mess up permissions and all files will be owned by the username of your local machine).

Running `dpkg -c` on both packages reveals that the Info.plist lacks the read permissions for other users.

1.11.8:
`-rw-r--r-- root/wheel     1589 2024-03-07 18:21 var/jb/Applications/TrollSpeed.app/Info.plist`

1.11.9:
`-rw------- root/wheel     1589 2024-03-07 18:21 var/jb/Applications/TrollSpeed.app/Info.plist`

**Comment by Lessica** [comment]
Oh my! I don’t know why my theos project built the same package but with different file permissions… Thank you a thousand times! @opa334
