### ISSUE TITLE
Some apps crash indefinitely, even when rebooting and re-jailbreaking the situation. But when I turn off the injection tweaks in Dopamine, the app opens fine!

### ISSUE THREAD

**Issue by 0daysseus** [opa334/Dopamine#503]
Crash log:
{"roots_installed":0,"app_cohort":"2|date=1710041400000&sf=143441&tid=81afaac0d599d8cc3b09a8d9de40f172613012e3ae6d4c5255ffb2cc5b363e69&ttype=e","app_name":"Filebox","app_version":"1.3.10","timestamp":"2024-03-11 10:44:36.00 +0800","slice_uuid":"af599753-c425-3aa3-b510-13f83e7cb411","adam_id":"1558391784","build_version":"8","platform":2,"bundleID":"me.shuifeng.Filebox","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 16.5 (20F66)","incident_id":"043EBADF-E994-4D57-8711-4F4DCD471EC4","name":"Filebox","is_beta":1}
{
  "uptime" : 200,
  "procRole" : "unknown",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPad14,1",
  "coalitionID" : 1096,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 16.5",
    "releaseType" : "User",
    "build" : "20F66"
  },
  "captureTime" : "2024-03-11 10:44:36.2351 +0800",
  "incident" : "043EBADF-E994-4D57-8711-4F4DCD471EC4",
  "pid" : 752,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-03-11 10:44:36.0036 +0800",
  "procStartAbsTime" : 4803881838,
  "procExitAbsTime" : 4809430231,
  "procName" : "Filebox",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/52D61382-600E-4373-B4AF-D1746AC49694\/Filebox.app\/Filebox",
  "bundleInfo" : {"CFBundleShortVersionString":"1.3.10","CFBundleVersion":"8","CFBundleIdentifier":"me.shuifeng.Filebox","DTAppStoreToolsBuild":"15E204"},
  "storeInfo" : {"itemID":"1558391784","storeCohortMetadata":"2|date=1710041400000&sf=143441&tid=81afaac0d599d8cc3b09a8d9de40f172613012e3ae6d4c5255ffb2cc5b363e69&ttype=e","entitledBeta":true,"deviceIdentifierForVendor":"24B8F2A0-1BA5-4CE1-B0FD-6C1BEAAF0AED","softwareVersionExternalIdentifier":"133081396","applicationVariant":"1:iPad14,1:16","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "me.shuifeng.Filebox",
  "isBeta" : 1,
  "wasUnlockedSinceBoot" : 1,
  "isLocked" : 0,
  "codeSigningID" : "me.shuifeng.Filebox",
  "codeSigningTeamID" : "LX863G777H",
  "codeSigningFlags" : 570434305,
  "codeSigningValidationCategory" : 2,
  "codeSigningTrustLevel" : 0,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/ASN1Swift.framework\/ASN1Swift","Referenced from: <AF599753-C425-3AA3-B510-13F83E7CB411> \/Volumes\/VOLUME\/*\/Filebox.app\/Filebox","Reason: tried: '\/usr\/lib\/swift\/ASN1Swift.framework\/ASN1Swift' (no such file, not in dyld cache), '\/private\/preboot\/Cryptexes\/OS\/usr\/lib\/swift\/ASN1Swift.framework\/ASN1Swift' (no such file), '\/private\/var\/containers\/Bundle\/Application\/52D61382-600E-4373-B4AF-D1746AC49694\/Filebox.app\/Frameworks\/ASN1Swift.framework\/ASN1Swift' (code signature invalid in <88D0BBC7-8F59-3389-BF4E-35E755D085F8> '\/private\/var\/containers\/Bundle\/Application\/52D61382-600E-4373-B4AF-D1746AC49694\/Filebox.app\/Frameworks\/ASN1Swift.framework\/ASN1Swift' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00071540, codeBlobSize=0x00007840), '\/private\/var\/containers\/Bundle\/Application\/52D61382-600E-4373-B4AF-D1746AC49694\/Filebox.app\/Frameworks\/ASN1Swift.framework\/ASN1Swift' (code signature invalid in <88D0BBC7-8F59-3389-BF4E-35E755D"]},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":12712,"threadState":{"x":[{"value":6},{"value":1},{"value":6100102064},{"value":157},{"value":6100101040},{"value":0},{"value":0},{"value":0},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":55},{"value":4},{"value":32768},{"value":521},{"value":4388971704,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6100101040},{"value":157},{"value":6100102064},{"value":1},{"value":6},{"value":0},{"value":0},{"value":6100104560},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4389026584},"cpsr":{"value":4096},"fp":{"value":6100100992},"sp":{"value":6100100928},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4388982732,"matchesCrashFrame":1},"far":{"value":4385488896}},"frames":[{"imageOffset":446412,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":490264,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":490316,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":106500,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":0},{"imageOffset":99084,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4124,"imageIndex":0},{"imageOffset":89308,"symbol":"start","symbolLocation":1948,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4388536320,
    "size" : 557056,
    "uuid" : "444f5041-4d49-4e45-444f-50414d494e45",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4366778368,
    "size" : 14647296,
    "uuid" : "af599753-c425-3aa3-b510-13f83e7cb411",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/52D61382-600E-4373-B4AF-D1746AC49694\/Filebox.app\/Filebox",
    "name" : "Filebox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4385701888,
    "size" : 49152,
    "uuid" : "a624d80f-fb0a-3f46-b392-d8d1d42fb726",
    "path" : "\/usr\/lib\/systemhook.dylib",
    "name" : "systemhook.dylib"
  }
],
  "sharedCache" : {
  "base" : 6517489664,
  "size" : 2958344192,
  "uuid" : "4819de83-6dcc-338b-bf42-5024f1afd00b"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=16.4M resident=0K(0%) swapped_out_or_unallocated=16.4M(100%)\nWritable regions: Total=1712K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1712K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                         16K        1 \nStack                             1008K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                            1536K        4 \n__DATA_CONST                       640K        3 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                        1936K        3 \n__TEXT                            14.5M        5 \ndyld private memory                272K        1 \n===========                     =======  ======= \nTOTAL                             19.9M       20 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "ec4629d10e897f2ede6b4befb773a33b15d35db3",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6246d6a916a70b047e454124",
      "factorPackIds" : {
        "WALLET_APP_ECOM_PAYMENT_SHEET" : "64496ae8128ed17664c618d9"
      },
      "deploymentId" : 240000010
    },
    {
      "rolloutId" : "61675b89201f677a9a4cbd65",
      "factorPackIds" : {
        "HEALTH_FEATURE_AVAILABILITY" : "65a855f5f087695cfac03d1f"
      },
      "deploymentId" : 240000095
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by opa334** [comment]
Works just fine for me.

Additionally, if disabling tweak injection fixes it, that means it's a tweak issue.

**Comment by opa334** [comment]
This is a bug with some older versions of "SSL KillSwitch 3", it accidentally hooks `amfid` and breaks code signature verification inside it. This will then cause all apps that use the `amfid` path to get verified to start crashing.
