### ISSUE TITLE
v. 2.0.11 | Watch Faces aren't working in Watch App and Notifications Still are Not Mirrored

### ISSUE THREAD

**Issue by bazikid** [opa334/Dopamine#505]
Seems despite the new 2.0.11 update, the watch faces still do not appear in the watch app nor do the notifications work as mirrored with the iPhone. At some point, the faces appeared, but when adding a new face to the watch through the watch app, it did not add to the watch. Then, upon unpairing and repairing, was faced with the same issue. This is on both **_arm64e_** and **_arm64_** devices (based on infernowolf also continuing to have the issue).
![IMG_5902](https://github.com/opa334/Dopamine/assets/163013909/060dbfa5-30c2-4d08-b011-b32c14a6777e)

**Comment by InfernoWolf19** [comment]
Yeah a previous issue I opened with the same problems listed in a comment further down was closed 😅.

**Comment by opa334** [comment]
Provide a sysdiagnose while the issue is happening https://it-training.apple.com/tutorials/support/sup075, note that this might contain sensitive info, send it to me via email: opa334@protonmail.com

Secondly, please use SSH to run "launchctl list" and post the output here.

**Comment by bazikid** [comment]
> Provide a sysdiagnose while the issue is happening https://it-training.apple.com/tutorials/support/sup075, note that this might contain sensitive info, send it to me via email: [opa334@protonmail.com](mailto:opa334@protonmail.com)
> 
> Secondly, please use SSH to run "launchctl list" and post the output here.

Since I have never used SSH before, I installed the necessary packages and attempted to open it in terminal, though apparently the default password of 'alpine' is not the password set. Any way around this? 

Working on sending the sysdiagnose to you. But in terms of that, I'm not sure how to replicate the issue happening, as the apple watch connects fine, the notifications are just not mirrored and I can't edit the faces through the watch app, should I attempt to add a watch face then capture a sysdiagnose?



=========
Update: I managed to get in. I'll email all the information to the email you provided.

**Comment by InfernoWolf19** [comment]
Here is my LaunchCTL output text: 


[launchctl_output.txt](https://github.com/opa334/Dopamine/files/14564425/launchctl_output.txt)

**Comment by opa334** [comment]
I looked at the sysdiagnose and find anything interesting in it. Additionally, the launchctl logs indicate that the daemons are starting correctly, ruling out any issues with that.

**Comment by bazikid** [comment]
> I looked at the sysdiagnose and find anything interesting in it. Additionally, the launchctl logs indicate that the daemons are starting correctly, ruling out any issues with that.

Interesting, what's weird about all this is my watch was working in a previous build, but once I updated last week is when I ran in to this issue. I think the release that it was working on was pulled though. Not sure if I was on 2.0.9 or lower.

**Comment by InfernoWolf19** [comment]
> I looked at the sysdiagnose and find anything interesting in it. Additionally, the launchctl logs indicate that the daemons are starting correctly, ruling out any issues with that.

As well as my attached launchctl logs, I will be sending my sysdiagnosis file soon. Please take a look at it as while the diagnosis was running, I was actively trying to add a Watch face/view a Watch face and so on, so maybe you might spot something...

**Comment by InfernoWolf19** [comment]
> I looked at the sysdiagnose and find anything interesting in it. Additionally, the launchctl logs indicate that the daemons are starting correctly, ruling out any issues with that.

I have sent my sysdiagnose file now to corresponding email. Please take a look at it. Thanks.

**Comment by opa334** [comment]
> > I looked at the sysdiagnose and find anything interesting in it. Additionally, the launchctl logs indicate that the daemons are starting correctly, ruling out any issues with that.
> 
> I have sent my sysdiagnose file now to corresponding email. Please take a look at it. Thanks.

Nothing obvious in it either.

Does the issue happen when jailbreaking with tweak injection disabled?

**Comment by bazikid** [comment]
Seems disabling tweak injector restored the watch faces. With tweaks I managed to get the notifications to mirror though I'm not sure how. But disabling the tweak injector did restore the faces and allowed me to change them through the iPhone app. So for arm64e devices like mine it must be related to a tweak I have installed. I'll play around with them and uninstall/reinstall and see what might relieve the issue

**Comment by bazikid** [comment]
> > > I looked at the sysdiagnose and find anything interesting in it. Additionally, the launchctl logs indicate that the daemons are starting correctly, ruling out any issues with that.
> 
> > 
> 
> > I have sent my sysdiagnose file now to corresponding email. Please take a look at it. Thanks.
> 
> 
> 
> Nothing obvious in it either.
> 
> 
> 
> Does the issue happen when jailbreaking with tweak injection disabled?

I think it's related to the Flora tweak. I disabled that, didn't even uninstall it, and the watch faces restored and I can edit them in the watch app on my phone. I believe inferno also has flora activated so looks like that may be the issue.

In fact Flora was causing me a lot of issues I didn't even know were related to it until disabling it just now, like the Gmail app crashing when attempting to click on the three lines at the top left or account switch at the top right. Probably best I don't use it for now then.

**Comment by InfernoWolf19** [comment]
> > > > I looked at the sysdiagnose and find anything interesting in it. Additionally, the launchctl logs indicate that the daemons are starting correctly, ruling out any issues with that.
> > 
> > > 
> > 
> > > I have sent my sysdiagnose file now to corresponding email. Please take a look at it. Thanks.
> > 
> > 
> > 
> > Nothing obvious in it either.
> > 
> > 
> > 
> > Does the issue happen when jailbreaking with tweak injection disabled?
> 
> I think it's related to the Flora tweak. I disabled that, didn't even uninstall it, and the watch faces restored and I can edit them in the watch app on my phone. I believe inferno also has flora activated so looks like that may be the issue.
> 
> In fact Flora was causing me a lot of issues I didn't even know were related to it until disabling it just now, like the Gmail app crashing when attempting to click on the three lines at the top left or account switch at the top right. Probably best I don't use it for now then.

Yep can confirm it was due to Flora tweak. Odd that a colour customisation tweak broke Apple Watch notifs and Watch faces. But it is working now after disabling the tweak.
