### ISSUE TITLE
watchdog timeout intercept fail?

### ISSUE THREAD

**Issue by monsm** [opa334/Dopamine#507]
iphone7,15.8.2,Ver2.0.11

rebooted after two panic  (  https://www.mediafire.com/file/73iqg4jpm1ugavd/panic.zip/file  )

I found this（ https://github.com/opa334/Dopamine/commit/8331af478c9f803b30008970659d610350e86c61 ） in the history commits. Did the intercept fail?

1:
"panicString" : "panic(cpu 1 caller 0xfffffff00f4a7f00): watchdog timeout: no checkins from watchdogd in 94 seconds (19 total checkins since monitoring last enabled)\nDebugger message: panic\nMemory ID: 0xff\nOS release type: User\nOS version: 19H384\nKernel version: Darwin Kernel Version 21.6.0: Sun Oct 15 00:18:06 PDT 2023; root:xnu-8020.241.42~8\/RELEASE_ARM64_T8010\nKernelCache UUID: CD36CE0B0356F65AFE5A8841F99CA9D2\nKernel UUID: D986A786-4953-350E-97CF-C0FCFF85FFCF\niBoot version: iBoot-7459.140.15\nsecure boot?: YES\nPaniclog version: 13\nKernel slide:      0x000000000883c000\nKernel text base:  0xfffffff00f840000\nmach_absolute_time: 0x6d5fc0936b\nEpoch Time:        sec       usec\n  Boot    : 0x65ef87c7 0x000a3c35\n  Sleep   : 0x65efd7fc 0x0003a97f\n  Wake    : 0x65efd7fc 0x0008ca59\n  Calendar: 0x65efd919 0x0007fc86\n\nZone info:\n  Zone map: 0xffffffe0001c8000 - 0xffffffe6001c8000\n  . VM    : 0xffffffe0001c8000 - 0xffffffe0e682c000\n  . RO    : 0xffffffe0e682c000 - 0xffffffe1334f8000\n  . GEN0  : 0xffffffe1334f8000 - 0xffffffe219b5c000\n  . GEN1  : 0xffffffe219b5c000 - 0xffffffe3001c0000\n  . GEN2  : 0xffffffe3001c0000 - 0xffffffe3e6828000\n  . GEN3  : 0xffffffe3e6828000 - 0xffffffe4cce90000\n  . DATA  : 0xffffffe4cce90000 - 0xffffffe6001c8000\n  Metadata: 0xffffffee6d23c000 - 0xffffffee6ea3c000\n  Bitmaps : 0xffffffee6ea3c000 - 0xffffffee6f55c000\n\nCORE 0: PC=0xfffffff00fa2d844, LR=0xfffffff00fa2d844, FP=0xffffffee76283f00\nCORE 1 is the one that panicked. Check the full backtrace for details.\nCompressor Info: 86% of compressed pages limit (OK) and 30% of segments limit (OK) with 3 swapfiles and OK swap space\nTotal cpu_usage: 23101318\nThread task pri cpu_usage\n0xffffffe21a9ca328 launchd 63 5086913\n0xffffffe219c55518 kernel_task 0 2727045\n0xffffffe219c78e10 kernel_task 0 2153860\n\nPanicked task 0xffffffe2ff70cc90: 162 pages, 4 threads: pid 1: launchd\nPanicked thread: 0xffffffe21a9ca328, backtrace: 0xffffffee6d0e78a0, tid: 104364\n\t\t  lr: 0xfffffff00fa01ea0  fp: 0xffffffee6d0e78e0\n\t\t  lr: 0xfffffff00fa01c28  fp: 0xffffffee6d0e7950\n\t\t  lr: 0xfffffff00fb21324  fp: 0xffffffee6d0e79c0\n\t\t  lr: 0xfffffff00fb202c8  fp: 0xffffffee6d0e7a70\n\t\t  lr: 0xfffffff00f9c55fc  fp: 0xffffffee6d0e7a80\n\t\t  lr: 0xfffffff00fa01944  fp: 0xffffffee6d0e7e10\n\t\t  lr: 0xfffffff00fa01944  fp: 0xffffffee6d0e7e70\n\t\t  lr: 0xfffffff010043000  fp: 0xffffffee6d0e7e90\n\t\t  lr: 0xfffffff00f4a7f00  fp: 0xffffffee6d0e7ec0\n\t\t  lr: 0xfffffff00f4a75b0  fp: 0xffffffee6d0e7f00\n\t\t  lr: 0xfffffff00f4a5b34  fp: 0xffffffee6d0e7f20\n\t\t  lr: 0xfffffff00f0a28dc  fp: 0xffffffee6d0e7fb0\n\t\t  lr: 0xfffffff00ffbf96c  fp: 0xffffffee6d0e7fc0\n\t\t  lr: 0xfffffff00fb219b8  fp: 0xffffffee6d0e7fe0\n\t\t  lr: 0xfffffff00f9c5650  fp: 0xffffffee6d0e7ff0\n\t\t  lr: 0xfffffff00fb20298  fp: 0xffffffee760ebe60\n\t\t  lr: 0xfffffff00fb20298  fp: 0xffffffee760ebf10\n\t\t  lr: 0xfffffff00f9c55fc  fp: 0xffffffee760ebf20\n\n",

2:
"panicString" : "panic(cpu 1 caller 0xfffffff01a4f3f00): watchdog timeout: no checkins from watchdogd in 94 seconds (171 total checkins since monitoring last enabled)\nDebugger message: panic\nMemory ID: 0xff\nOS release type: User\nOS version: 19H384\nKernel version: Darwin Kernel Version 21.6.0: Sun Oct 15 00:18:06 PDT 2023; root:xnu-8020.241.42~8\/RELEASE_ARM64_T8010\nKernelCache UUID: CD36CE0B0356F65AFE5A8841F99CA9D2\nKernel UUID: D986A786-4953-350E-97CF-C0FCFF85FFCF\niBoot version: iBoot-7459.140.15\nsecure boot?: YES\nPaniclog version: 13\nKernel slide:      0x0000000013888000\nKernel text base:  0xfffffff01a88c000\nmach_absolute_time: 0x76f50eff31\nEpoch Time:        sec       usec\n  Boot    : 0x65efd929 0x0003cbc3\n  Sleep   : 0x65f028aa 0x000ee530\n  Wake    : 0x65f028b4 0x0002a29e\n  Calendar: 0x65f02fc1 0x00037535\n\nZone info:\n  Zone map: 0xffffffe19e2e8000 - 0xffffffe79e2e8000\n  . VM    : 0xffffffe19e2e8000 - 0xffffffe28494c000\n  . RO    : 0xffffffe28494c000 - 0xffffffe2d1618000\n  . GEN0  : 0xffffffe2d1618000 - 0xffffffe3b7c7c000\n  . GEN1  : 0xffffffe3b7c7c000 - 0xffffffe49e2e0000\n  . GEN2  : 0xffffffe49e2e0000 - 0xffffffe584948000\n  . GEN3  : 0xffffffe584948000 - 0xffffffe66afb0000\n  . DATA  : 0xffffffe66afb0000 - 0xffffffe79e2e8000\n  Metadata: 0xffffffe19bfd0000 - 0xffffffe19d7d0000\n  Bitmaps : 0xffffffe19d7d0000 - 0xffffffe19e2d8000\n\nCORE 0: PC=0xfffffff01aa79844, LR=0xfffffff01aa79844, FP=0xffffffe00d05bf00\nCORE 1 is the one that panicked. Check the full backtrace for details.\nCompressor Info: 78% of compressed pages limit (OK) and 26% of segments limit (OK) with 2 swapfiles and OK swap space\nTotal cpu_usage: 23841498\nThread task pri cpu_usage\n0xffffffe3b6960708 launchd 63 4844192\n0xffffffe3b792aa30 kernel_task 0 664096\n0xffffffe3b7bece10 kernel_task 0 910626\n\nPanicked task 0xffffffe49e285f68: 184 pages, 4 threads: pid 1: launchd\nPanicked thread: 0xffffffe3b6960708, backtrace: 0xffffffe195f278a0, tid: 124513\n\t\t  lr: 0xfffffff01aa4dea0  fp: 0xffffffe195f278e0\n\t\t  lr: 0xfffffff01aa4dc28  fp: 0xffffffe195f27950\n\t\t  lr: 0xfffffff01ab6d324  fp: 0xffffffe195f279c0\n\t\t  lr: 0xfffffff01ab6c2c8  fp: 0xffffffe195f27a70\n\t\t  lr: 0xfffffff01aa115fc  fp: 0xffffffe195f27a80\n\t\t  lr: 0xfffffff01aa4d944  fp: 0xffffffe195f27e10\n\t\t  lr: 0xfffffff01aa4d944  fp: 0xffffffe195f27e70\n\t\t  lr: 0xfffffff01b08f000  fp: 0xffffffe195f27e90\n\t\t  lr: 0xfffffff01a4f3f00  fp: 0xffffffe195f27ec0\n\t\t  lr: 0xfffffff01a4f35b0  fp: 0xffffffe195f27f00\n\t\t  lr: 0xfffffff01a4f1b34  fp: 0xffffffe195f27f20\n\t\t  lr: 0xfffffff01a0ee8dc  fp: 0xffffffe195f27fb0\n\t\t  lr: 0xfffffff01b00b96c  fp: 0xffffffe195f27fc0\n\t\t  lr: 0xfffffff01ab6d9b8  fp: 0xffffffe195f27fe0\n\t\t  lr: 0xfffffff01aa11650  fp: 0xffffffe195f27ff0\n\t\t  lr: 0xfffffff01ab6c298  fp: 0xffffffe00c8bbe60\n\t\t  lr: 0xfffffff01ab6c298  fp: 0xffffffe00c8bbf10\n\t\t  lr: 0xfffffff01aa115fc  fp: 0xffffffe00c8bbf20\n\n",

**Comment by monsm** [comment]
When I use dopamine for no more than 5 days, I will encounter watchdog timeout. When I use meowbreak, it has been running normally for 12 days. The installed tweak is the same source and the same version, and they are used after deleting each other's jailbreak.

**Comment by opa334** [comment]
No, this is a different timeout. Dopamine only intercepts watchdogd but if that itself times out there is nothing it can do.

**Comment by monsm** [comment]
Watchdog timeout and restart always occur in a short period of time. After opening multiple apps, the device quickly heats up and becomes unresponsive. I suspect it may be due to insufficient running memory or CPU processing issues

**Comment by monsm** [comment]
Viewing each process module with cocoatop after using dopamine shows a green dyld_shared_cache_arm64.1 and ared dyld_shared_cache_arm64.1, It can be judged that the red one is killed and the green one is started and killed again, and the cycle is repeated. Is this the reason that leads to the instability of the system? After using meowbrek2, I can only see a dyld_shared_cache_arm64.1 with white background on cocoatop. I don't see that the loop is started and killed again. I encountered two more watchdog timeout today
![8ECAFDF3-07F5-40F3-91A9-4734948B2BCC](https://github.com/opa334/Dopamine/assets/3960265/ecb4a5d2-6e1c-4a11-b82c-fa949772ca9f)

**Comment by opa334** [comment]
This has been fixed in 2.1.3.

**Comment by monsm** [comment]
> This has been fixed in 2.1.3.

Thanks. Run It for a few days and see if it shows up again
