### ISSUE TITLE
Simply installing the Ellekit plugin will put it into safe mode.

### ISSUE THREAD

**Issue by liushaoyu963** [opa334/Dopamine#509]
At the time of a FaceTime video call, I upgraded the ‘Phone Assistant’ plugin, and after restarting the springboard, it entered safe mode. After deleting all plugins, I found that simply installing Ellekit would trigger safe mode. Even after clearing the jailbreak in jailbreak mode and then re-jailbreaking, the problem persisted.
![4F6102AD-50FA-4D70-8075-38935AE91B76](https://github.com/opa334/Dopamine/assets/163225776/9777be8c-7e15-4761-8a9e-6cead0f48437)

**Comment by opa334** [comment]
Press "Exit Safe Mode", if you don't, the phone will stay in it.

**Comment by liushaoyu963** [comment]
> 按“退出安全模式”，如果不这样做，手机将保持在该模式。

I have tried to exit safe mode, but it doesn't work. Only by uninstalling Ellekit can it be restored, but without Ellekit, many plugins cannot be used. I think completely removing the jailbreak environment can solve this problem, but clearing the jailbreak within Dopamine does not clean it thoroughly. Is there any other way to completely clean it up? If not, would resetting the phone work?

**Comment by liushaoyu963** [comment]
Thanks for your reply.
I have tried to exit safe mode, but it doesn't work. Only by uninstalling Ellekit can it be restored, but without Ellekit, many plugins cannot be used. I think completely removing the jailbreak environment can solve this problem, but clearing the jailbreak within Dopamine does not clean it thoroughly. Is there any other way to completely clean it up? If not, would resetting the phone work?

**Comment by ssdsl0126** [comment]
> Thanks for your reply.
> 
> I have tried to exit safe mode, but it doesn't work. Only by uninstalling Ellekit can it be restored, but without Ellekit, many plugins cannot be used. I think completely removing the jailbreak environment can solve this problem, but clearing the jailbreak within Dopamine does not clean it thoroughly. Is there any other way to completely clean it up? If not, would resetting the phone work?

这个好像属于ellekit一个bug，我群里有人跟你一样，你在/var/mobile找下有没有一个文件是.eksafemode如果有删除，再退出安全模式即可

**Comment by liushaoyu963** [comment]
> 这个好像属于ellekit一个bug，我群里有人跟你一样，你在/var/mobile找下有没有一个文件是.eksafemode如果有删除，再退出安全模式即可

按照你回答的思路，删除了.eksafemode文件，要重启用户空间才能恢复，重启springboard并不行。只要重启springboard，亮屏后1分钟左右，就会进入安全模式。不过不管怎么样，现在是暂时恢复了越狱状态，谢谢你的解答，能否邀请我进群聊，可以一起交流一下。

Following your suggested approach, I deleted the .eksafemode file. However, a user-space restart is needed to restore it; restarting the SpringBoard doesn't work. Whenever the SpringBoard is restarted, about a minute after the screen lights up, it goes into safe mode. Nevertheless, the jailbreak status is temporarily restored now. Thank you for your guidance. Could you invite me to the group chat so we can discuss this further?

**Comment by ssdsl0126** [comment]
> > 这个好像属于ellekit一个bug，我群里有人跟你一样，你在/var/mobile找下有没有一个文件是.eksafemode如果有删除，再退出安全模式即可
> 
> 
> 
> 按照你回答的思路，删除了.eksafemode文件，要重启用户空间才能恢复，重启springboard并不行。只要重启springboard，亮屏后1分钟左右，就会进入安全模式。不过不管怎么样，现在是暂时恢复了越狱状态，谢谢你的解答，能否邀请我进群聊，可以一起交流一下。
> 
> 
> 
> Following your suggested approach, I deleted the .eksafemode file. However, a user-space restart is needed to restore it; restarting the SpringBoard doesn't work. Whenever the SpringBoard is restarted, about a minute after the screen lights up, it goes into safe mode. Nevertheless, the jailbreak status is temporarily restored now. Thank you for your guidance. Could you invite me to the group chat so we can discuss this further?
> 
> 

之前那个人他单独安装ellekit都会安全的所以我教他的可用，不太清楚你是不是一样的情况只能试试🤣

**Comment by liushaoyu963** [comment]
那情况跟我一样，只安装Ellekit就安全模式，你是怎么发现这个解决方法的？

**Comment by HolmesZhao** [comment]
> 那情况跟我一样，只安装Ellekit就安全模式，你是怎么发现这个解决方法的？

这个解决办法也不彻底啊😂重启springboard 还是会提示安全模式

**Comment by lindo-zy** [comment]
I also encountered this issue on my  iPad Pro 4th。我在ipad pro 4代上也遇到了同样的问题
