### ISSUE TITLE
Daemons disabled reset

### ISSUE THREAD

**Issue by Mikasa-san** [opa334/Dopamine#513]
Every time I re-jailbreak it resets the disabled.plist file which contains the daemons in this path /var/db/com.apple.xpc.launchd/

iPhone 14 Pro Max - 16.1.2

**Comment by opa334** [comment]
I do not see why this would happen, Dopamine does not touch that file.

Besides, you really shouldn't be touching it either, disabling daemons isn't possible to do without side effects.
