### ISSUE TITLE
executable can not run after dopamine jailbroken

### ISSUE THREAD

**Issue by WYK15** [opa334/Dopamine#514]
Please help me.
I have a Mach-O 64-bit executable arm64 file:SeeDaemon,it just NSLog pid.
I move it to /var/jb/usr/bin on iPhone(dopamine jailbroken) and run it, but it can not run,here is output:
![image](https://github.com/opa334/Dopamine/assets/22286162/0c80a0db-c272-4a5d-bbdb-65ee7b13ebb4)

But it can run succeed on iphone(checkrain jailbroken),located at /usr/bin
![image](https://github.com/opa334/Dopamine/assets/22286162/b3687b93-fb04-47ef-ab99-a96766a00337)

is this problem related to the way jailbroken, why is that and how can i fix this

BTW, here is my executable file:
[SeeDaemon.zip](https://github.com/opa334/Dopamine/files/14665625/SeeDaemon.zip)

**Comment by opa334** [comment]
This binary lacks the platform-application and unsandbox entitlements, sign it with those using Procursus ldid https://github.com/ProcursusTeam/ldid

**Comment by WYK15** [comment]
> This binary lacks the platform-application and unsandbox entitlements, sign it with those using Procursus ldid https://github.com/ProcursusTeam/ldid

Thanks for so quick reply, I tried, but still the same error.   :(
here is my entitlement:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>platform-application</key>
	<true/>
</dict>
</plist>
```

**Comment by opa334** [comment]
> > This binary lacks the platform-application and unsandbox entitlements, sign it with those using Procursus ldid https://github.com/ProcursusTeam/ldid
> 
> Thanks for so quick reply, I tried, but still the same error. :( here is my entitlement:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>com.apple.security.app-sandbox</key>
> 	<true/>
> 	<key>platform-application</key>
> 	<true/>
> </dict>
> </plist>
> ```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>platform-application</key>
	<true/>
	<key>com.apple.private.security.container-required</key>
	<false/>
</dict>
</plist>
```

**Comment by WYK15** [comment]
it works , thank you so much, you made my day！
