### ISSUE TITLE
Watchdog Timeout

### ISSUE THREAD

**Issue by cjay276** [opa334/Dopamine#515]
iPhone SE (2020) 16.5.1

Every time i jailbreak 5 minutes later my phone reboots and i get watchdog timeout, this happens even without downloading any tweak. Please help me fix this, i have tried everything to fix this and nothing is working.

**Comment by opa334** [comment]
Might be hardware failure? There is no such known issue...

**Comment by opa334** [comment]
What exactly does it say?

**Comment by cjay276** [comment]
> What exactly does it say?

![IMG_3245](https://github.com/opa334/Dopamine/assets/164746778/fc4f13d3-2703-402d-80b2-650b94825c1d)
![IMG_3246](https://github.com/opa334/Dopamine/assets/164746778/dc1012b3-cbcf-4406-aaeb-957faeea65ef)

**Comment by opa334** [comment]
Yep that's almost definitely hardware failure, does your microphone work?

**Comment by cjay276** [comment]
> Yep that's almost definitely hardware failure, does your microphone work?

mic works yes

**Comment by opa334** [comment]
Does it reboot after 5 minutes in stock mode aswell?

**Comment by cjay276** [comment]
> Does it reboot after 5 minutes in stock mode aswell?
Actually yes! My battery is so dead that it reboots randomly but, sometimes it's stable though.

**Comment by opa334** [comment]
Then it's a hardware issue.
