### ISSUE TITLE
Why my iPhone automatically restoring/restarting?

### ISSUE THREAD

**Issue by Bob4716** [opa334/Dopamine#519]
Idk if this is issue but my iPhone has rebooted twice since I got dopamine, all by itself. After rebooting everything runs fine and I still have Jail...

**Comment by Bob4716** [comment]
Four times now idk what happen.

**Comment by Bob4716** [comment]
Update: phone has restarted several times... always the phone lags, it can only be in an application that is open and then it restarts itself. And no panic log is created. I should add that this only happens to me with version 2.0.11 It hasn't happened to me with any other version, only this one. :/ even rejail doesn't work. Please dev fix this issue.

I have iPhone X iOS 16.1.

**Comment by opa334** [comment]
Maybe you got a bad battery? This certainly is not an issue with Dopamine.
