### ISSUE TITLE
Infinite boot loop 

### ISSUE THREAD

**Issue by OverWatch-R** [opa334/Dopamine#520]
Hi @opa334dev hope you’re enjoying your day 
I’m facing this issue when installing Crane…
The phone enters in infinite Bootloop then restart then watchdog timeout then Dpkg interrupted. When I uninstall it , everything is back to normal 
So I would like to know what’s going on

**Comment by opa334** [comment]
This will be fixed shortly (also it has nothing to do with Dopamine...)
