### ISSUE TITLE
Apps at AppStore cant update

### ISSUE THREAD

**Issue by hagomoro333** [opa334/Dopamine#526]
Hello i have issue Apps at AppStore cant update.. im done reboot my iPhone then try update apps at AppStore without jb.. result same cant update.. then i try jailbreak Dopamine 2 my iPhone 11 iOS 16.6b1
And i try update back and result still same cant update https://github.com/opa334/Dopamine/assets/48108428/4b7a5bea-4815-4bc5-a487-41e0d1f5e394

**Comment by opa334** [comment]
Unrelated to Dopamine.
