### ISSUE TITLE
A9X 16.1: XPF failure

### ISSUE THREAD

**Issue by kamilai-js** [opa334/Dopamine#527]
![Uploading 0DE71586-6361-47CC-91E3-5FF57C948B8B.png…]()

**Comment by kamilai-js** [comment]
查找地址
Jailbreak failed with error: Error Domain=JBErrorDomain Code=-2 "XPF failed with error: (Set "devmode" failed on "kernelSymbol.developer_mode_enabled")" UserInfo={NSLocalizedDescription=XPF failed with error: (Set "devmode" failed on "kernelSymbol.developer_mode_enabled")}

**Comment by opa334** [comment]
What iOS version / device?

**Comment by kamilai-js** [comment]
ios16.1      iPad pro 12.9 inch    A9X

**Comment by opa334** [comment]
This works for me, you sure it's not some sort of beta?

**Comment by opa334** [comment]
I have tested every single version between 16.1 beta 1 and 16.1 RC and can't reproduce this issue with any of them...
