### ISSUE TITLE
Latest version of dopamine breaks apple pay

### ISSUE THREAD

**Issue by Arzumify** [opa334/Dopamine#530]
I have installed the latest version of dopamine on my iPhone SE (second gen) on iOS 16.1.1. I'm not sure when this happened,  but since the previous dopamine update all Apple Pay cards have disappeared and add new simply results in an infinitely spinning wheel. The SEP is not modified, nor have I installed any tweaks involving NFC. The cards still show up in Cowabunga. I have changed my PIN in this time, but according to system preferences this shouldn't affect anything.

Here is my list of packages:

2048:(2048) 0.2019.6.29
Alderis Color Picker:(ws.hbang.alderis) 1.2.3
AltList:(com.opa334.altlist) 1.0.11
Amber:(com.ps.amber) 1.2.1
Ampere:(com.mtac.ampere) 1.4
AppData:(com.fouadraheb.appdata) 1.4.0
Apps Manager:(com.tigisoftware.appdatamanager) 1.8.2-5
apt:(apt) 2.7.1
Artemis:(com.icraze.artemis) 1.4
base:(base) 1-6
bash:(bash) 5.2.15
build-essential:(build-essential) 16.2
ca-certificates:(ca-certificates) 20230910
CCSupport:(com.opa334.ccsupport) 1.3.13-2
chariz-keyring:(chariz-keyring) 2021.07.18
clang:(clang) 14.0.0~5.7.2~RELEASE
clang-14:(clang-14) 14.0.0~5.7.2~RELEASE
coreutils:(coreutils) 9.4
curl:(curl) 8.2.1
darwintools:(darwintools) 1.6
dash:(dash) 0.5.12
Date Picker - Wheels:(com.tomaszpoliszuk.datepickerwheels) 1.0.1
debianutils:(debianutils) 5.7-1
diffutils:(diffutils) 3.9
diskdev-cmds:(diskdev-cmds) 697
Dopamine BaseBin Link:(dopamine-basebin-link) 1.0.0
dpkg:(dpkg) 1.22.0
ElleKit:(ellekit) 1.1.2
essential:(essential) 0-5
Felicity Pro:(com.xandesign.felicitypro) 4.1
file-cmds:(file-cmds) 400-1
Filza File Manager 64-bit:(com.tigisoftware.filza64bit) 4.0.1-4
findutils:(findutils) 4.9.0
FingerLock:(com.mtac.fingerlock) 3.0.2
FloatingDockXVI:(com.nahtedetihw.floatingdockxvi) 1.9
git:(git) 2.39.1
golang:(golang) 1.21.1
golang-1.21-go:(golang-1.21-go) 1.21.1
golang-1.21-src:(golang-1.21-src) 1.21.1
golang-go:(golang-go) 1.21.1
golang-src:(golang-src) 1.21.1
gpgv:(gpgv) 2.4.3
grep:(grep) 3.11
gzip:(gzip) 1.13
havoc-keyring:(havoc-keyring) 2022.06.03
iCleaner Pro:(com.exile90.icleanerpro) 7.10.0
inetutils:(inetutils) 2.0-1
iSponsorBlock:(com.galacticdev.isponsorblock) 1.2.4
launchctl:(launchctl) 1:1.1.1
ld64:(ld64) 609-3
ldid:(ldid) 2.1.5-procursus7
less:(less) 608
libapt-pkg6.0:(libapt-pkg6.0) 2.7.1
libassuan0:(libassuan0) 2.5.6
libbrotli1:(libbrotli1) 1.1.0
libc++-14-dev:(libc++-14-dev) 14.0.0~5.7.2~RELEASE
libc++-dev:(libc++-dev) 14.0.0~5.7.2~RELEASE
libc-ares2:(libc-ares2) 1.19.0
libclang-common-14-dev:(libclang-common-14-dev) 14.0.0~5.7.2~RELEASE
libclang-cpp14:(libclang-cpp14) 14.0.0~5.7.2~RELEASE
libcrypt2:(libcrypt2) 4.4.36
libcurl4:(libcurl4) 8.2.1
libdimentio0:(libdimentio0) 1:0~20230202.7ffffff
libedit0:(libedit0) 3.1-20230828
libffi8:(libffi8) 3.4.4
libgcrypt20:(libgcrypt20) 1.10.2
libgmp10:(libgmp10) 6.3.0
libgnutls30:(libgnutls30) 3.8.1
libgpg-error0:(libgpg-error0) 1.47
libhogweed6:(libhogweed6) 3.9.1
libidn2-0:(libidn2-0) 2.3.4
libintl8:(libintl8) 0.22
libiosexec-dev:(libiosexec-dev) 1.3.1
libiosexec1:(libiosexec1) 1.3.1
libkrw Plug-in (Dopamine):(libkrw0-dopamine) 2.0.1
libkrw0:(libkrw0) 1.1.1
libllvm14:(libllvm14) 14.0.0~5.7.2~RELEASE
liblz4-1:(liblz4-1) 1.9.4
liblzma5:(liblzma5) 5.4.4
libmagic1:(libmagic1) 5.43
libmd0:(libmd0) 1.1.0
libncursesw6:(libncursesw6) 6.4
libnettle8:(libnettle8) 3.9.1
libnghttp2-14:(libnghttp2-14) 1.52.0
libnpth0:(libnpth0) 1.6-2
libp11-kit0:(libp11-kit0) 0.25.0
libpam-modules:(libpam-modules) 1000.0
libpam2:(libpam2) 20230627
libpcre1:(libpcre1) 8.45-1
libpcre2-8-0:(libpcre2-8-0) 10.42
libplist3:(libplist3) 2.2.0+git20230130.4b50a5a
libreadline8:(libreadline8) 8.2.0-1
libroot (Dopamine):(libroot-dopamine) 1.0.1
librtmp1:(librtmp1) 2.4+20151223.gitfa8646d.1
libSandy:(com.opa334.libsandy) 1.1.4
libssh2-1:(libssh2-1) 1.10.0-1
libssl3:(libssl3) 3.0.10
libtapi:(libtapi) 1100.0.11-1
libtasn1-6:(libtasn1-6) 4.19.0
libunistring5:(libunistring5) 1.1
libuuid16:(libuuid16) 1.6.2-3
libxar1:(libxar1) 1.8.0.487.100.1-1
libxxhash0:(libxxhash0) 0.8.2
libz-ng2:(libz-ng2) 2.1.3
libzstd1:(libzstd1) 1.5.5
llvm-14:(llvm-14) 14.0.0~5.7.2~RELEASE
llvm-14-dev:(llvm-14-dev) 14.0.0~5.7.2~RELEASE
llvm-14-linker-tools:(llvm-14-linker-tools) 14.0.0~5.7.2~RELEASE
llvm-14-runtime:(llvm-14-runtime) 14.0.0~5.7.2~RELEASE
llvm-dev:(llvm-dev) 14.0.0~5.7.2~RELEASE
make:(make) 4.4.1
nano:(nano) 7.2
ncurses-bin:(ncurses-bin) 6.4
ncurses-term:(ncurses-term) 6.4
NewTerm 3 Beta:(ws.hbang.newterm3) 3.0~beta1
openssh:(openssh) 1:0
openssh-client:(openssh-client) 9.2p1
openssh-server:(openssh-server) 9.2p1
openssh-sftp-server:(openssh-sftp-server) 9.2p1
p7zip:(p7zip) 17.04
PreferenceLoader:(preferenceloader) 2.2.6-1
procursus-keyring:(procursus-keyring) 2020.05.09-4
profile.d:(profile.d) 0-7
RealCC:(com.jakeashacks.realcc) 0.0.4
Return YouTube Dislike:(weeb.lillie.youtubedislikesreturn) 1.11.10
Reverie:(lilliana.reverie) 0.0.3
sed:(sed) 4.9
shell-cmds:(shell-cmds) 278-2
shshd:(shshd) 1.1.1.1
Sileo:(org.coolstar.sileo) 2.5
snaputil:(snaputil) 12.3
SnowBoard:(com.spark.snowboard) 1.5.26-Beta4-rootless
sudo:(sudo) 1.9.14p3
SwipeExtenderX:(com.qiop1379.swipeextenderx) 1.6.1
system-cmds:(system-cmds) 950-2
tar:(tar) 1.35
uikittools:(uikittools) 2.1.6-1
unrar:(unrar) 6.2.6
unzip:(unzip) 6.0-28
uYou:(com.miro.uyou) 3.0.3
uYouCrashFix:(com.icraze.uyoucrashfix) 1.0
uYouImport:(com.miro.uyouimport) 1.0
Velvet 2:(com.noisyflake.velvet2) 2.1.2-3
vi:(vi) 070224
xz-utils:(xz-utils) 5.4.4
YouPiP:(com.ps.youpip) 1.8.7
YouQuality:(com.ps.youquality) 1.2.0
YouTube X:(com.ps.ytx) 1.6.2
YTABConfig:(com.ps.ytabconfig) 1.7.2
YTABGoodies:(com.ps.ytabgoodies) 1.0.4
YTClassicVideoQuality:(com.ps.ytclassicvideoquality) 1.3.2
YTVideoOverlay:(com.ps.ytvideooverlay) 1.2.0
zip:(zip) 3.0-12
zsh:(zsh) 5.9

**Comment by opa334** [comment]
Does it work when you're in jailed state?

**Comment by Arzumify** [comment]
No it does not

**Comment by opa334** [comment]
Then it can't be caused by Dopamine
