### ISSUE TITLE
bug feedback

### ISSUE THREAD

**Issue by HanYaoHao** [opa334/Dopamine#543]
Problem 1️⃣ the plug-in downloaded directly from the browser cannot be imported into sileo installation. It needs to be saved in the document and shared with sileo in the document before installation. Problem 2️⃣ SMS app fails to open and is stuck. Please check the developer and fix the problem Thank you!

**Comment by HanYaoHao** [comment]
The sharing problem has always existed, and the click to share has been blocked

**Comment by opa334** [comment]
Problem 1 was fixed in 2.1.1, Problem 2 is probably a tweak issue.
