### ISSUE TITLE
sileo and jailbreak app disappeared

### ISSUE THREAD

**Issue by limi586** [opa334/Dopamine#549]
sileo and jailbroken installed apps disappear from the app library,but I can search it with spotlight
dopamine 2.1.1

**Comment by opa334** [comment]
try respringing?

**Comment by limi586** [comment]
> try respringing?

I tried, but it didn't work, the problem appeared about two weeks ago when I was using dopamine2.0.11, yesterday I cleared the jailbreak and re-jailbroken with version 2.1.1 and still had this problem

**Comment by fivex0930105** [comment]
I have the same issue. After upgrading from dopamine 2.0.11 to 2.1.1, all jailbreak apps disappeared. Even after deleting the 2.1.1 jailbreak and reinstalling it, Sileo still doesn't appear. Additionally, I encountered problems with my TrollStore after upgrading to 2.1.1. Apps installed through TrollStore no longer appear on the home screen, regardless of whether the device is jailbroken or not.

**Comment by opa334** [comment]
doesn't sound like an issue with dopamine itself.
