### ISSUE TITLE
Feature request: set generator 

### ISSUE THREAD

**Issue by firedevel** [opa334/Dopamine#551]
Is there any way to set generator on iOS 15.7?
I tried 
https://github.com/Cryptiiiic/dimentio
https://github.com/opa334/TrollNonce
but no one works

I want to upgrade my iPhone XR to iOS 16 using my shsh blob

**Comment by firedevel** [comment]
shshd and dimentio output

Failed to initialize IOSurface primitives, add "IOSurfaceRootUserClient" to the "com.apple.security.exception.iokit-user-client-class" dictionary of the binaries entitlements to fix this.
KRW plugin /var/jb/usr/lib/libkrw/libkrw-plugin.dylib did not provide functions it purported to provide

**Comment by opa334** [comment]
That error only refers to kcall, kernel read/write should still work. The actual issue is probably that dimentio is not updated for iOS 15.7.

I checked and it works fine for me on A15, 15.1.1 and A12, 15.4.1, despite printing these errors.

**Comment by ovoME** [comment]
i had the same problem
