### ISSUE TITLE
The deb tweak for WeChat and QQ cannot be opened through Sileo, since update 2.1

### ISSUE THREAD

**Issue by Tsangbaby** [opa334/Dopamine#554]
Must be saved to a file before opening through Sileohttps://github.com/opa334/Dopamine/assets/134396913/f6832150-a989-4127-b648-3aaaee29126a

**Comment by opa334** [comment]
This has already been fixed in 2.1.1.

**Comment by lclrc** [comment]
This may happen if you upgraded from an old version, because the new version redirects `/var/mobile` to the `/var/jb/var/mobile` path, but the previous files are still under `/var/mobile`.
```
LaunchServices: [Perform] not launching application - result = Error Domain=NSCocoaErrorDomain Code=513 "您没有将文件“Inbox”存储到文件夹“Documents”中的权限。" UserInfo={NSFilePath=/private/preboot/42F05073A3413E12D9C60EC88F179BD34D470CD453E4EF3DD11FD6CC25250042C5FE9918109A7268131E9E786FF28E32/dopamine-Kdg36v/procursus/var/mobile/Library/Application Support/Containers/org.coolstar.SileoStore/Documents/Inbox, NSUnderlyingError={
    Code = 13;
    Domain = NSPOSIXErrorDomain;
    UserInfo =     {
    };
}}
```

Solution:
    Move or copy `/var/mobile/Library/Application Support/Containers` to `/var/jb/var/mobile/Library/Application Support`, if you already have a `Containers` directory before, just move its subdirectories.

**Comment by opa334** [comment]
> This may happen if you upgraded from an old version, because the new version redirects `/var/mobile` to the `/var/jb/var/mobile` path, but the previous files are still under `/var/mobile`.
> 
> ```
> LaunchServices: [Perform] not launching application - result = Error Domain=NSCocoaErrorDomain Code=513 "您没有将文件“Inbox”存储到文件夹“Documents”中的权限。" UserInfo={NSFilePath=/private/preboot/42F05073A3413E12D9C60EC88F179BD34D470CD453E4EF3DD11FD6CC25250042C5FE9918109A7268131E9E786FF28E32/dopamine-Kdg36v/procursus/var/mobile/Library/Application Support/Containers/org.coolstar.SileoStore/Documents/Inbox, NSUnderlyingError={
>     Code = 13;
>     Domain = NSPOSIXErrorDomain;
>     UserInfo =     {
>     };
> }}
> ```
> 
> Solution: Move or copy `/var/mobile/Library/Application Support/Containers` to `/var/jb/var/mobile/Library/Application Support`, if you already have a `Containers` directory before, just move its subdirectories.

I'm confused, why can't it create the new directory on it's own? Can you show me the permissions of `/var/jb/var/mobile/Library/Application Support/Containers/org.coolstar.SileoStore/Documents/`? (press the i in filza and send a screenshot)

**Comment by lclrc** [comment]
> > This may happen if you upgraded from an old version, because the new version redirects `/var/mobile` to the `/var/jb/var/mobile` path, but the previous files are still under `/var/mobile`.
> > ```
> > LaunchServices: [Perform] not launching application - result = Error Domain=NSCocoaErrorDomain Code=513 "您没有将文件“Inbox”存储到文件夹“Documents”中的权限。" UserInfo={NSFilePath=/private/preboot/42F05073A3413E12D9C60EC88F179BD34D470CD453E4EF3DD11FD6CC25250042C5FE9918109A7268131E9E786FF28E32/dopamine-Kdg36v/procursus/var/mobile/Library/Application Support/Containers/org.coolstar.SileoStore/Documents/Inbox, NSUnderlyingError={
> >     Code = 13;
> >     Domain = NSPOSIXErrorDomain;
> >     UserInfo =     {
> >     };
> > }}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Solution: Move or copy `/var/mobile/Library/Application Support/Containers` to `/var/jb/var/mobile/Library/Application Support`, if you already have a `Containers` directory before, just move its subdirectories.
> 
> I'm confused, why can't it create the new directory on it's own? Can you show me the permissions of `/var/jb/var/mobile/Library/Application Support/Containers/org.coolstar.SileoStore/Documents/`? (press the i in filza and send a screenshot)

`/var/jb/var/mobile/Library/Application Support/Containers/org.coolstar.SileoStore/Documents/`
![image](https://github.com/opa334/Dopamine/assets/23278764/ea7b224b-e1f8-42d1-99eb-43cff27e6184)

You might also want to look at the permissions of the `/var/jb/var/mobile/Library/Application Support` path, since before the path under /`var/jb` was only created up to `/var/jb/var/mobile/Library/Application Support`, with no subdirectories from `Containers` onwards

<img width="414" alt="image" src="https://github.com/opa334/Dopamine/assets/23278764/fdb68caf-0ff8-4e37-9f52-72e68202ca07">

There was only the `Weed` directory here before, which was created by tweak 'SwipeExpender'.
<img width="414" alt="image" src="https://github.com/opa334/Dopamine/assets/23278764/45cc377b-41f7-43ff-a79e-ec8a806db33d">

**Comment by opa334** [comment]
Yeah this is the issue, SwipeExtender fucks up permissions it seems, the next update of Dopamine will fix all the permissions up every userspace reboot so this doesn't happen anymore.
