### ISSUE TITLE
iPhone 8 iOS 16.6 Jailbreak was deleted after reboot

### ISSUE THREAD

**Issue by BananeRapeuse** [opa334/Dopamine#559]
First, I have download and install dopamine with Scarlet, after, I have jailbreak the device correctly, sileo was on my home screen and i have install packages and after, when my phone shut down because of the battery was at 0%, I have recharge it and when I have reboot my phone all jailbreak apps has been deleted (just the Dopamine app and Scarlet was not deleted), when I want to un-jailbreak and re-jailbreak the device, it just reboot but sileo don’t install. Finally, I have uninstall and reinstall dopamine and re-jailbreak the device and sileo was installed but when i reboot only TrollStore was installed because I have install it from the TrollHelper I have install from sileo, unfortunately TrollHelper and other apps I have installed with sileo and the sileo app have been deleted, only the Persistent helper i have install on Tips app is working… please help me.

**Comment by opa334** [comment]
Dopamine is only semi untethered and needs to be reactivated after rebooting.

**Comment by BananeRapeuse** [comment]
Ok thanks you !
