### ISSUE TITLE
2.1.2 BUG

### ISSUE THREAD

**Issue by wen-6** [opa334/Dopamine#560]
之前的所有版本都稳定，可更新2.1.2后出现异常。
重启，死机，硬盘剩余空间全部占满。
All previous versions were stable, but exceptions occurred after updating 2.1.2
Restart, crash, and the remaining hard disk space is fully occupied.

iPhone12 Pro Max（iOS15.7.1）

**Comment by opa334** [comment]
occupied with what?

**Comment by wen-6** [comment]
看视频
Watch videos
![94DFD4CB-5C02-4ED6-9A62-EE8CBDEFCF16](https://github.com/opa334/Dopamine/assets/32879338/2e5df8ca-0f26-48e7-a989-f14d9eea7a05)

**Comment by wen-6** [comment]
更新后增加了这个开关，我不清楚这个开关的用途。前两次重启时，这个开关是开启的状态，我今天关闭了这个开关。尝试看看是否这里的问题，目前没重启。
After the update, this switch has been added, and I am not sure about its purpose. The switch was turned on during the first two restarts, but I turned it off today. Try to see if there is an issue here, it has not been restarted yet.
![038A22F5-1549-4A9F-A2EF-87584ADCD35E](https://github.com/opa334/Dopamine/assets/32879338/39d9f288-be7d-43f6-b382-63cf33be4976)

**Comment by wen-6** [comment]
今天看抖音，手机又重启了。
