### ISSUE TITLE
Broken on IOS 16 Beta

### ISSUE THREAD

**Issue by Lunariansia** [opa334/Dopamine#561]
It fails to pathfind on IOS 16 beta with an error about symbols, though I can't remember the exact error whilst typing this. I hope a bug fix for it can be found.

**Comment by opa334** [comment]
Please include your device and exact version.

**Comment by Lunariansia** [comment]
Device: Ipad Gen 7
Version: 16.0 Beta (20A5283p)

**Comment by aydenbottos** [comment]
Same issue as #329 unfortunately

**Comment by opa334** [comment]
Yes, duplicate of #329
