### ISSUE TITLE
Add support for dimentio

### ISSUE THREAD

**Issue by LuckyHeroes** [opa334/Dopamine#564]
When using dimentio, an error occours.

Failed to init IOSurface primitives, add "IOSurfaceRootUserClient" to the "com.apple.security.exception.iokit.user-client-class" dictionary of the binaries entitlements to fix this.

KRW plugin /var/jb/usr/lib/libkrw/libkrw-plugin.dylib did not provide functions it purported to have.

**Comment by opa334** [comment]
Duplicate of https://github.com/opa334/Dopamine/issues/551

**Comment by LuckyHeroes** [comment]
Incorrect opa, "That error only refers to kcall, kernel read/write should still work. The actual issue is probably that dimentio is not updated for iOS 15.7."

Palera1n works fine with dimentio, i looked through dimentio code and below looks like the support needs to be added for libkrw0-dopamine.

Its nice to have all in one jailbreak that supports all use cases as people still use futurerestore.



"""if(_kread_buf != NULL && _kwrite_buf != NULL) {
			kread_buf = _kread_buf;
			kwrite_buf = _kwrite_buf;
		} else if(init_tfp0() == KERN_SUCCESS) {
			printf("tfp0: 0x%" PRIX32 "\n", tfp0);
			kread_buf = kread_buf_tfp0;
			kwrite_buf = kwrite_buf_tfp0;
		} else if((kernrw_0 = dlopen("/usr/lib/libkernrw.0.dylib", RTLD_LAZY)) != NULL && (kernrw_0_req = (kernrw_0_req_kernrw_func_t)dlsym(kernrw_0, "requestKernRw")) != NULL && kernrw_0_req() == 0) {
			kread_buf = (kread_func_t)dlsym(kernrw_0, "kernRW_readbuf");
			kwrite_buf = (kwrite_func_t)dlsym(kernrw_0, "kernRW_writebuf");
		} else if((krw_0 = dlopen("/usr/lib/libkrw.0.dylib", RTLD_LAZY)) != NULL && (krw_0_kread = (krw_0_kread_func_t)dlsym(krw_0, "kread")) != NULL && (krw_0_kwrite = (krw_0_kwrite_func_t)dlsym(krw_0, "kwrite")) != NULL) {
			kread_buf = kread_buf_krw_0;
			kwrite_buf = kwrite_buf_krw_0;
		} else if((kmem_fd = open("/dev/kmem", O_RDWR | O_CLOEXEC)) != -1) {
			kread_buf = kread_buf_kmem;
			kwrite_buf = kwrite_buf_kmem;
		}"""

**Comment by opa334** [comment]
dimentio works fine for me on 15.1.1 and 15.4.1
