### ISSUE TITLE
iphone 11 16.1 Jailbreak failure when not connected 

### ISSUE THREAD

**Issue by icymanred** [opa334/Dopamine#565]
I was trying to jailbreak while offline and it failed multiple times. However as soon as i got online it worked l. Is this intentional?

**Comment by icymanred** [comment]
I can’t reproduce with airplane mode only with no wifi to connect to.

**Comment by opa334** [comment]
placebo

**Comment by icymanred** [comment]
Pretty sure its not but okay

**Comment by opa334** [comment]
Even if it's not, there would be no way I could do anything about it.
