### ISSUE TITLE
2.1.4 Banks detect

### ISSUE THREAD

**Issue by hungtoong** [opa334/Dopamine#567]
The new version was detected by the bank, I think the problem is about the url scheme.
![IMG_1996](https://github.com/opa334/Dopamine/assets/47075010/668e2e70-d1fc-4333-83f6-99f37e7d797e)

**Comment by qweraqq** [comment]
try vnodebypass

**Comment by authorisation** [comment]
This is not an issue with the jailbreak, it doesn't belong here

**Comment by opa334** [comment]
that is a good point indeed

**Comment by roothider** [comment]
> The new version was detected by the bank, I think the problem is about the url scheme. ![IMG_1996](https://private-user-images.githubusercontent.com/47075010/329504355-668e2e70-d1fc-4333-83f6-99f37e7d797e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjUxMTEsIm5iZiI6MTczMTY2NDgxMSwicGF0aCI6Ii80NzA3NTAxMC8zMjk1MDQzNTUtNjY4ZTJlNzAtZDFmYy00MzMzLTgzZjYtOTlmMzdlN2Q3OTdlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQxMDAwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2ZjMzM2YmU5NDY2M2M5YTI5MTZjYTM1YzVmYzhmYzE4Mzk3YzM3YWE3ZDE4YjcyMWZlOTYwNTFiMmE5MWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.M_ojBE8yKkK6P-h44Mftvv43WwiGJWyWjVSwv30eHA0)

try roothide
