### ISSUE TITLE
Failed to jailbreak iOS 16.1 iPhone 13 Pro Max

### ISSUE THREAD

**Issue by jhorvitz124** [opa334/Dopamine#569]
![image](https://github.com/opa334/Dopamine/assets/113337655/facc5ef9-422e-42ad-8668-26e18064c9e6)

**Comment by opa334** [comment]
looks like my feature for detecting duplicate applications works as intended?...

**Comment by jhorvitz124** [comment]
I'm wondering how to fix this.
