### ISSUE TITLE
Cannot execute non-default slices

### ISSUE THREAD

**Issue by asdfugil** [opa334/Dopamine#573]
The `posix_spawnattr_setarchpref_np(3)` API allows a non-default slice in a fat Mach-O to be executed. However, Dopamine's systemhook and jbserver does not take this into account, which results in non-default slices not being added to trustcache, which results in them not being executable.

To reproduce:
main.c
```c
int main(void) {}
```
```
xcrun -sdk iphoneos clang -arch arm64 -arch arm64e -miphoneos-version-min=15.0 main.c -o main
ldid -S main
```
Try to execute the binary normally on arm64e:
```
$ ./main
$
```
works fine
Try to execute the arm64 slice:
```
$ arch -arm64 ./main
Killed
$
```
the slice does not execute.

**Comment by opa334** [comment]
Fixed in 2.1.5
