### ISSUE TITLE
Safe Mode After Applying Misaka Tweaks

### ISSUE THREAD

**Issue by luhgarlicbread** [opa334/Dopamine#584]
Hello! Whenever I am jailbroken with Dopamine & I inject tweaks via Misaka, I get sent into safe mode. I can easily exit safe mode and Misaka’s tweaks will remain and everything will work smoothly.

What I’m requesting is: Dopamine can be patched to prevent entering safe mode after injecting Misaka tweaks unless Misaka’s tweaks are actually causing issues/panics.

I am rocking an iPhone 11 (A13 arm64e) on iOS 16.3.1 with the latest version of Dopamine.
Thank you and God bless.
~ Ethan

**Comment by opa334** [comment]
wtf are Misaka tweaks and why do you use that to inject them?!

my guess is it probably "restarts" SpringBoard by crashing it, hence triggering the safe mode and if that's the case then no that's not fixable.

**Comment by authorisation** [comment]
> wtf are Misaka tweaks

Misaka is this thing that utilizes kfd and MDC to do some minor tweaks. Mainly it just replaces or rewrites certain files in the iOS filesystem. Shouldn't really be used anymore as Dopamine  mostly supports every version it supports.
