### ISSUE TITLE
App Crashes: EXC_BAD_ACCESS (SIGSEGV) | KERN_INVALID_ADDRESS: 0x3e

### ISSUE THREAD

**Issue by Lazy-Write** [opa334/Dopamine#587]
I’m experiencing app crashes from a number of different apps when both in jailbroken and non-jailbroken states on an iPhone 13 Pro, 15.4.1.

I have tried disabling tweak injection, and rebooting into non-jailbroken and the issue still seems to persist.

When opening some apps, after varying amounts of time between instantly and around 30 seconds, the app will just crash and close itself.

Cr4shed and KrashKop error reports always state the culprit as unknown, with the following error:

`Exception type: EXC_BAD_ACCESS (SIGSEGV)
Exception subtype: KERN_INVALID_ADDRESS: 0x3e
Exception codes: 0x0000000000000001, 0x000000000000003e
Culprit: Unknown
VM Protection: 0x3e is not in any region.`

I have attached a full crash report, in this particular case it relates to ‘8-Ball Pool’, but the error is the same for other apps too.

Any idea what could be happening here? If you need any other details/logs please let me know.
[Crash Report.txt](https://github.com/user-attachments/files/15544606/Crash.Report.txt)

**Comment by Rumplforskn** [comment]
Not enough memory ? Optimise your ram usage maybe

**Comment by Rumplforskn** [comment]
Not enough memory ? Optimise ram usage might help stop crashes...

**Comment by opa334** [comment]
The fact it happens in unjailbroken mode means it's not an issue with Dopamine.

**Comment by Lazy-Write** [comment]
> Not enough memory ? Optimise ram usage might help stop crashes...

How would I do that?



> The fact it happens in unjailbroken mode means it's not an issue with Dopamine.

It happens when not in a jailbroken state, but when I removed the jailbreak completely the apps work fine. Surely that means it must be to do with Dopamine?

**Comment by opa334** [comment]
> It happens when not in a jailbroken state, but when I removed the jailbreak completely the apps work fine. Surely that means it must be to do with Dopamine?

If it happens while not in a jailbroken state, it means it cannot have anything to do with Dopamine at all.

**Comment by Lazy-Write** [comment]
> > It happens when not in a jailbroken state, but when I removed the jailbreak completely the apps work fine. Surely that means it must be to do with Dopamine?
> 
> If it happens while not in a jailbroken state, it means it cannot have anything to do with Dopamine at all.

I get what you’re saying, but it’s also only happening after jailbreaking with Dopamine?

**Comment by opa334** [comment]
> > > It happens when not in a jailbroken state, but when I removed the jailbreak completely the apps work fine. Surely that means it must be to do with Dopamine?
> > 
> > 
> > If it happens while not in a jailbroken state, it means it cannot have anything to do with Dopamine at all.
> 
> I get what you’re saying, but it’s also only happening after jailbreaking with Dopamine?

Maybe jailbreak detection? You can always try hiding the jailbreak inside Dopamine, even when you're not jailbroken.
