### ISSUE TITLE
Install Trollstore Error

### ISSUE THREAD

**Issue by leiwang168** [opa334/Dopamine#588]
Running on an iPhone12,1 on iOS 15.7.2
Downloading kernel
libgrabkernel2: ERROR: Failed to find a firmware URL!
libgrabkernel2: ERROR: Failed to get firmware URL!
Failed to download kernel
Failed to get kernel
![8F1FCF81-9DA7-45CA-83AF-D6A6EEE34682](https://github.com/opa334/Dopamine/assets/66875428/6209335a-2e65-49be-8c68-397937245e0a)

**Comment by opa334** [comment]
Please report it at https://github.com/alfiecg24/libgrabkernel2

**Comment by alfiecg24** [comment]
@leiwang168 I will try and push out a TrollInstallerX build with a fix in the coming days.

**Comment by cuinskool** [comment]
Same issue with verbose logging. I'm wondering if it has to be updated via OTA to work. I just restored this iPhone 6s using iTunes on Windows. 

![Image](https://github.com/user-attachments/assets/8901aa65-d2ec-40de-a7f2-7eacdd7b4a93)
