### ISSUE TITLE
发生错误 检测到标识符为[org.coolstar.SileoStore]的应用程序存在于 Dopamines 应用目录中("/privatepreboot/9A3A704D9F413383DE87733A7909A68BCAA35782282A113F33A3D3CD906FC1342F71710E18F098C6E09615B7D9585667/dopamine-CEt6qi/procursus/Applications")，但其已被单独安装在系统上，无法继续。

### ISSUE THREAD

**Issue by zzhtsyz** [opa334/Dopamine#589]
![bbe83ae2a92d82912ad039aae53dfac](https://github.com/opa334/Dopamine/assets/15843440/bf9f4935-bf02-4965-9e17-f2fd319f3478)

**Comment by zzhtsyz** [comment]
iOS 15.0.1  13promax

**Comment by opa334** [comment]
looks like the feature to detect duplicate apps works as intended
