### ISSUE TITLE
Error after jailbreak 

### ISSUE THREAD

**Issue by OverWatch-R** [opa334/Dopamine#591]
[
![IMG_5047](https://github.com/opa334/Dopamine/assets/94493115/16189883-fe51-4df3-937c-8a12302aeb62)
](url)

2.0.6
iOS 16,5

**Comment by opa334** [comment]
Did you uninstall libkrw0 yourself?

**Comment by opa334** [comment]
Hopefully fixed in 2.1.7, if not it should now print a more detailed error.
