### ISSUE TITLE
Disable Tweak Injection

### ISSUE THREAD

**Issue by luhgarlicbread** [opa334/Dopamine#594]
Hello, when disabling tweak injection while jailbroken a prompt comes up asking to reboot the userspace, although I may have discovered that a simple respiring achieves the same purpose in a quicker fashion.
Instead of rebooting the userspace right away I hit “later”, and then I restarted the springboard with the option in Dopamine and my tweaks were back. Injected & ready to go.
Do we really need to do a userspace reboot when a reboot of the springboard appears to achieve the same purpose in less time?

Thanks & God bless!
~Ethan

**Comment by opa334** [comment]
No, respringing only enables SpringBoard tweaks, a full userspace reboot is needed to enable tweaks system wide.

**Comment by luhgarlicbread** [comment]
> No, respringing only enables SpringBoard tweaks, a full userspace reboot is needed to enable tweaks system wide.

Had a feeling there was going to be a caveat.
