### ISSUE TITLE
native iOS NFC breaking/nfcd crashing

### ISSUE THREAD

**Issue by dotnickcommaone** [opa334/Dopamine#603]
- [ ] - I've been trying to set up NFC automations on my iPhone,and it doesn't seem to bring up the native iOS NFC reading prompt,and in banking apps (Vietnamese banks uses ID cards to authenticate for transfers) same thing happens,and it's not a hardware issue (Apple Pay and reading tags with Aemulo works),and in logs nfcd is crashing every time the prompt tries to show up

**Comment by dotnickcommaone** [comment]
here's the log: https://drive.google.com/file/d/1-FvkqLcPID6xzq4Vs8Wj4nS_DXydmnV7/view?usp=drivesdk

**Comment by dotnickcommaone** [comment]
well my idiocy found out what was causing it (aemulo),so just scratch that

**Comment by luhgarlicbread** [comment]
> here's the log: https://drive.google.com/file/d/1-FvkqLcPID6xzq4Vs8Wj4nS_DXydmnV7/view?usp=drivesdk

Yo where do u find the Dopamine logs?
