### ISSUE TITLE
Getting Error while installing the Dopamine ipa 2.1.7

### ISSUE THREAD

**Issue by R0g3r-Byte** [opa334/Dopamine#604]
Hi, I am trying to install the ipa on iPhone X, on iOS 16.7.7 but getting an error. I understand the current compatibility is till 16.6.1* but still, is this an expected behaviour of the app.

![Error](https://github.com/opa334/Dopamine/assets/72746463/5ce92ab6-e447-4b18-9b39-08e7b213602b)

**Comment by opa334** [comment]
This is not how you sideload apps and it has nothing to do with Dopamine.
