### ISSUE TITLE
Mount preboot and root r/w

### ISSUE THREAD

**Issue by yakuv0** [opa334/Dopamine#606]
Hello

though palera1n settings is possible to mount the directories, in dopamine the option is not available, any alternative shell commands or future plans to add it in dopamine?!

**Comment by opa334** [comment]
preboot is automatically mounted r/w. Unless you prefer your phone to be paperweight, remounting the rootfs is not something that is possible.

**Comment by yakuv0** [comment]
This elaboration is just to have clarity when possible knowing the tremendous efforts @opa334 provides.

In palera1n (rootless) through the mount directory option, it’s possible to grant access to soft linked directories instead of having same folders in multiple apps and have it synced.

Example: linking safari download folder
‘/var/mobile/Containers/Shared/AppGroup/xxx-xxx-xxx/File Provider Storage/Downloads’ to ‘/var/mobile/Containers/Data/Application/xxx-xxx-xxx/Documents‘

The linked folders would appear in app with read and write permission.
It was noticed that there are actually some recent apps that provides such function within the app it self as (link folder).
