### ISSUE TITLE
Current playing song/music not showing on my car's HUD after jailbreaking / only shows in stock state

### ISSUE THREAD

**Issue by Tex91** [opa334/Dopamine#61]
I have a BMW F30 and I use Spotify and CarPlay all the time. Whenever I am jailbroken, I cannot see the "current playing song" in my Head Up Display, however as soon as I reboot into a non-jailbroken state, the music displays just fine. I don't have any tweaks that could affect this, and I don't have SnowBoard either which I know causes issues with CarPlay in general. Not sure if I'm the only one with that issue but hopefully it gets sorted soon somehow.

**Comment by opa334** [comment]
This should already be fixed in upstream, when 1.0 is out and this is still not fixed, please open another issue.
