### ISSUE TITLE
Watchdog Timeout

### ISSUE THREAD

**Issue by line-Winker** [opa334/Dopamine#612]
![54ec7fadea03669a5e769c95b0e39fa_看图王](https://github.com/user-attachments/assets/1c16ad10-6b6b-450a-a634-1df1f92e6d05)

**Comment by KAGUYA-1137** [comment]
I have same issue.

When the app displays a popup asking if you want to allow it to use Face ID, it freezes for a while and after respringing, the same popup as the line-Winker.
![image](https://github.com/user-attachments/assets/d8b27943-e355-4c84-b7cc-3b41f8ed8996)

**Comment by opa334** [comment]
This is probably caused by a broken tweak.
