### ISSUE TITLE
Jetsam numbers do opposite

### ISSUE THREAD

**Issue by eglacias** [opa334/Dopamine#613]
With the default set to two, more of my apps force close when switched away from (left in background) and do so much quicker instead of staying open.
I never have any problem with things just crashing right away like memory out with this jailbreak, which also awesomely ***runs for more than a month up time with never a single respring or reboot***
I’ve always had problems with iOS constantly kicking out apps that I want to keep open while switching around several apps. 
Changing the number *higher*, for instance, to 4, caused my applications to stop force closing, caused my applications to stay open longer. 8plus A11 3 gig device

The explanation you gave for what the number does could perhaps be made a little clearer?
It seems like the higher, the number, the more memory that’s allowed to be allocated to each application, causing them to stay in memory longer.

**Comment by opa334** [comment]
The system doesn't have infinite memory, if you put the number up higher then other processes will allocate more memory without getting killed and the apps will still be killed when the system runs low on memory.
