### ISSUE TITLE
The latest version seems to break the Snowboard UI

### ISSUE THREAD

**Issue by Gu3hi** [opa334/Dopamine#622]
Dopamine 2.1.7 and the UI theme that used to work normally, now it doesn't work, please check this issue, thank you.
https://pastebin.com/UTmSLTYu

**Comment by opa334** [comment]
Nope, I investigated this crash report and it cannot in any way be caused by the Dopamine update. It's a Snowboard bug and I have sent the details to sparkdev, the Dopamine version you're running shouldn't even affect it.
