### ISSUE TITLE
IOS 15.7.2  reboot random   at 2.2.x version : spin lock ,very frequent  every half day . but 2.09 is ok , can you fix it?

### ISSUE THREAD

**Issue by Jason-2058** [opa334/Dopamine#623]
A15 IOS 15.7.2  reboot random   at 2.2.x version : spin lock ,very frequent  every half day . but 2.09 is ok , can you fix it?

**Comment by opa334** [comment]
placebo

**Comment by h1psta** [comment]
same experience for me, could not pinpoint what version is the last stable but I update Dopamine everytime and the last month I started getting random reboots all the time without changing any tweaks

se 2020, ios 15.3

**Comment by opa334** [comment]
The last stable version is 2.2.2.

**Comment by h1psta** [comment]
i was on 2.2.2. had these crashes on both 2x and 3x multipliers :/ but  actually, i had also started using choicy more aggressively (including on daemons), i will try 2.2.2. with choicy disabled
________________________________

**Comment by h1psta** [comment]
Reporting back, absolutely no restarts on 2.1.7. even with aggressive Choicy usage (disabling injecting into many deamons), 2.2.2. still giving a few restarts per day (both when opening apps or when the phone is idling)

**Comment by Jason-2058** [comment]
> Reporting back, absolutely no restarts on 2.1.7. even with aggressive Choicy usage (disabling injecting into many deamons), 2.2.2. still giving a few restarts per day (both when opening apps or when the phone is idling)

I seem to have found a solution. It has been restarted within 28 days.
