### ISSUE TITLE
Bash segfault due to LANG variable

### ISSUE THREAD

**Issue by polarbub** [opa334/Dopamine#627]
I want to use bash as my shell, but when I run it I get a segfault. Unsetting the `LANG` environmental variable makes bash work propperly as hinted by [this](https://x.com/opa334dev/status/1715115870010151144) tweet, but to unset `LANG` I have to use another shell and then start bash, so I can't set bash as my default shell. On my linux pc with the `LANG` variable set to the same value as on my phone bash works fine. I am on ios 16.3.1 on an iPhone 8. Any ideas on why this happens or how to set the variable correctly for bash on Dopamine?

**Comment by opa334** [comment]
Dopamine doesn't have any involvement in this variable being set. That is done either by the bootstrap or by NewTerm (don't remember), so there is nothing to be done here. Maybe there is some file you can edit to remove it.

The main problem is that Procursus has not been maintained all too much and therefore this bug still hasn't been fixed.
