### ISSUE TITLE
Dopamine version stuck at 2.2.1

### ISSUE THREAD

**Issue by danserks** [opa334/Dopamine#629]
After downloading newest update of dopamine ipa it’s still shows 2.2.1

**Comment by danserks** [comment]
![57512915-C523-4588-8F37-2F58916A7458](https://github.com/user-attachments/assets/471a6bf9-a06b-45b8-b3f1-6db59a373259)

**Comment by notfence** [comment]
+1 iPhone Xr iOS 15.6 RC

**Comment by any444v** [comment]
same, iPhone 6S iOS 15.8.3

**Comment by froyo4u** [comment]
same

**Comment by froyo4u** [comment]
Looking at the code, the build number was never changed but it is updated
