### ISSUE TITLE
NewTerm does not work

### ISSUE THREAD

**Issue by xianfeng596** [opa334/Dopamine#632]
NewTerm shows Session Ended.It still shows this after rejailbreak.

Dopamine 2.2.2
iOS15.7.6 running on iPhone 6s

**Comment by opa334** [comment]
Are you using NewTerm 3 Beta? Cause NewTerm 2 indeed does not work.

**Comment by xianfeng596** [comment]
I am using NewTerm 3 Beta.

**Comment by xianfeng596** [comment]
![askdlkfas](https://github.com/user-attachments/assets/90e375df-3c6e-4b9a-be89-4716c076ba67)

**Comment by harworrell** [comment]
did you figure this out? i’m having the same issue and can’t figure it out

**Comment by ghh-jb** [comment]
Broken permissions of ROOT_PATH_NS@/usr/bin

**Comment by xianfeng596** [comment]
I solved this issue through reinstalling jb
