### ISSUE TITLE
Yellow iPhone 14  on iOS 16.3 (20D50) Downloading Kernel Jailbreak failed with error: Error Domain=JBErrorDomain Code=-1 "Failed to find kernelcache" UserInfo={NSLocalizedDescription=Failed to find kernelcache}

### ISSUE THREAD

**Issue by En2024en** [opa334/Dopamine#635]
Starting Jailbreak (Model: iPhone14,7, Version 16.3 (Build 20D50), Configuration: {removeJailbreak=1, tweakInjection=0, idownload=0, appJIT=0})
Downloading Kernel
Jailbreak failed with error: Error Domain=JBErrorDomain Code=-1 "Failed to find kernelcache" UserInfo={NSLocalizedDescription=Failed to find kernelcache}

[
![IMG_0002](https://github.com/user-attachments/assets/1faf7f57-c83b-4ac9-9ef8-b369d5f125e4)
](url)

**Comment by opa334** [comment]
This specific device / version combo is only supported when you install Dopamine through TrollStore. TrollInstaller X should support it.

**Comment by En2024en** [comment]
> This specific device / version combo is only supported when you install Dopamine through TrollStore. TrollInstaller X should support it.

Yellow iPhone 14 or Yellow iPhone 14 Plus on iOS 16.3 (20D50)

I have this device , can't able to install troll installerx getting error "https://github.com/alfiecg24/TrollInstallerX/issues/33

**Comment by En2024en** [comment]
> This specific device / version combo is only supported when you install Dopamine through TrollStore. TrollInstaller X should support it.

FINALLY its done by this https://trollstore.app/installing-trollhelper-misaka/
