### ISSUE TITLE
Dopamine's dylib injection into the desktop process cannot obtain the target task port

### ISSUE THREAD

**Issue by QuiYou** [opa334/Dopamine#636]
**Dopamine's dylib injection into the desktop process cannot obtain the target task port

The following two methods cannot obtain**

`static mach_port_t getTask(int pid)
{
    task_for_pid(mach_task_self(), pid, &task);
    return task;
}`

`static task_t GetTask(pid_t pid) {
    void *libHandle = dlopen("/usr/lib/system/libsystem_kernel.dylib", RTLD_LAZY);
    if (libHandle) {
        typedef kern_return_t (*task_for_t)(mach_port_name_t target_tport, pid_t pid, mach_port_name_t *t);
        
        task_for_t TaskPort = (task_for_t)dlsym(libHandle, "task_for_pid");
        
        if (TaskPort) {
            kern_return_t kr = TaskPort(mach_task_self(), pid, &task);
            if (kr != KERN_SUCCESS) {
                 NSLog(@"[8888]: get task error: %d", kr);
            }
        }
        
        dlclose(libHandle);
    }
    
    return task;
}`

**Comment by QuiYou** [comment]
error: 5

**Comment by jiuqianqi111** [comment]
显示已越狱，但是图标不显示怎么回事，而且重新越狱试了很多遍也不行，重启手机也不行

**Comment by opa334** [comment]
`task_for_pid` requires the `task_for_pid-allow=true` entitlement to work.
