### ISSUE TITLE
Scp cannot access the application data directory

### ISSUE THREAD

**Issue by w2599** [opa334/Dopamine#65]
When I use winscp to access /private/var/mobile/Containers/Data, it prompts Permission denied. Is this a sandbox permission issue?

**Comment by opa334** [comment]
Procursus binaries are lacking some entitlements, will be fixed soon by them.

**Comment by Sholman81** [comment]
![131430988](https://github.com/opa334/Dopamine/assets/131430988/ed92fa62-7a4d-4ae7-85fa-eb7f0849894c)
![18235760](https://github.com/opa334/Dopamine/assets/131430988/66ca6149-9573-41bd-a3e6-0b74026c7d1e)
![114452622](https://github.com/opa334/Dopamine/assets/131430988/d1797c3e-366d-42fa-ad37-6dfff5ea6639)
![18235760](https://github.com/opa334/Dopamine/assets/131430988/629d647b-9dff-4987-b655-97979e6aa157)
