### ISSUE TITLE
Jailbreak delete my trollstore app registration

### ISSUE THREAD

**Issue by BananeRapeuse** [opa334/Dopamine#652]
Hello, the last week I have try to jailbreak my iPhone 8 on 16.6 with the last version, I was installing Dopamine with trollstore and jailbreak the phone.
When the phone shut down to reboot Jailbroken he has taken more than 1 minute to boot and when I was trying to open sileo it won’t open, also all my apps I have installed with trollstore including it, just won’t open, after this I have reboot the phone and the phone say me something like « The phone reboot due to crach » after that I was forces to refresh app registrations with the persistence helper to be able to open sideloaded apps.

**Comment by opa334** [comment]
This why the persistence helper exists, because the apps stop working when the system reloads the icon cache.
