### ISSUE TITLE
Failed to Jailbreak Error: -6

### ISSUE THREAD

**Issue by sn7d** [opa334/Dopamine#658]
Had v2.1.12 for a while then my device randomly rebooted, saw an update, updated to 2.1.14 then tried to jaulbreak and this popped up:

![IMG_2724](https://github.com/user-attachments/assets/74381aee-c959-4e68-813b-90f17e092ece)
[Dopamine fail to jailbreak.txt](https://github.com/user-attachments/files/17599772/Dopamine.fail.to.jailbreak.txt)

**Comment by sn7d** [comment]
Sorry, v2.2.2.12-v2.2.2.14

**Comment by opa334** [comment]
you're not using the official dopamine, so I cannot help you
