### ISSUE TITLE
Battery drained after replacing charging port flex cable

### ISSUE THREAD

**Issue by Hogeren** [opa334/Dopamine#663]
My phone is iPhone12，ios16.1.2
The charging port flex cable was replaced because the fast charging module was broken.
But after that，the battery drained even airplane mode on overnight.
After I downgrade Dopamine from latest 2.2.2 to 2.0.10，the issue is still reproduced！
After I clear the jailbreak environment，the power consumption get well.
It seems that the issue was reproduced even after reboot. Only get recovery after clear jailbreak env in Dopamine.
![9E614F2C-F6C8-423C-9188-C686E68806A5](https://github.com/user-attachments/assets/c790e69a-b5f9-48b1-a16c-3d5c96709b31)

**Comment by opa334** [comment]
If this happens even after reboot (when not jailbroken), then it is completely impossible for Dopamine to have anything to do with it.

**Comment by Hogeren** [comment]
@opa334 Thanks for your feedback! But I'm confused why the issue only gone with clearing jailbreak.
