### ISSUE TITLE
Injection into the com.apple.WebKit.WebContent process is not possible

### ISSUE THREAD

**Issue by hulovebin** [opa334/Dopamine#669]
"Injection into the com.apple.WebKit.WebContent process is not possible, while injection into other processes works fine. My own injection code is perfectly fine."

**Comment by opa334** [comment]
Yes, injection into WebContent has indeed been disabled on iOS 16 since it's too sandboxed to even contact the jailbreak server, let alone load tweaks.

**Comment by hulovebin** [comment]
thanks
