### ISSUE TITLE
jailbreak not installing?

### ISSUE THREAD

**Issue by catlover42** [opa334/Dopamine#73]
i install the jailbreak and sileo doesnt appear, so i install it again and it get stuck on initialising environment. ive tried respringing and sileo still doesnt turn up, is there a fix for this? im on iphone XR ios 15.4.1

**Comment by Tawnee323** [comment]
Don’t just respiring. Fully reboot after a failed attempt.

**Comment by biggpopps** [comment]
Hello, sorry if my question is not about the topic. I have a iphone 12 on iOS 14.3. Is there any method for me to go to iOS 15.4.1 ? I have saved blobs etcetera.

Thanks

**Comment by Cryptiiiic** [comment]
Jailbreak apps will only show up after a successful jailbreak, you need to make sure it succeeded and didn't reboot to stock.

Please verify
@catlover42

**Comment by Cryptiiiic** [comment]
> Hello, sorry if my question is not about the topic. I have a iphone 12 on iOS 14.3. Is there any method for me to go to iOS 15.4.1 ? I have saved blobs etcetera.
> 
> Thanks

@biggpopps no, not the place to ask either

**Comment by Cryptiiiic** [comment]
No response
