### ISSUE TITLE
Trollstore UICache update breaks Jailbroken icons

### ISSUE THREAD

**Issue by Xernium** [opa334/Dopamine#88]
Exactly as the title says, running uicache in trollstore breaks icons added by Dopamine. I'm not sure if this should be an issue opened here or on the Trollstore repo, so if this is in the wrong please please move the issue, thanks.

**Comment by opa334** [comment]
Yeah because there is no icon cache hook. I tried doing it and almost bootlooped my main device, so that's postponed indefinitely
