### ISSUE TITLE
Apple Pay cards unavailable

### ISSUE THREAD

**Issue by 958ach** [opa334/Dopamine#90]
Cards in Apple Pay unavailable after jailbreaking with Dopamine 1.0 same result when using hide jailbreak - Beta 8 had no issues.

Restarting device into stock allows Apple pay to work normally again although double-click side button needs toggling to enable again
11 Pro Max A13 iOS 15.1

**Comment by ssdsl0126** [comment]
![IMG_0561](https://user-images.githubusercontent.com/35905829/235936742-3358abd5-4b78-4234-82bb-4c781fe589c5.PNG)
Quick transit card has blank setting

**Comment by 958ach** [comment]
Attempts so far:

NOFORKFIX.NOTWEAKS : 4 attempt resulted in no response after userspace reboot 

NOFORKFIX : 4 jailbreak succeeds no cards available in apple pay

NO.FORKFIX.NO.TWEAKS.OLD-PATHRESOLVE: 2/4 success rate jailbreaking appears the 2 successful attempts result userspace reboot then no response - unable to tell if cards available apple pay

**Comment by opa334** [comment]
my bad I think the builds are broken

**Comment by opa334** [comment]
Ok try again now, NO.FORKFIX.NO.TWEAKS.OLD-PATHRESOLVE and NOFORKFIX.NOTWEAKS should work now

**Comment by invalidunit** [comment]
Perhaps the problem stems from Preferenceloader. Just use Choicy to prevent the tweaks from injecting into Settings, and you'll be able to see the original interface.

**Comment by invalidunit** [comment]
> Perhaps the problem stems from Preferenceloader. Just use Choicy to prevent the tweaks from injecting into Settings, and you'll be able to see the original interface.

![D7769F8B-8C1C-4DDA-8C1A-1891EC2585CE](https://user-images.githubusercontent.com/35675770/235967470-f3c107ec-6e71-4d12-bc04-c4fc0a75105d.png)

**Comment by ssdsl0126** [comment]
Based on the latest tests, it has been found that the issue of blank quick transit card settings is caused by the Bioprotect tweak

**Comment by 958ach** [comment]
> Ok try again now, NO.FORKFIX.NO.TWEAKS.OLD-PATHRESOLVE and NOFORKFIX.NOTWEAKS should work now


NO.FORKFIX.NO.TWEAKS.OLD-PATHRESOLVE : cards available in apple Pay

NOFORKFIX.NOTWEAKS : no cards available in apple pay

As I’ve seen it in another reply - bio protect tweak not installed

**Comment by opa334** [comment]
> > Ok try again now, NO.FORKFIX.NO.TWEAKS.OLD-PATHRESOLVE and NOFORKFIX.NOTWEAKS should work now
> 
> NO.FORKFIX.NO.TWEAKS.OLD-PATHRESOLVE : cards available in apple Pay
> 
> NOFORKFIX.NOTWEAKS : no cards available in apple pay
> 
> As I’ve seen it in another reply - bio protect tweak not installed

that doesn't make much sense :/ are you absolutely sure?

**Comment by 958ach** [comment]
> > > Ok try again now, NO.FORKFIX.NO.TWEAKS.OLD-PATHRESOLVE and NOFORKFIX.NOTWEAKS should work now
> > 
> > 
> > NO.FORKFIX.NO.TWEAKS.OLD-PATHRESOLVE : cards available in apple Pay
> > NOFORKFIX.NOTWEAKS : no cards available in apple pay
> > As I’ve seen it in another reply - bio protect tweak not installed
> 
> that doesn't make much sense :/ are you absolutely sure?

I’ll check again I only did each one once I may have got the results mixed

**Comment by 958ach** [comment]
> > > Ok try again now, NO.FORKFIX.NO.TWEAKS.OLD-PATHRESOLVE and NOFORKFIX.NOTWEAKS should work now
> > 
> > 
> > NO.FORKFIX.NO.TWEAKS.OLD-PATHRESOLVE : cards available in apple Pay
> > NOFORKFIX.NOTWEAKS : no cards available in apple pay
> > As I’ve seen it in another reply - bio protect tweak not installed
> 
> that doesn't make much sense :/ are you absolutely sure?

Just tried noforkfix.notweaks again cards available 


checking nopathresolves again now back in 5

**Comment by 958ach** [comment]
> must be a tweak issue then, try again in 1.0.2

No joy in 1.0.2 I’m going to remove jailbreak in dopamine and check with no tweaks

**Comment by 958ach** [comment]
> Since wipe fixed the issue, its a tweak's fault and not dopamine's so labeled as invalid

Odd thing is I’ve reinstalled the same tweaks but have been unable to replicate
