### ISSUE TITLE
Jailbreak issue

### ISSUE THREAD

**Issue by Cedo9999** [opa334/Dopamine#93]
When I jailbroke for the first time everything went as expected exempt for all my old tweaks(that I installed via fugu15) were gone, I didn't think much of it and I reinstalled them, after respringing via Sileo, my phone crashed, so I jailbroke again. When I did my phone did a user space reboot to finalise the jailbreak,but when it did instead of booting up my phone showed me the Apple logo for an infinite amount of time, not booting up like it always had, effectively giving me a real scare. Please help me

**Comment by opa334** [comment]
Can you access your device via SSH? If not, do a hard reset and hope for the best

**Comment by Cedo9999** [comment]
Wdym a hard reset? Do you mean reset the jailbreak files? If so I already tried.

**Comment by opa334** [comment]
Try again in 1.0.2

**Comment by Cedo9999** [comment]
And I just managed to reboot my phone regularly after trying to force restart it for 30 straight.

**Comment by Cedo9999** [comment]
Thanks! I'll see what I can do!

**Comment by Cedo9999** [comment]
I attempted to jailbreak(without resetting/uninstalling any of the jailbreak files) with no success

**Comment by Cedo9999** [comment]
I reset everything and retail broke and everyone seems to work fine now!
