### ISSUE TITLE
automatically restart

### ISSUE THREAD

**Issue by TiAmo789** [opa334/Dopamine#94]
{"bug_type":"210","timestamp":"2023-05-04 00:18:06.00 +0800","os_version":"iPhone OS 15.4.1 (19E258)","incident_id":"434E4314-B059-403C-8870-DFD84A7122EE"}
{
  "build" : "iPhone OS 15.4.1 (19E258)",
  "product" : "iPhone14,2",
  "socId" : "0x00008110",
  "kernel" : "Darwin Kernel Version 21.4.0: Mon Feb 21 21:27:57 PST 2022; root:xnu-8020.102.3~1\/RELEASE_ARM64_T8110",
  "incident" : "434E4314-B059-403C-8870-DFD84A7122EE",
  "crashReporterKey" : "d8e861e94bb2a7b96ec739501f0147c1461a6da8",
  "date" : "2023-05-04 00:18:06.26 +0800",
  "panicString" : "panic(cpu 1 caller 0xfffffff022254290): userspace watchdog timeout: no successful checkins from thermalmonitord in 180 seconds\nservice returned not alive with context : unresponsive dispatch queue(s): com.apple.main-thread \nservice: backboardd, total successful checkins since wake (960 seconds ago): 97, last successful checkin: 0 seconds ago\nservice: SpringBoard, total successful checkins since wake (960 seconds ago): 96, last successful checkin: 0 seconds ago\nservice: mediaserverd, total successful checkins since wake (960 seconds ago): 97, last successful checkin: 0 seconds ago\nservice: logd, total successful checkins since wake (960 seconds ago): 97, last successful checkin: 0 seconds ago\nservice: thermalmonitord, total successful checkins since wake (960 seconds ago): 79, last successful checkin: 180 seconds ago\nservice: runningboardd, total successful checkins since wake (960 seconds ago): 97, last successful checkin: 0 seconds ago\nservice: wifid, total successful checkins since wake (960 seconds ago): 97, last successful checkin: 0 seconds ago\n\nDebugger message: panic\nMemory ID: 0xff\nOS release type: User\nOS version: 19E258\nKernel version: Darwin Kernel Version 21.4.0: Mon Feb 21 21:27:57 PST 2022; root:xnu-8020.102.3~1\/RELEASE_ARM64_T8110\nKernel UUID: E5C6FB6F-07CE-3AEE-8400-99EC7DEB9B6B\niBoot version: iBoot-7459.102.5\nsecure boot?: YES\nPaniclog version: 13\nKernel slide:      0x0000000018724000\nKernel text base:  

{"bug_type":"115","timestamp":"2023-05-04 00:18:07.00 +0800","name":"Reset count","os_version":"iPhone OS 15.4.1 (19E258)","incident_id":"2D03F1F2-D2DB-410B-9C26-866CAD9A8E11"}
Incident Identifier: 2D03F1F2-D2DB-410B-9C26-866CAD9A8E11
CrashReporter Key:   d8e861e94bb2a7b96ec739501f0147c1461a6da8
Date: 2023-05-04 00:18:07.92 +0800
Reset count: 1
Boot failure count: 0
Boot faults: 
Boot stage: 0
Boot app: 68573167

**Comment by TiAmo789** [comment]
![image](https://user-images.githubusercontent.com/127301869/235979179-c6ed5f0b-fb69-4b98-b439-d6522311d928.jpeg)

**Comment by Cryptiiiic** [comment]
@TiAmo789 does this happen on version 1.0.2? show proof you updated

**Comment by TiAmo789** [comment]
![image](https://user-images.githubusercontent.com/127301869/236283501-12c1666d-cfab-48f6-9d03-0c087bf63672.png)

**Comment by TiAmo789** [comment]
![image](https://user-images.githubusercontent.com/127301869/236283590-4ebc8af0-77d9-4d02-8f86-aa764fcf3b97.png)![正在上传 236283605...]

**Comment by TiAmo789** [comment]
![image](https://user-images.githubusercontent.com/127301869/236284140-d4885580-47e1-4476-9158-f4cdcd3d08db.png)

**Comment by opa334** [comment]
This is a device issue when some hardware component is broken. A friend of mine has it too. This happens on stock aswell.
