### ISSUE TITLE
Connect AirPodsPor to use the pink screen to shut down.

### ISSUE THREAD

**Issue by 532355805** [opa334/Dopamine#99]
Connect AirPodsPor to use the pink screen to shut down.

**Comment by Cryptiiiic** [comment]
This seems like a bad translation, I don't understand at all.
@532355805

**Comment by 532355805** [comment]
When the phone is connected to AirPodsPor, the phone will freeze.

**Comment by opa334** [comment]
Can't reproduce

**Comment by 532355805** [comment]
> 

This seems like a bad translation, I don't understand at all.
